### ISSUE TITLE
多模块环境下的继承问题

### ISSUE THREAD

**Issue by jingdor** [laruence/yaf#103]
application  文件目录如下 
│  bootstrap.php
├─controllers
├─library
├─models
├─modules
│  ├─Backend
│  │  ├─controllers
│  │  │      Index.php
│  │  │      Base.php
│  │  └─views
│  ├─Frontend
└─views

Base.php 文件如下

``` php
<?php
class BaseController extends Yaf_Controller_Abstract {
    public  function init(){


    }

    public  function  indexAction(){
        exit();
    }
}
```

Index.php 文件如下：

``` php
class IndexController extends Backend_BaseController{
   public function indexAction() {//默认Action
        echo "test";
        exit();
   }
}
```

我想backend 模块下面的 index 控制器  继承 backend模块下面的 Base控制  我需要怎么写？

**Comment by loncool** [comment]
框架默认不支持的， yaf的模块只是路由用的。 不管自动加载模块下文件。

**Comment by itsmikej** [comment]
简单点的话可以require
