### ISSUE TITLE
URL arguments will not work if there is less than 2.

### ISSUE THREAD

**Issue by undeadindustries** [laruence/yaf#131]
I'm not sure if this is a bug, or by design. If it is by design, would you mind a quick explanation why it is designed that way? Thanks!

If you want to create a route that uses the first argument as the action, you must also have a second argument.

This will work:
$config = array(
        "name" => array(
           "type"  => "rewrite",  
           "match" => "/user-list/:a/:id", //match only /user-list/*
           "route" => array(
               'controller' => "user",   //route to user controller,
               'action'     => ":a",     //route to :a action
           ),
        ),
    );

However, This will  result in "no :aAction found" error.

$config = array(
        "name" => array(
           "type"  => "rewrite",  
           "match" => "/user-list/:a", //match only /user-list/*
           "route" => array(
               'controller' => "user",   //route to user controller,
               'action'     => ":a",     //route to :a action
           ),
        ),
    );

Why is the second ":id" argument required? Or is this a bug?

p.s. I emailed quickly with Laruence about this. but it's probably better to discuss it here...

**Comment by bosiam** [comment]
@zxcvdavid 
按照你的步骤安装依然报错了，“IS_CONSTANT_ARRAY” 这个问题应该已经修复了的，
帮忙诊断下，谢谢。
description
------------------
/usr/local/nginx/html/yaf-2.3.2/yaf_config.c: In function ‘yaf_config_zval_dtor’:
/usr/local/nginx/html/yaf-2.3.2/yaf_config.c:81: error: ‘IS_CONSTANT_ARRAY’ undeclared (first use in this function)
/usr/local/nginx/html/yaf-2.3.2/yaf_config.c:81: error: (Each undeclared identifier is reported only once
/usr/local/nginx/html/yaf-2.3.2/yaf_config.c:81: error: for each function it appears in.)
/usr/local/nginx/html/yaf-2.3.2/yaf_config.c: In function ‘yaf_config_ini_zval_persistent’:
/usr/local/nginx/html/yaf-2.3.2/yaf_config.c:183: error: ‘IS_CONSTANT_ARRAY’ undeclared (first use in this function)
/usr/local/nginx/html/yaf-2.3.2/yaf_config.c: In function ‘yaf_config_ini_zval_losable’:
/usr/local/nginx/html/yaf-2.3.2/yaf_config.c:222: error: ‘IS_CONSTANT_ARRAY’ undeclared (first use in this function)
make: *** [yaf_config.lo] Error 1

以下是全部信息：
-----------------
[root@runnging_stone html]# cd yaf-2.3.2
[root@runnging_stone yaf-2.3.2]# phpize 
Configuring for:
PHP Api Version:         20131106
Zend Module Api No:      20131226
Zend Extension Api No:   220131226
[root@runnging_stone yaf-2.3.2]# ./configure 
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for a sed that does not truncate output... /bin/sed
checking for cc... cc
checking for C compiler default output file name... a.out
checking whether the C compiler works... yes
checking whether we are cross compiling... no
checking for suffix of executables... 
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether cc accepts -g... yes
checking for cc option to accept ISO C89... none needed
checking how to run the C preprocessor... cc -E
checking for icc... no
checking for suncc... no
checking whether cc understands -c and -o together... yes
checking for system library directory... lib
checking if compiler supports -R... no
checking if compiler supports -Wl,-rpath,... yes
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking target system type... x86_64-unknown-linux-gnu
checking for PHP prefix... /usr/local/php
checking for PHP includes... -I/usr/local/php/include/php -I/usr/local/php/include/php/main -I/usr/local/php/include/php/TSRM -I/usr/local/php/include/php/Zend -I/usr/local/php/include/php/ext -I/usr/local/php/include/php/ext/date/lib
checking for PHP extension directory... /usr/local/php/lib/php/extensions/no-debug-non-zts-20131226
checking for PHP installed headers prefix... /usr/local/php/include/php
checking if debug is enabled... no
checking if zts is enabled... no
checking for re2c... no
configure: WARNING: You will need re2c 0.13.4 or later if you want to regenerate PHP parsers.
checking for gawk... gawk
checking whether to enable yaf support... yes, shared
checking PHP version... 5.6.5, ok
checking for ld used by cc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for /usr/bin/ld option to reload object files... -r
checking for BSD-compatible nm... /usr/bin/nm -B
checking whether ln -s works... yes
checking how to recognize dependent libraries... pass_all
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking dlfcn.h usability... yes
checking dlfcn.h presence... yes
checking for dlfcn.h... yes
checking the maximum length of command line arguments... 1966080
checking command to parse /usr/bin/nm -B output from cc object... ok
checking for objdir... .libs
checking for ar... ar
checking for ranlib... ranlib
checking for strip... strip
checking if cc supports -fno-rtti -fno-exceptions... no
checking for cc option to produce PIC... -fPIC
checking if cc PIC flag -fPIC works... yes
checking if cc static flag -static works... no
checking if cc supports -c -o file.o... yes
checking whether the cc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... no

creating libtool
appending configuration tag "CXX" to libtool
configure: creating ./config.status
config.status: creating config.h
[root@runnging_stone yaf-2.3.2]# make install
/bin/sh /usr/local/nginx/html/yaf-2.3.2/libtool --mode=compile cc  -I. -I/usr/local/nginx/html/yaf-2.3.2 -DPHP_ATOM_INC -I/usr/local/nginx/html/yaf-2.3.2/include -I/usr/local/nginx/html/yaf-2.3.2/main -I/usr/local/nginx/html/yaf-2.3.2 -I/usr/local/php/include/php -I/usr/local/php/include/php/main -I/usr/local/php/include/php/TSRM -I/usr/local/php/include/php/Zend -I/usr/local/php/include/php/ext -I/usr/local/php/include/php/ext/date/lib  -DHAVE_CONFIG_H  -g -O2   -c /usr/local/nginx/html/yaf-2.3.2/yaf.c -o yaf.lo 
mkdir .libs
 cc -I. -I/usr/local/nginx/html/yaf-2.3.2 -DPHP_ATOM_INC -I/usr/local/nginx/html/yaf-2.3.2/include -I/usr/local/nginx/html/yaf-2.3.2/main -I/usr/local/nginx/html/yaf-2.3.2 -I/usr/local/php/include/php -I/usr/local/php/include/php/main -I/usr/local/php/include/php/TSRM -I/usr/local/php/include/php/Zend -I/usr/local/php/include/php/ext -I/usr/local/php/include/php/ext/date/lib -DHAVE_CONFIG_H -g -O2 -c /usr/local/nginx/html/yaf-2.3.2/yaf.c  -fPIC -DPIC -o .libs/yaf.o
/bin/sh /usr/local/nginx/html/yaf-2.3.2/libtool --mode=compile cc  -I. -I/usr/local/nginx/html/yaf-2.3.2 -DPHP_ATOM_INC -I/usr/local/nginx/html/yaf-2.3.2/include -I/usr/local/nginx/html/yaf-2.3.2/main -I/usr/local/nginx/html/yaf-2.3.2 -I/usr/local/php/include/php -I/usr/local/php/include/php/main -I/usr/local/php/include/php/TSRM -I/usr/local/php/include/php/Zend -I/usr/local/php/include/php/ext -I/usr/local/php/include/php/ext/date/lib  -DHAVE_CONFIG_H  -g -O2   -c /usr/local/nginx/html/yaf-2.3.2/yaf_application.c -o yaf_application.lo 
 cc -I. -I/usr/local/nginx/html/yaf-2.3.2 -DPHP_ATOM_INC -I/usr/local/nginx/html/yaf-2.3.2/include -I/usr/local/nginx/html/yaf-2.3.2/main -I/usr/local/nginx/html/yaf-2.3.2 -I/usr/local/php/include/php -I/usr/local/php/include/php/main -I/usr/local/php/include/php/TSRM -I/usr/local/php/include/php/Zend -I/usr/local/php/include/php/ext -I/usr/local/php/include/php/ext/date/lib -DHAVE_CONFIG_H -g -O2 -c /usr/local/nginx/html/yaf-2.3.2/yaf_application.c  -fPIC -DPIC -o .libs/yaf_application.o
/bin/sh /usr/local/nginx/html/yaf-2.3.2/libtool --mode=compile cc  -I. -I/usr/local/nginx/html/yaf-2.3.2 -DPHP_ATOM_INC -I/usr/local/nginx/html/yaf-2.3.2/include -I/usr/local/nginx/html/yaf-2.3.2/main -I/usr/local/nginx/html/yaf-2.3.2 -I/usr/local/php/include/php -I/usr/local/php/include/php/main -I/usr/local/php/include/php/TSRM -I/usr/local/php/include/php/Zend -I/usr/local/php/include/php/ext -I/usr/local/php/include/php/ext/date/lib  -DHAVE_CONFIG_H  -g -O2   -c /usr/local/nginx/html/yaf-2.3.2/yaf_bootstrap.c -o yaf_bootstrap.lo 
 cc -I. -I/usr/local/nginx/html/yaf-2.3.2 -DPHP_ATOM_INC -I/usr/local/nginx/html/yaf-2.3.2/include -I/usr/local/nginx/html/yaf-2.3.2/main -I/usr/local/nginx/html/yaf-2.3.2 -I/usr/local/php/include/php -I/usr/local/php/include/php/main -I/usr/local/php/include/php/TSRM -I/usr/local/php/include/php/Zend -I/usr/local/php/include/php/ext -I/usr/local/php/include/php/ext/date/lib -DHAVE_CONFIG_H -g -O2 -c /usr/local/nginx/html/yaf-2.3.2/yaf_bootstrap.c  -fPIC -DPIC -o .libs/yaf_bootstrap.o
/bin/sh /usr/local/nginx/html/yaf-2.3.2/libtool --mode=compile cc  -I. -I/usr/local/nginx/html/yaf-2.3.2 -DPHP_ATOM_INC -I/usr/local/nginx/html/yaf-2.3.2/include -I/usr/local/nginx/html/yaf-2.3.2/main -I/usr/local/nginx/html/yaf-2.3.2 -I/usr/local/php/include/php -I/usr/local/php/include/php/main -I/usr/local/php/include/php/TSRM -I/usr/local/php/include/php/Zend -I/usr/local/php/include/php/ext -I/usr/local/php/include/php/ext/date/lib  -DHAVE_CONFIG_H  -g -O2   -c /usr/local/nginx/html/yaf-2.3.2/yaf_dispatcher.c -o yaf_dispatcher.lo 
 cc -I. -I/usr/local/nginx/html/yaf-2.3.2 -DPHP_ATOM_INC -I/usr/local/nginx/html/yaf-2.3.2/include -I/usr/local/nginx/html/yaf-2.3.2/main -I/usr/local/nginx/html/yaf-2.3.2 -I/usr/local/php/include/php -I/usr/local/php/include/php/main -I/usr/local/php/include/php/TSRM -I/usr/local/php/include/php/Zend -I/usr/local/php/include/php/ext -I/usr/local/php/include/php/ext/date/lib -DHAVE_CONFIG_H -g -O2 -c /usr/local/nginx/html/yaf-2.3.2/yaf_dispatcher.c  -fPIC -DPIC -o .libs/yaf_dispatcher.o
/bin/sh /usr/local/nginx/html/yaf-2.3.2/libtool --mode=compile cc  -I. -I/usr/local/nginx/html/yaf-2.3.2 -DPHP_ATOM_INC -I/usr/local/nginx/html/yaf-2.3.2/include -I/usr/local/nginx/html/yaf-2.3.2/main -I/usr/local/nginx/html/yaf-2.3.2 -I/usr/local/php/include/php -I/usr/local/php/include/php/main -I/usr/local/php/include/php/TSRM -I/usr/local/php/include/php/Zend -I/usr/local/php/include/php/ext -I/usr/local/php/include/php/ext/date/lib  -DHAVE_CONFIG_H  -g -O2   -c /usr/local/nginx/html/yaf-2.3.2/yaf_exception.c -o yaf_exception.lo 
 cc -I. -I/usr/local/nginx/html/yaf-2.3.2 -DPHP_ATOM_INC -I/usr/local/nginx/html/yaf-2.3.2/include -I/usr/local/nginx/html/yaf-2.3.2/main -I/usr/local/nginx/html/yaf-2.3.2 -I/usr/local/php/include/php -I/usr/local/php/include/php/main -I/usr/local/php/include/php/TSRM -I/usr/local/php/include/php/Zend -I/usr/local/php/include/php/ext -I/usr/local/php/include/php/ext/date/lib -DHAVE_CONFIG_H -g -O2 -c /usr/local/nginx/html/yaf-2.3.2/yaf_exception.c  -fPIC -DPIC -o .libs/yaf_exception.o
/bin/sh /usr/local/nginx/html/yaf-2.3.2/libtool --mode=compile cc  -I. -I/usr/local/nginx/html/yaf-2.3.2 -DPHP_ATOM_INC -I/usr/local/nginx/html/yaf-2.3.2/include -I/usr/local/nginx/html/yaf-2.3.2/main -I/usr/local/nginx/html/yaf-2.3.2 -I/usr/local/php/include/php -I/usr/local/php/include/php/main -I/usr/local/php/include/php/TSRM -I/usr/local/php/include/php/Zend -I/usr/local/php/include/php/ext -I/usr/local/php/include/php/ext/date/lib  -DHAVE_CONFIG_H  -g -O2   -c /usr/local/nginx/html/yaf-2.3.2/yaf_config.c -o yaf_config.lo 
 cc -I. -I/usr/local/nginx/html/yaf-2.3.2 -DPHP_ATOM_INC -I/usr/local/nginx/html/yaf-2.3.2/include -I/usr/local/nginx/html/yaf-2.3.2/main -I/usr/local/nginx/html/yaf-2.3.2 -I/usr/local/php/include/php -I/usr/local/php/include/php/main -I/usr/local/php/include/php/TSRM -I/usr/local/php/include/php/Zend -I/usr/local/php/include/php/ext -I/usr/local/php/include/php/ext/date/lib -DHAVE_CONFIG_H -g -O2 -c /usr/local/nginx/html/yaf-2.3.2/yaf_config.c  -fPIC -DPIC -o .libs/yaf_config.o
/usr/local/nginx/html/yaf-2.3.2/yaf_config.c: In function ‘yaf_config_zval_dtor’:
/usr/local/nginx/html/yaf-2.3.2/yaf_config.c:81: error: ‘IS_CONSTANT_ARRAY’ undeclared (first use in this function)
/usr/local/nginx/html/yaf-2.3.2/yaf_config.c:81: error: (Each undeclared identifier is reported only once
/usr/local/nginx/html/yaf-2.3.2/yaf_config.c:81: error: for each function it appears in.)
/usr/local/nginx/html/yaf-2.3.2/yaf_config.c: In function ‘yaf_config_ini_zval_persistent’:
/usr/local/nginx/html/yaf-2.3.2/yaf_config.c:183: error: ‘IS_CONSTANT_ARRAY’ undeclared (first use in this function)
/usr/local/nginx/html/yaf-2.3.2/yaf_config.c: In function ‘yaf_config_ini_zval_losable’:
/usr/local/nginx/html/yaf-2.3.2/yaf_config.c:222: error: ‘IS_CONSTANT_ARRAY’ undeclared (first use in this function)
make: *** [yaf_config.lo] Error 1
