### ISSUE TITLE
XP下出现 Class 'Yaf_Application' not found

### ISSUE THREAD

**Issue by shaohao2014** [laruence/yaf#152]
按照教程将php_yaf.dll拷贝到 php\ext 目录，之后将templates文件夹拷贝纸htdocs目录，运行之后出现
Fatal error: Class 'Yaf_Application' not found in 。求解，嘻嘻

**Comment by shaohao2014** [comment]
windows xp 下如何重启php呢？

**Comment by zxcvdavid** [comment]
@shaohao2014 :
1. Fatal error: Class 'Yaf_Application' not found in xxxx，
 1. 检查phpinfo中有没有yaf加载信息 
 2. 检查php.ini中有没有加入extension= MODULES_PATH(扩展路径)\yaf.dll  
 3. 有没有重启web server

2. 一般windows上的部署只需要重启相应的web server即可.

btw: 这些其实都可以很容易baidu到..所以以后尽量在search不到的时候再提问会对你好一些..

**Comment by shaohao2014** [comment]
@zxcvdavid 
1、php -m | grep yaf后显示yaf ；
2、php.ini中已经加入 extension=php_yaf.dll ；
3、nginx -s stop ；重启nginx后“Class 'Yaf_Application' not found”错误依旧。
4、我在这里提问前先search了github的issues，没有搜到Class 'Yaf_Application' not found，之后google“Class 'Yaf_Application' not found”搜到寥寥的几条内容，依旧找不到解决方案。最后才在这里提问了。嘻嘻。。。

**Comment by zxcvdavid** [comment]
看下你webserver下phpinfo()里的php和你cli下面的php到底是不是同一个php..

**Comment by shaohao2014** [comment]
1、我的服务器是ngnix，怎么看phpinfo()？
2、cli下的php怎么看？
我是菜鸟，见笑了！嘻嘻。。。

**Comment by zxcvdavid** [comment]
1. https://www.google.com/?gws_rd=ssl#newwindow=1&q=phpinfo%E6%80%8E%E4%B9%88%E7%9C%8B

2. https://www.google.com/?gws_rd=ssl#newwindow=1&q=cli+php%E7%89%88%E6%9C%AC

我帮你google了

**Comment by shaohao2014** [comment]
phpinfo()和php -v 显示的都是5.4.19，兄弟。。。

**Comment by shaohao2014** [comment]
另外，yaf和thinkphp有啥本质的区别？我以前用过thinkphp，看过yaf的源码目录结构后，感觉和thinkphp比较像，综合起来，感觉thinkphp比较好用好上手一点，性能差别上没有看过yaf和thinkphp的对比。

**Comment by wuleying** [comment]
大TP确实是天下无敌。

**Comment by hehexianshi** [comment]
其实我也认为 yaf 和thinkphp 挺像的  就想 php 和c 挺像的一样, 因为他们都是用来写代码。
但是我由衷的建议你 还是别做程序了 真的 这个不太适合你

**Comment by jingdor** [comment]
thnikphp是什么？

**Comment by xiaojiangang** [comment]
PHP是世界上最好的语言。
![wx1s1xdv_crwkb_copb kef](https://cloud.githubusercontent.com/assets/2449891/6143580/5812bbe0-b206-11e4-8d7b-e5cf81edcf22.gif)

**Comment by oyjq** [comment]
tp是最好的PHP框架

**Comment by laruence** [comment]
你们别闹!

**Comment by shaohao2014** [comment]
鸟哥来啦，太兴奋啦！嘻嘻

**Comment by shaohao2014** [comment]
@laruence ，
你抽空帮我解决一下我遇到的问题吧，嘻嘻

**Comment by shaohao2014** [comment]
@hehexianshi ，好的，本来兄弟就是业余选手。

**Comment by laruence** [comment]
windows下不熟

**Comment by shaohao2014** [comment]
windows下就说明不专业，嘻嘻。感谢啦

**Comment by laruence** [comment]
-_#, 真的不熟, 不过, 貌似, 好像, 我听过, 你需要把yaf.dll copy到system32下

**Comment by DeeJaVu** [comment]
WHAT THE FUCK IS THIS FUCKING SHIT

write in english so other people can understand why the fuck this fucking Yaf_Application is not found

i am wasting my time looking for this fucking issue

**Comment by ciwl** [comment]
linux 下出现这个问题呢？

**Comment by laruence** [comment]
@ciwl 说明你没安装好

**Comment by laruence** [comment]
@DeeJaVu I am not familiar with Windows, but I heard about that there could be some errors if you don't place the yaf.dll under system32/ folder on windows. please try to copy the yaf.dll into system32 folder.
