### ISSUE TITLE
编译安装在./configure一步 提示 failed to detect PHP version, please report

### ISSUE THREAD

**Issue by nihaibao** [laruence/yaf#156]
php -v =>
PHP 5.6.3
phpize -v =>
PHP Api Version:         20131106
Zend Module Api No:      20131226
Zend Extension Api No:   220131226
环境 OS X 10.10.2 XAMPP yaf试了两个版本 2.2.9 和 2.3.3 都是一样的错误
编译安装swoole是没问题的

**Comment by laruence** [comment]
你能把整个configure的时候的输出贴出来么, 我测试没问题啊

**Comment by nihaibao** [comment]
EllipsisdeMacBook-Pro:php-yaf-master ellipsis$ ./configure --with-php-config=/Applications/XAMPP/bin/php-config

checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for a sed that does not truncate output... /usr/bin/sed
checking for cc... cc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether cc accepts -g... yes
checking for cc option to accept ISO C89... none needed
checking how to run the C preprocessor... cc -E
checking for icc... no
checking for suncc... no
checking whether cc understands -c and -o together... yes
checking for system library directory... lib
checking if compiler supports -R... no
checking if compiler supports -Wl,-rpath,... yes
checking build system type... x86_64-apple-darwin14.1.0
checking host system type... x86_64-apple-darwin14.1.0
checking target system type... x86_64-apple-darwin14.1.0
checking for PHP prefix... /Applications/XAMPP/xamppfiles
checking for PHP includes... -I/Applications/XAMPP/xamppfiles/include/php -I/Applications/XAMPP/xamppfiles/include/php/main -I/Applications/XAMPP/xamppfiles/include/php/TSRM -I/Applications/XAMPP/xamppfiles/include/php/Zend -I/Applications/XAMPP/xamppfiles/include/php/ext -I/Applications/XAMPP/xamppfiles/include/php/ext/date/lib
checking for PHP extension directory... /Applications/XAMPP/xamppfiles/lib/php/extensions/no-debug-non-zts-20131226
checking for PHP installed headers prefix... /Applications/XAMPP/xamppfiles/include/php
checking if debug is enabled... no
checking if zts is enabled... no
checking for re2c... no
configure: WARNING: You will need re2c 0.13.4 or later if you want to regenerate PHP parsers.
checking for gawk... no
checking for nawk... no
checking for awk... awk
checking if awk is broken... no
checking whether to enable yaf support... yes, shared
checking PHP version... Unknown option: n
Usage: head [-options] <url>...
    -m <method>   use method for the request (default is 'HEAD')
    -f            make request even if head believes method is illegal
    -b <base>     Use the specified URL as base
    -t <timeout>  Set timeout value
    -i <time>     Set the If-Modified-Since header on the request
    -c <conttype> use this content-type for POST, PUT, CHECKIN
    -a            Use text mode for content I/O
    -p <proxyurl> use this as a proxy
    -P            don't load proxy settings from environment
    -H <header>   send this HTTP header (you can specify several)

    -u            Display method and URL before any response
    -U            Display request headers (implies -u)
    -s            Display response status code
    -S            Display response status chain
    -e            Display response headers
    -d            Do not display content
    -o <format>   Process HTML content in various ways

    -v            Show program version
    -h            Print this message

    -x            Extra debugging output
configure: error: failed to detect PHP version, please report

**Comment by laruence** [comment]
hmm, 你的本地head是个啥命令......

**Comment by nihaibao** [comment]
EllipsisdeMacBook-Pro:php-yaf-master ellipsis$ head
Usage: head [-options] <url>...
    -m <method>   use method for the request (default is 'HEAD')
    -f            make request even if head believes method is illegal
    -b <base>     Use the specified URL as base
    -t <timeout>  Set timeout value
    -i <time>     Set the If-Modified-Since header on the request
    -c <conttype> use this content-type for POST, PUT, CHECKIN
    -a            Use text mode for content I/O
    -p <proxyurl> use this as a proxy
    -P            don't load proxy settings from environment
    -H <header>   send this HTTP header (you can specify several)

    -u            Display method and URL before any response
    -U            Display request headers (implies -u)
    -s            Display response status code
    -S            Display response status chain
    -e            Display response headers
    -d            Do not display content
    -o <format>   Process HTML content in various ways

    -v            Show program version
    -h            Print this message

    -x            Extra debugging output

**Comment by winkexp** [comment]
把错误的head文件暂时改名或者修改你的$PATH搜索顺序，，，XAMPP带了个head在它的bin里面

wenhedeMacBook-Pro:bin wayne$ which head
/Applications/XAMPP/bin/head
wenhedeMacBook-Pro:bin wayne$ sudo mv head header
wenhedeMacBook-Pro:bin wayne$ which head
/usr/bin/head
wenhedeMacBook-Pro:bin wayne$

**Comment by tyoriisu** [comment]
我遇到了这个问题，用了楼上 @winkexp 的办法解决了
不过我which head没问题，返回是/usr/bin/head
which HEAD返回的是XAMPP里的HEAD，名字改掉就成功了
