### ISSUE TITLE
关于 Yaf_Route_Rewrite路由的使用

### ISSUE THREAD

**Issue by mhsun1992** [laruence/yaf#169]
例如该URL：
https://github.com/laruence/php-yaf/issues

路由配置：
routes.rewrite.type="rewrite"
routes.rewrite.match="/:user_name/:repo_name/issues"
routes.rewrite.route.controller=repo
routes.rewrite.route.action=issues

访问路径 /laruence/php-yaf/issues 正常，被路由到 repo/issues。

问题来了：
当我访问 /laruence/php-yaf/issueserror 的时候 issueserror 也会匹配 issues 成功然后被路由到 repo/issues

我的疑问：
文档中的描述场景是 /product/:ident/name1/value1/name2/value2 ，在段ident后直接跟params了，所以我想确认下例如这样的URL路径 /laruence/php-yaf/issueserror 被路由到到 repo/issues 是否是正确的匹配结果？

**Comment by chenyachao** [comment]
routes.rewrite.match="/:user_name/:repo_name/issues$"

试试这样～～

**Comment by Red-wolf-s-husband** [comment]
楼上，你的头像亮了！

**Comment by mhsun1992** [comment]
@chenyachao @Red-wolf-s-husband 你两撞头了

**Comment by Red-wolf-s-husband** [comment]
@mhsun1992 你说在全球最大的同性交友网上遇到这样的情况的概率是多大？

**Comment by chenyachao** [comment]
@Red-wolf-s-husband 头像分辨率差评～
