### ISSUE TITLE
只有自己调用response方法，setHeader的值才会输出

### ISSUE THREAD

**Issue by SyuTingSong** [laruence/yaf#181]
我尝试按 http://php.net/manual/en/yaf-response-abstract.setheader.php 中的例子写`setHeader`输出一个header，发现自己在action中调用response之后header能正常输出，但是yaf框架会把body再重复输出一次。

我放弃了自己主动调用response方法，setHeader的内容就不输出了。

    public function listAction() {
        $user_id = $this->session->get('user_id');
        if (empty($user_id)) {
            $this->getResponse()->setHeader('Content-Type', 'application/json');
            $this->getResponse()->appendBody(json_encode([
                'msg' => 'Login required',
            ]));
        }
    }

当我在Bootstrap中调用`$dispatcher->returnResponse(true)`之后，并在index.php中把 `$application->bootstrap()->run();`改为`$application->bootstrap()->run()->response();`，这个Header才能正常输出，并且Body不会重复。

为什么yaf自动response的时候不会输出header呢？是我调用方法不对还是出了个bug？

**Comment by laruence** [comment]
应该已经修复了, 请尝试使用用主干代码....

**Comment by Red-wolf-s-husband** [comment]
@laruence 你在代码里下毒！
我clean 过n次，重新编译安装n次。

![image](https://cloud.githubusercontent.com/assets/4018764/9292928/eb5107aa-4445-11e5-82bd-07c40f0ab33d.png)

layout asm
![image](https://cloud.githubusercontent.com/assets/4018764/9292932/26e01d10-4446-11e5-9fd6-3be556907b6a.png)


![image](https://cloud.githubusercontent.com/assets/4018764/9292939/684b2510-4446-11e5-99c4-9a69b01b61e4.png)

可不可以替我解咯？

**Comment by laruence** [comment]
什么意思?

**Comment by Red-wolf-s-husband** [comment]
原来的代码调的是yaf_response_send也就是汇编看到的那个结果，可是我pull了你的这个patch，然后
```
make distclean && phpzie --clean 
```
然后重新安装，kill fpm，再重启。
这个bug依然存在，从gdb layout asm的结果来看，完全是代码没有更新导致的呀。
但我objdump yaf.so文件的结果显示在这个函数里并没有有调yaf_response_send的代码，为什么，fpm进程的gdb layout asm始终是老代码。。。。。。

**Comment by laruence** [comment]
没遇到过, 估计是啥低级错误吧

**Comment by SyuTingSong** [comment]
嗯，已经正常了
