### ISSUE TITLE
命令行执行脚本出现PHP Fatal error:  Class 'Yaf_Application' not found

### ISSUE THREAD

**Issue by BlueGood** [laruence/yaf#188]
服务器装了yaf，网页也没有问题，正常执行，但是写定时任务的时候发现从命令行无法直接执行，会报PHP Fatal error:  Class 'Yaf_Application' not found错误，同一个脚本我用浏览器访问就没问题。
查了半天没看到有遇到这个情况的，是我少装了什么东西吗？

**Comment by laruence** [comment]
你用你的命令行执行php -m 看看有没有加载yaf, 如果有, 用php -i | grep yaf 看看是不是开启了use_namespace. 如果没有....那你...自己解决..

**Comment by BlueGood** [comment]
看了下，php -m没有加载yaf，命令行模式单独加载了自己的php.ini。。改过来就好了。。麻烦鸟哥了。
