### ISSUE TITLE
Error in pecl upgrade to get the newest stable yaf (2.3.4)

### ISSUE THREAD

**Issue by chemdream** [laruence/yaf#189]
on OSX 10.9.2, when running: sudo pecl upgrade
I get this error:
config.status: creating config.h
running: make
/bin/sh /private/tmp/pear/temp/pear-build-rootjind1l/yaf-2.3.4/libtool --mode=compile cc  -I. -I/private/tmp/pear/temp/yaf -DPHP_ATOM_INC -I/private/tmp/pear/temp/pear-build-rootjind1l/yaf-2.3.4/include -I/private/tmp/pear/temp/pear-build-rootjind1l/yaf-2.3.4/main -I/private/tmp/pear/temp/yaf -I/usr/include/php -I/usr/include/php/main -I/usr/include/php/TSRM -I/usr/include/php/Zend -I/usr/include/php/ext -I/usr/include/php/ext/date/lib  -DHAVE_CONFIG_H  -g -O2   -c /private/tmp/pear/temp/yaf/yaf.c -o yaf.lo
mkdir .libs
 cc -I. -I/private/tmp/pear/temp/yaf -DPHP_ATOM_INC -I/private/tmp/pear/temp/pear-build-rootjind1l/yaf-2.3.4/include -I/private/tmp/pear/temp/pear-build-rootjind1l/yaf-2.3.4/main -I/private/tmp/pear/temp/yaf -I/usr/include/php -I/usr/include/php/main -I/usr/include/php/TSRM -I/usr/include/php/Zend -I/usr/include/php/ext -I/usr/include/php/ext/date/lib -DHAVE_CONFIG_H -g -O2 -c /private/tmp/pear/temp/yaf/yaf.c  -fno-common -DPIC -o .libs/yaf.o
/bin/sh /private/tmp/pear/temp/pear-build-rootjind1l/yaf-2.3.4/libtool --mode=compile cc  -I. -I/private/tmp/pear/temp/yaf -DPHP_ATOM_INC -I/private/tmp/pear/temp/pear-build-rootjind1l/yaf-2.3.4/include -I/private/tmp/pear/temp/pear-build-rootjind1l/yaf-2.3.4/main -I/private/tmp/pear/temp/yaf -I/usr/include/php -I/usr/include/php/main -I/usr/include/php/TSRM -I/usr/include/php/Zend -I/usr/include/php/ext -I/usr/include/php/ext/date/lib  -DHAVE_CONFIG_H  -g -O2   -c /private/tmp/pear/temp/yaf/yaf_application.c -o yaf_application.lo
 cc -I. -I/private/tmp/pear/temp/yaf -DPHP_ATOM_INC -I/private/tmp/pear/temp/pear-build-rootjind1l/yaf-2.3.4/include -I/private/tmp/pear/temp/pear-build-rootjind1l/yaf-2.3.4/main -I/private/tmp/pear/temp/yaf -I/usr/include/php -I/usr/include/php/main -I/usr/include/php/TSRM -I/usr/include/php/Zend -I/usr/include/php/ext -I/usr/include/php/ext/date/lib -DHAVE_CONFIG_H -g -O2 -c /private/tmp/pear/temp/yaf/yaf_application.c  -fno-common -DPIC -o .libs/yaf_application.o
/bin/sh /private/tmp/pear/temp/pear-build-rootjind1l/yaf-2.3.4/libtool --mode=compile cc  -I. -I/private/tmp/pear/temp/yaf -DPHP_ATOM_INC -I/private/tmp/pear/temp/pear-build-rootjind1l/yaf-2.3.4/include -I/private/tmp/pear/temp/pear-build-rootjind1l/yaf-2.3.4/main -I/private/tmp/pear/temp/yaf -I/usr/include/php -I/usr/include/php/main -I/usr/include/php/TSRM -I/usr/include/php/Zend -I/usr/include/php/ext -I/usr/include/php/ext/date/lib  -DHAVE_CONFIG_H  -g -O2   -c /private/tmp/pear/temp/yaf/yaf_bootstrap.c -o yaf_bootstrap.lo
 cc -I. -I/private/tmp/pear/temp/yaf -DPHP_ATOM_INC -I/private/tmp/pear/temp/pear-build-rootjind1l/yaf-2.3.4/include -I/private/tmp/pear/temp/pear-build-rootjind1l/yaf-2.3.4/main -I/private/tmp/pear/temp/yaf -I/usr/include/php -I/usr/include/php/main -I/usr/include/php/TSRM -I/usr/include/php/Zend -I/usr/include/php/ext -I/usr/include/php/ext/date/lib -DHAVE_CONFIG_H -g -O2 -c /private/tmp/pear/temp/yaf/yaf_bootstrap.c  -fno-common -DPIC -o .libs/yaf_bootstrap.o
/bin/sh /private/tmp/pear/temp/pear-build-rootjind1l/yaf-2.3.4/libtool --mode=compile cc  -I. -I/private/tmp/pear/temp/yaf -DPHP_ATOM_INC -I/private/tmp/pear/temp/pear-build-rootjind1l/yaf-2.3.4/include -I/private/tmp/pear/temp/pear-build-rootjind1l/yaf-2.3.4/main -I/private/tmp/pear/temp/yaf -I/usr/include/php -I/usr/include/php/main -I/usr/include/php/TSRM -I/usr/include/php/Zend -I/usr/include/php/ext -I/usr/include/php/ext/date/lib  -DHAVE_CONFIG_H  -g -O2   -c /private/tmp/pear/temp/yaf/yaf_dispatcher.c -o yaf_dispatcher.lo
 cc -I. -I/private/tmp/pear/temp/yaf -DPHP_ATOM_INC -I/private/tmp/pear/temp/pear-build-rootjind1l/yaf-2.3.4/include -I/private/tmp/pear/temp/pear-build-rootjind1l/yaf-2.3.4/main -I/private/tmp/pear/temp/yaf -I/usr/include/php -I/usr/include/php/main -I/usr/include/php/TSRM -I/usr/include/php/Zend -I/usr/include/php/ext -I/usr/include/php/ext/date/lib -DHAVE_CONFIG_H -g -O2 -c /private/tmp/pear/temp/yaf/yaf_dispatcher.c  -fno-common -DPIC -o .libs/yaf_dispatcher.o
/bin/sh /private/tmp/pear/temp/pear-build-rootjind1l/yaf-2.3.4/libtool --mode=compile cc  -I. -I/private/tmp/pear/temp/yaf -DPHP_ATOM_INC -I/private/tmp/pear/temp/pear-build-rootjind1l/yaf-2.3.4/include -I/private/tmp/pear/temp/pear-build-rootjind1l/yaf-2.3.4/main -I/private/tmp/pear/temp/yaf -I/usr/include/php -I/usr/include/php/main -I/usr/include/php/TSRM -I/usr/include/php/Zend -I/usr/include/php/ext -I/usr/include/php/ext/date/lib  -DHAVE_CONFIG_H  -g -O2   -c /private/tmp/pear/temp/yaf/yaf_exception.c -o yaf_exception.lo
 cc -I. -I/private/tmp/pear/temp/yaf -DPHP_ATOM_INC -I/private/tmp/pear/temp/pear-build-rootjind1l/yaf-2.3.4/include -I/private/tmp/pear/temp/pear-build-rootjind1l/yaf-2.3.4/main -I/private/tmp/pear/temp/yaf -I/usr/include/php -I/usr/include/php/main -I/usr/include/php/TSRM -I/usr/include/php/Zend -I/usr/include/php/ext -I/usr/include/php/ext/date/lib -DHAVE_CONFIG_H -g -O2 -c /private/tmp/pear/temp/yaf/yaf_exception.c  -fno-common -DPIC -o .libs/yaf_exception.o
/bin/sh /private/tmp/pear/temp/pear-build-rootjind1l/yaf-2.3.4/libtool --mode=compile cc  -I. -I/private/tmp/pear/temp/yaf -DPHP_ATOM_INC -I/private/tmp/pear/temp/pear-build-rootjind1l/yaf-2.3.4/include -I/private/tmp/pear/temp/pear-build-rootjind1l/yaf-2.3.4/main -I/private/tmp/pear/temp/yaf -I/usr/include/php -I/usr/include/php/main -I/usr/include/php/TSRM -I/usr/include/php/Zend -I/usr/include/php/ext -I/usr/include/php/ext/date/lib  -DHAVE_CONFIG_H  -g -O2   -c /private/tmp/pear/temp/yaf/yaf_config.c -o yaf_config.lo
 cc -I. -I/private/tmp/pear/temp/yaf -DPHP_ATOM_INC -I/private/tmp/pear/temp/pear-build-rootjind1l/yaf-2.3.4/include -I/private/tmp/pear/temp/pear-build-rootjind1l/yaf-2.3.4/main -I/private/tmp/pear/temp/yaf -I/usr/include/php -I/usr/include/php/main -I/usr/include/php/TSRM -I/usr/include/php/Zend -I/usr/include/php/ext -I/usr/include/php/ext/date/lib -DHAVE_CONFIG_H -g -O2 -c /private/tmp/pear/temp/yaf/yaf_config.c  -fno-common -DPIC -o .libs/yaf_config.o
/bin/sh /private/tmp/pear/temp/pear-build-rootjind1l/yaf-2.3.4/libtool --mode=compile cc  -I. -I/private/tmp/pear/temp/yaf -DPHP_ATOM_INC -I/private/tmp/pear/temp/pear-build-rootjind1l/yaf-2.3.4/include -I/private/tmp/pear/temp/pear-build-rootjind1l/yaf-2.3.4/main -I/private/tmp/pear/temp/yaf -I/usr/include/php -I/usr/include/php/main -I/usr/include/php/TSRM -I/usr/include/php/Zend -I/usr/include/php/ext -I/usr/include/php/ext/date/lib  -DHAVE_CONFIG_H  -g -O2   -c /private/tmp/pear/temp/yaf/configs/yaf_config_ini.c -o configs/yaf_config_ini.lo
/private/tmp/pear/temp/pear-build-rootjind1l/yaf-2.3.4/libtool: line 1280: configs/yaf_config_ini.loT: No such file or directory
mkdir configs/.libs
mkdir: configs: No such file or directory
make: *** [configs/yaf_config_ini.lo] Error 1
ERROR: `make' failed

**Comment by chemdream** [comment]
I am able to install 2.3.4 manually with the .tgz file... I'm not sure what the difference would be?

**Comment by bingx86** [comment]
Have the same problem on CentOS 6.5 for yaf-2.3.4 and yaf-2.3.5. The error msg is the same with chemdream posted above. But I can install yaf manually with the downloaded package, by using command: phpize; configure; make && make install

**Comment by laruence** [comment]
````
modules
397153 1216 -rwxr-xr-x. 1 root root 1242462 Sep  8 12:04 /var/tmp/pear-build-rootQ0RCZX/install-yaf-2.3.5/usr/lib64/php/modules/yaf.so

Build process completed successfully
Installing '/usr/lib64/php/modules/yaf.so'
install ok: channel://pecl.php.net/yaf-2.3.5
configuration option "php_ini" is not set to php.ini location
You should add "extension=yaf.so" to php.ini
[huixinchen@jx-lj-hxc.lianjia.com:/home/huixinchen/opensource/github/yaf/] (master)
$ cat ^C
[huixinchen@jx-lj-hxc.lianjia.com:/home/huixinchen/opensource/github/yaf/] (master)
$ cat /etc/issue
CentOS release 6.5 (Final)
Kernel \r on an \m
````

I am not sure what's going wrong in your side :<

**Comment by bingx86** [comment]
command 

 ```  pecl install yaf ```


error
```
/bin/sh /tmp/pear/temp/pear-build-rootqUnnrb/yaf-2.3.5/libtool --mode=compile cc  -I. -I/tmp/pear/temp/yaf -DPHP_ATOM_INC -I/tmp/pear/temp/pear-build-rootqUnnrb/yaf-2.3.5/include -I/tmp/pear/temp/pear-build-rootqUnnrb/yaf-2.3.5/main -I/tmp/pear/temp/yaf -I/usr/local/include/php -I/usr/local/include/php/main -I/usr/local/include/php/TSRM -I/usr/local/include/php/Zend -I/usr/local/include/php/ext -I/usr/local/include/php/ext/date/lib  -DHAVE_CONFIG_H  -g -O2   -c /tmp/pear/temp/yaf/configs/yaf_config_ini.c -o configs/yaf_config_ini.lo
/tmp/pear/temp/pear-build-rootqUnnrb/yaf-2.3.5/libtool: line 1283: configs/yaf_config_ini.loT: No such file or directory
mkdir configs/.libs
mkdir: cannot create directory `configs/.libs': No such file or directory
make: *** [configs/yaf_config_ini.lo] 错误 1
```

**Comment by chemdream** [comment]
That's weird that it's the same error on 2 completely different operating systems: CENT and OSX.

I assumed with was just an OSX quirk.

**Comment by laruence** [comment]
the more weird thing is, I can not reproduce it neither in OS X nor CentOS :<

**Comment by chemdream** [comment]
There is someone else in my office experiencing the same thing. I'm in 10.9.2, He's in 10.10.x

We are both binded to a windows domain, but have sudo access and an admin account.

**Comment by laruence** [comment]
thanks very much for the ssh access, this should be fixed now, but it only able to work in next release of course :<

**Comment by tomyan** [comment]
Any idea when this fix is going to be released?

Thanks

**Comment by netroby** [comment]
pecl install yaf-2.3.5 still got this issue. @laruence 

```
downloading yaf-2.3.5.tgz ...

Starting to download yaf-2.3.5.tgz (104,743 bytes)
.
.
..
..
..
..
..
..
..
..
..
....done: 104,743 bytes

68 source files, building

running: phpize

Configuring for:
PHP Api Version:         20131106

Zend Module Api No:      20131226
Zend Extension Api No:   220131226

building in /tmp/pear/temp/pear-build-defaultuserhh6mMc/yaf-2.3.5

running: /tmp/pear/temp/yaf/configure --with-php-config=/usr/local/bin/php-config

checking for grep that handles long lines and -e... /bin/grep

checking for egrep... /bin/grep -E

checking for a sed that does not truncate output... /bin/sed

checking for cc... cc

checking whether the C compiler works... yes
checking for C compiler default output file name... a.out

checking for suffix of executables...

checking whether we are cross compiling... no

checking for suffix of object files... o

checking whether we are using the GNU C compiler... yes

checking whether cc accepts -g... yes

checking for cc option to accept ISO C89... none needed

checking how to run the C preprocessor... cc -E

checking for icc... no

checking for suncc... no

checking whether cc understands -c and -o together... yes
checking for system library directory... lib

checking if compiler supports -R... no

checking if compiler supports -Wl,-rpath,... yes

checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu

checking target system type... x86_64-unknown-linux-gnu

checking for PHP prefix... /usr/local
checking for PHP includes... -I/usr/local/include/php -I/usr/local/include/php/main -I/usr/local/include/php/TSRM -I/usr/local/include/php/Zend -I/usr/local/include/php/ext -I/usr/local/include/php/ext/date/lib

checking for PHP extension directory... /usr/local/lib/php/extensions/no-debug-non-zts-20131226
checking for PHP installed headers prefix... /usr/local/include/php

checking if debug is enabled... no

checking if zts is enabled... no
checking for re2c... re2c

checking for re2c version... 0.13.5 (ok)
checking for gawk... no

checking for nawk... nawk

checking if nawk is broken... no

checking whether to enable yaf support... yes, shared

checking PHP version... 5.6.29, ok

checking for ld used by cc... /usr/bin/ld

checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for /usr/bin/ld option to reload object files... -r

checking for BSD-compatible nm... /usr/bin/nm -B
checking whether ln -s works... yes

checking how to recognize dependent libraries... pass_all

checking for ANSI C header files... yes

checking for sys/types.h... yes

checking for sys/stat.h... yes

checking for stdlib.h... yes

checking for string.h... yes

checking for memory.h... yes

checking for strings.h... yes

checking for inttypes.h... yes

checking for stdint.h... yes

checking for unistd.h... yes

checking dlfcn.h usability... yes

checking dlfcn.h presence... yes
checking for dlfcn.h... yes

checking the maximum length of command line arguments... 1572864

checking command to parse /usr/bin/nm -B output from cc object... ok

checking for objdir... .libs
checking for ar... ar

checking for ranlib... ranlib
checking for strip... strip

checking if cc supports -fno-rtti -fno-exceptions... no

checking for cc option to produce PIC... -fPIC

checking if cc PIC flag -fPIC works... yes

checking if cc static flag -static works... yes

checking if cc supports -c -o file.o... yes

checking whether the cc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes

checking whether -lc should be explicitly linked in... no

checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate

checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes

checking whether to build shared libraries... yes
checking whether to build static libraries... no


creating libtool

appending configuration tag "CXX" to libtool

configure: creating ./config.status

config.status: creating config.h

running: make

/bin/bash /tmp/pear/temp/pear-build-defaultuserhh6mMc/yaf-2.3.5/libtool --mode=compile cc  -I. -I/tmp/pear/temp/yaf -DPHP_ATOM_INC -I/tmp/pear/temp/pear-build-defaultuserhh6mMc/yaf-2.3.5/include -I/tmp/pear/temp/pear-build-defaultuserhh6mMc/yaf-2.3.5/main -I/tmp/pear/temp/yaf -I/usr/local/include/php -I/usr/local/include/php/main -I/usr/local/include/php/TSRM -I/usr/local/include/php/Zend -I/usr/local/include/php/ext -I/usr/local/include/php/ext/date/lib  -DHAVE_CONFIG_H  -g -O2   -c /tmp/pear/temp/yaf/yaf.c -o yaf.lo

mkdir .libs

 cc -I. -I/tmp/pear/temp/yaf -DPHP_ATOM_INC -I/tmp/pear/temp/pear-build-defaultuserhh6mMc/yaf-2.3.5/include -I/tmp/pear/temp/pear-build-defaultuserhh6mMc/yaf-2.3.5/main -I/tmp/pear/temp/yaf -I/usr/local/include/php -I/usr/local/include/php/main -I/usr/local/include/php/TSRM -I/usr/local/include/php/Zend -I/usr/local/include/php/ext -I/usr/local/include/php/ext/date/lib -DHAVE_CONFIG_H -g -O2 -c /tmp/pear/temp/yaf/yaf.c  -fPIC -DPIC -o .libs/yaf.o

/bin/bash /tmp/pear/temp/pear-build-defaultuserhh6mMc/yaf-2.3.5/libtool --mode=compile cc  -I. -I/tmp/pear/temp/yaf -DPHP_ATOM_INC -I/tmp/pear/temp/pear-build-defaultuserhh6mMc/yaf-2.3.5/include -I/tmp/pear/temp/pear-build-defaultuserhh6mMc/yaf-2.3.5/main -I/tmp/pear/temp/yaf -I/usr/local/include/php -I/usr/local/include/php/main -I/usr/local/include/php/TSRM -I/usr/local/include/php/Zend -I/usr/local/include/php/ext -I/usr/local/include/php/ext/date/lib  -DHAVE_CONFIG_H  -g -O2   -c /tmp/pear/temp/yaf/yaf_application.c -o yaf_application.lo

 cc -I. -I/tmp/pear/temp/yaf -DPHP_ATOM_INC -I/tmp/pear/temp/pear-build-defaultuserhh6mMc/yaf-2.3.5/include -I/tmp/pear/temp/pear-build-defaultuserhh6mMc/yaf-2.3.5/main -I/tmp/pear/temp/yaf -I/usr/local/include/php -I/usr/local/include/php/main -I/usr/local/include/php/TSRM -I/usr/local/include/php/Zend -I/usr/local/include/php/ext -I/usr/local/include/php/ext/date/lib -DHAVE_CONFIG_H -g -O2 -c /tmp/pear/temp/yaf/yaf_application.c  -fPIC -DPIC -o .libs/yaf_application.o

/bin/bash /tmp/pear/temp/pear-build-defaultuserhh6mMc/yaf-2.3.5/libtool --mode=compile cc  -I. -I/tmp/pear/temp/yaf -DPHP_ATOM_INC -I/tmp/pear/temp/pear-build-defaultuserhh6mMc/yaf-2.3.5/include -I/tmp/pear/temp/pear-build-defaultuserhh6mMc/yaf-2.3.5/main -I/tmp/pear/temp/yaf -I/usr/local/include/php -I/usr/local/include/php/main -I/usr/local/include/php/TSRM -I/usr/local/include/php/Zend -I/usr/local/include/php/ext -I/usr/local/include/php/ext/date/lib  -DHAVE_CONFIG_H  -g -O2   -c /tmp/pear/temp/yaf/yaf_bootstrap.c -o yaf_bootstrap.lo

 cc -I. -I/tmp/pear/temp/yaf -DPHP_ATOM_INC -I/tmp/pear/temp/pear-build-defaultuserhh6mMc/yaf-2.3.5/include -I/tmp/pear/temp/pear-build-defaultuserhh6mMc/yaf-2.3.5/main -I/tmp/pear/temp/yaf -I/usr/local/include/php -I/usr/local/include/php/main -I/usr/local/include/php/TSRM -I/usr/local/include/php/Zend -I/usr/local/include/php/ext -I/usr/local/include/php/ext/date/lib -DHAVE_CONFIG_H -g -O2 -c /tmp/pear/temp/yaf/yaf_bootstrap.c  -fPIC -DPIC -o .libs/yaf_bootstrap.o

/bin/bash /tmp/pear/temp/pear-build-defaultuserhh6mMc/yaf-2.3.5/libtool --mode=compile cc  -I. -I/tmp/pear/temp/yaf -DPHP_ATOM_INC -I/tmp/pear/temp/pear-build-defaultuserhh6mMc/yaf-2.3.5/include -I/tmp/pear/temp/pear-build-defaultuserhh6mMc/yaf-2.3.5/main -I/tmp/pear/temp/yaf -I/usr/local/include/php -I/usr/local/include/php/main -I/usr/local/include/php/TSRM -I/usr/local/include/php/Zend -I/usr/local/include/php/ext -I/usr/local/include/php/ext/date/lib  -DHAVE_CONFIG_H  -g -O2   -c /tmp/pear/temp/yaf/yaf_dispatcher.c -o yaf_dispatcher.lo

 cc -I. -I/tmp/pear/temp/yaf -DPHP_ATOM_INC -I/tmp/pear/temp/pear-build-defaultuserhh6mMc/yaf-2.3.5/include -I/tmp/pear/temp/pear-build-defaultuserhh6mMc/yaf-2.3.5/main -I/tmp/pear/temp/yaf -I/usr/local/include/php -I/usr/local/include/php/main -I/usr/local/include/php/TSRM -I/usr/local/include/php/Zend -I/usr/local/include/php/ext -I/usr/local/include/php/ext/date/lib -DHAVE_CONFIG_H -g -O2 -c /tmp/pear/temp/yaf/yaf_dispatcher.c  -fPIC -DPIC -o .libs/yaf_dispatcher.o

/bin/bash /tmp/pear/temp/pear-build-defaultuserhh6mMc/yaf-2.3.5/libtool --mode=compile cc  -I. -I/tmp/pear/temp/yaf -DPHP_ATOM_INC -I/tmp/pear/temp/pear-build-defaultuserhh6mMc/yaf-2.3.5/include -I/tmp/pear/temp/pear-build-defaultuserhh6mMc/yaf-2.3.5/main -I/tmp/pear/temp/yaf -I/usr/local/include/php -I/usr/local/include/php/main -I/usr/local/include/php/TSRM -I/usr/local/include/php/Zend -I/usr/local/include/php/ext -I/usr/local/include/php/ext/date/lib  -DHAVE_CONFIG_H  -g -O2   -c /tmp/pear/temp/yaf/yaf_exception.c -o yaf_exception.lo

 cc -I. -I/tmp/pear/temp/yaf -DPHP_ATOM_INC -I/tmp/pear/temp/pear-build-defaultuserhh6mMc/yaf-2.3.5/include -I/tmp/pear/temp/pear-build-defaultuserhh6mMc/yaf-2.3.5/main -I/tmp/pear/temp/yaf -I/usr/local/include/php -I/usr/local/include/php/main -I/usr/local/include/php/TSRM -I/usr/local/include/php/Zend -I/usr/local/include/php/ext -I/usr/local/include/php/ext/date/lib -DHAVE_CONFIG_H -g -O2 -c /tmp/pear/temp/yaf/yaf_exception.c  -fPIC -DPIC -o .libs/yaf_exception.o

/bin/bash /tmp/pear/temp/pear-build-defaultuserhh6mMc/yaf-2.3.5/libtool --mode=compile cc  -I. -I/tmp/pear/temp/yaf -DPHP_ATOM_INC -I/tmp/pear/temp/pear-build-defaultuserhh6mMc/yaf-2.3.5/include -I/tmp/pear/temp/pear-build-defaultuserhh6mMc/yaf-2.3.5/main -I/tmp/pear/temp/yaf -I/usr/local/include/php -I/usr/local/include/php/main -I/usr/local/include/php/TSRM -I/usr/local/include/php/Zend -I/usr/local/include/php/ext -I/usr/local/include/php/ext/date/lib  -DHAVE_CONFIG_H  -g -O2   -c /tmp/pear/temp/yaf/yaf_config.c -o yaf_config.lo

 cc -I. -I/tmp/pear/temp/yaf -DPHP_ATOM_INC -I/tmp/pear/temp/pear-build-defaultuserhh6mMc/yaf-2.3.5/include -I/tmp/pear/temp/pear-build-defaultuserhh6mMc/yaf-2.3.5/main -I/tmp/pear/temp/yaf -I/usr/local/include/php -I/usr/local/include/php/main -I/usr/local/include/php/TSRM -I/usr/local/include/php/Zend -I/usr/local/include/php/ext -I/usr/local/include/php/ext/date/lib -DHAVE_CONFIG_H -g -O2 -c /tmp/pear/temp/yaf/yaf_config.c  -fPIC -DPIC -o .libs/yaf_config.o

/bin/bash /tmp/pear/temp/pear-build-defaultuserhh6mMc/yaf-2.3.5/libtool --mode=compile cc  -I. -I/tmp/pear/temp/yaf -DPHP_ATOM_INC -I/tmp/pear/temp/pear-build-defaultuserhh6mMc/yaf-2.3.5/include -I/tmp/pear/temp/pear-build-defaultuserhh6mMc/yaf-2.3.5/main -I/tmp/pear/temp/yaf -I/usr/local/include/php -I/usr/local/include/php/main -I/usr/local/include/php/TSRM -I/usr/local/include/php/Zend -I/usr/local/include/php/ext -I/usr/local/include/php/ext/date/lib  -DHAVE_CONFIG_H  -g -O2   -c /tmp/pear/temp/yaf/configs/yaf_config_ini.c -o configs/yaf_config_ini.lo

/tmp/pear/temp/pear-build-defaultuserhh6mMc/yaf-2.3.5/libtool: line 1283: configs/yaf_config_ini.loT: No such file or directory

mkdir configs/.libs

mkdir: cannot create directory 'configs/.libs': No such file or directory

Makefile:192: recipe for target 'configs/yaf_config_ini.lo' failed
make: *** [configs/yaf_config_ini.lo] Error 1

ERROR: `make' failed

```

**Comment by miaoyushun** [comment]
@tomyan @netroby 
I had the same problem, but when I tried to install this extension manually, everything looks good, like this:

```
pecl download yaf-2.3.5
tar zxvf yaf-2.3.5.tgz
cd yaf-2.3.5
phpize
./configure
make && make install
echo "extension=yaf.so" > /etc/php.d/yaf.ini
```

**Comment by towertop** [comment]
@miaoyushun

Please dont put the last command in the installing steps you shared. That line just cleaned out my php.in 5 minutes ago.
