### ISSUE TITLE
windows下编译php7 nts x64版的时候报错请问如何处理- -

### ISSUE THREAD

**Issue by magicdragoon** [laruence/yaf#194]
f:\php-sdk\phpdev\vc14\x64\pecl\yaf-php7\php_yaf.h(84): error C2032: “__p__environ”: 函数不能是 struct“_zend_yaf_globals” 的成员 (编译源文件 ..\pecl\yaf-php7\yaf_application.c)
f:\php-sdk\phpdev\vc14\x64\pecl\yaf-php7\php_yaf.h(84): error C2032: “__p__environ”: 函数不能是 struct“_zend_yaf_globals” 的成员 (编译源文件 ..\pecl\yaf-php7\yaf_controller.c)
f:\php-sdk\phpdev\vc14\x64\pecl\yaf-php7\php_yaf.h(84): error C2032: “__p__environ”: 函数不能是 struct“_zend_yaf_globals” 的成员 (编译源文件 ..\pecl\yaf-php7\yaf_action.c)
f:\php-sdk\phpdev\vc14\x64\pecl\yaf-php7\php_yaf.h(84): error C2032: “__p__environ”: 函数不能是 struct“_zend_yaf_globals” 的成员 (编译源文件 ..\pecl\yaf-php7\yaf_config.c)
f:\php-sdk\phpdev\vc14\x64\pecl\yaf-php7\php_yaf.h(84): error C2032: “__p__environ”: 函数不能是 struct“_zend_yaf_globals” 的成员 (编译源文件 ..\pecl\yaf-php7\yaf_exception.c)
..\pecl\yaf-php7\yaf_exception.c(42): warning C4267: “=”: 从“size_t”转换到“uint”，可能丢失数据
f:\php-sdk\phpdev\vc14\x64\pecl\yaf-php7\php_yaf.h(84): error C2032: “__p__environ”: 函数不能是 struct“_zend_yaf_globals” 的成员 (编译源文件 ..\pecl\yaf-php7\yaf_dispatcher.c)
f:\php-sdk\phpdev\vc14\x64\pecl\yaf-php7\php_yaf.h(84): error C2032: “__p__environ”: 函数不能是 struct“_zend_yaf_globals” 的成员 (编译源文件 ..\pecl\yaf-php7\yaf_bootstrap.c)
f:\php-sdk\phpdev\vc14\x64\pecl\yaf-php7\php_yaf.h(84): error C2032: “__p__environ”: 函数不能是 struct“_zend_yaf_globals” 的成员 (编译源文件 ..\pecl\yaf-php7\yaf.c)
..\pecl\yaf-php7\yaf_application.c(324): error C2059: 语法错误:“(”
..\pecl\yaf-php7\yaf_application.c(324): error C2275: “zval”: 将此类型用作表达式非法
f:\php-sdk\phpdev\vc14\x64\php-source-directory\zend\zend_types.h(84): note: 参见“zval”的声明
..\pecl\yaf-php7\yaf_application.c(324): error C2275: “zend_string”: 将此类型用作表达式非法
f:\php-sdk\phpdev\vc14\x64\php-source-directory\zend\zend_types.h(87): note: 参见“zend_string”的声明
..\pecl\yaf-php7\yaf_application.c(324): error C2100: 非法的间接寻址
..\pecl\yaf-php7\yaf.c(77): error C2059: 语法错误:“(”
..\pecl\yaf-php7\yaf_application.c(324): error C2224: “.value”的左侧必须具有结构/联合类型
..\pecl\yaf-php7\yaf.c(78): error C2059: 语法错误:“,”
..\pecl\yaf-php7\yaf_application.c(324): error C2065: “__s”: 未声明的标识符
..\pecl\yaf-php7\yaf_dispatcher.c(450): warning C4267: “=”: 从“size_t”转换到“uint”，可能丢失数据
..\pecl\yaf-php7\yaf.c(79): error C2059: 语法错误:“}”
..\pecl\yaf-php7\yaf_application.c(324): error C2065: “__z”: 未声明的标识符
..\pecl\yaf-php7\yaf.c(84): error C2143: 语法错误: 缺少“)”(在“*”的前面)
..\pecl\yaf-php7\yaf_dispatcher.c(452): warning C4267: “=”: 从“size_t”转换到“uint”，可能丢失数据
..\pecl\yaf-php7\yaf.c(84): error C2143: 语法错误: 缺少“{”(在“*”的前面)
..\pecl\yaf-php7\yaf_application.c(324): error C2224: “.u1”的左侧必须具有结构/联合类型
..\pecl\yaf-php7\yaf.c(84): error C2059: 语法错误:“)”
..\pecl\yaf-php7\yaf.c(85): error C2373: “yaf_globals”: 重定义；不同的类型修饰符
..\pecl\yaf-php7\yaf.c(46): note: 参见“yaf_globals”的声明..\pecl\yaf-php7\yaf_application.c(385): error C2059: 语法错 误:“(”

..\pecl\yaf-php7\yaf.c(85): error C2054: 在“yaf_globals”之后应输入“(”
yaf_loader.c
yaf_plugin.c
..\pecl\yaf-php7\yaf.c(99): error C2059: 语法错误:“(”
..\pecl\yaf-php7\yaf.c(114): error C2059: 语法错误:“(”
..\pecl\yaf-php7\yaf_controller.c(476): warning C4267: “函数”: 从“size_t”转换到“int”，可能丢失数据
..\pecl\yaf-php7\yaf_controller.c(492): warning C4267: “函数”: 从“size_t”转换到“int”，可能丢失数据
..\pecl\yaf-php7\yaf.c(294): error C2065: “zm_globals_ctor_yaf”: 未声明的标识符
..\pecl\yaf-php7\yaf_controller.c(512): warning C4267: “函数”: 从“size_t”转换到“int”，可能丢失数据
..\pecl\yaf-php7\yaf.c(294): warning C4312: “类型转换”: 从“int”转换到更大的“void (__cdecl *)(void *)”
..\pecl\yaf-php7\yaf.c(298): error C2099: 初始值设定项不是常量
..\pecl\yaf-php7\yaf.c(298): warning C4047: “初始化”:“unsigned char”与“void *”的间接级别不同
..\pecl\yaf-php7\yaf.c(298): warning C4047: “初始化”:“int”与“char [21]”的间接级别不同
..\pecl\yaf-php7\yaf_application.c(686): error C2059: 语法错误:“(”
yaf_registry.c
yaf_request.c
yaf_response.c
yaf_router.c
yaf_session.c
yaf_view.c
f:\php-sdk\phpdev\vc14\x64\pecl\yaf-php7\php_yaf.h(84): error C2032: “__p__environ”: 函数不能是 struct“_zend_yaf_globals” 的成员 (编译源文件 ..\pecl\yaf-php7\yaf_loader.c)
..\pecl\yaf-php7\yaf_loader.c(119): warning C4267: “初始化”: 从“size_t”转换到“uint”，可能丢失数据
f:\php-sdk\phpdev\vc14\x64\pecl\yaf-php7\php_yaf.h(84): error C2032: “__p__environ”: 函数不能是 struct“_zend_yaf_globals” 的成员 (编译源文件 ..\pecl\yaf-php7\yaf_registry.c)
..\pecl\yaf-php7\yaf_loader.c(155): warning C4244: “=”: 从“__int64”转换到“uint”，可能丢失数据
..\pecl\yaf-php7\yaf_loader.c(161): warning C4244: “=”: 从“__int64”转换到“uint”，可能丢失数据
..\pecl\yaf-php7\yaf_loader.c(332): warning C4267: “函数”: 从“size_t”转换到“int”，可能丢失数据
..\pecl\yaf-php7\yaf_loader.c(505): warning C4267: “函数”: 从“size_t”转换到“int”，可能丢失数据
f:\php-sdk\phpdev\vc14\x64\pecl\yaf-php7\php_yaf.h(84): error C2032: “__p__environ”: 函数不能是 struct“_zend_yaf_globals” 的成员 (编译源文件 ..\pecl\yaf-php7\yaf_plugin.c)
f:\php-sdk\phpdev\vc14\x64\pecl\yaf-php7\php_yaf.h(84): error C2032: “__p__environ”: 函数不能是 struct“_zend_yaf_globals” 的成员 (编译源文件 ..\pecl\yaf-php7\yaf_request.c)
..\pecl\yaf-php7\yaf_request.c(334): warning C4244: “=”: 从“__int64”转换到“uint”，可能丢失数据
..\pecl\yaf-php7\yaf_request.c(340): warning C4267: “=”: 从“size_t”转换到“uint”，可能丢失数据
f:\php-sdk\phpdev\vc14\x64\pecl\yaf-php7\php_yaf.h(84): error C2032: “__p__environ”: 函数不能是 struct“_zend_yaf_globals” 的成员 (编译源文件 ..\pecl\yaf-php7\yaf_response.c)
..\pecl\yaf-php7\yaf_request.c(328): warning C4244: “初始化”: 从“double”转换到“float”，可能丢失数据
f:\php-sdk\phpdev\vc14\x64\pecl\yaf-php7\php_yaf.h(84): error C2032: “__p__environ”: 函数不能是 struct“_zend_yaf_globals” 的成员 (编译源文件 ..\pecl\yaf-php7\yaf_router.c)
f:\php-sdk\phpdev\vc14\x64\pecl\yaf-php7\php_yaf.h(84): error C2032: “__p__environ”: 函数不能是 struct“_zend_yaf_globals” 的成员 (编译源文件 ..\pecl\yaf-php7\yaf_session.c)
..\pecl\yaf-php7\yaf_response.c(336): warning C4267: “函数”: 从“size_t”转换到“int”，可能丢失数据
..\pecl\yaf-php7\yaf_router.c(86): warning C4244: “=”: 从“zend_ulong”转换到“ulong”，可能丢失数据
..\pecl\yaf-php7\yaf_router.c(122): warning C4244: “=”: 从“zend_ulong”转换到“ulong”，可能丢失数据
..\pecl\yaf-php7\yaf_router.c(160): warning C4267: “=”: 从“size_t”转换到“uint”，可能丢失数据
..\pecl\yaf-php7\yaf_session.c(293): warning C4133: “函数”: 从“ulong *”到“zend_ulong *”的类型不兼容
f:\php-sdk\phpdev\vc14\x64\pecl\yaf-php7\php_yaf.h(84): error C2032: “__p__environ”: 函数不能是 struct“_zend_yaf_globals” 的成员 (编译源文件 ..\pecl\yaf-php7\yaf_view.c)
NMAKE : fatal error U1077: “"E:\Program Files\VS2015\VC\BIN\amd64\cl.exe"”: 返回代码“0x2”
Stop.

**Comment by laruence** [comment]
你用的是php7分支么

**Comment by laruence** [comment]
phpize/configure的时候都要使用php7的phpize和php-config

**Comment by magicdragoon** [comment]
用的是php7的分支

**Comment by laruence** [comment]
看样子感觉你是版本没搞对, 是PHP7的源代码?

**Comment by magicdragoon** [comment]
嗯用的是php7的源代码RC2

**Comment by magicdragoon** [comment]
yaconf用同样的代码和设置，修改了下可以正常编译通过

**Comment by laruence** [comment]
@magicdragoon 我提交了一个修改,你看看能不能解决这个问题.

**Comment by magicdragoon** [comment]
厄，现在变成了这个错误了@@
..\pecl\yaf-php7\requests\yaf_request_http.c(70): error C2065: “rewrited”: 未声明的标识符
..\pecl\yaf-php7\requests\yaf_request_http.c(71): warning C4047: “=”:“int”与“zval *”的间接级别不同
..\pecl\yaf-php7\requests\yaf_request_http.c(72): error C2065: “rewrited”: 未声明的标识符
..\pecl\yaf-php7\requests\yaf_request_http.c(75): error C2065: “rewrited”: 未声明的标识符
..\pecl\yaf-php7\requests\yaf_request_http.c(75): warning C4047: “函数”:“zval *”与“int”的间接级别不同
..\pecl\yaf-php7\requests\yaf_request_http.c(75): warning C4024: “_zval_get_long”: 形参和实参 1 的类型不同
..\pecl\yaf-php7\requests\yaf_request_http.c(83): error C2065: “rewrited”: 未声明的标识符
..\pecl\yaf-php7\requests\yaf_request_http.c(83): warning C4047: “函数”:“zval *”与“int”的间接级别不同
..\pecl\yaf-php7\requests\yaf_request_http.c(83): warning C4024: “_zval_ptr_dtor”: 形参和实参 1 的类型不同

**Comment by magicdragoon** [comment]
在
yaf_request_http.c(70):添加了  	zval *rewrited;      后可以往后编译了不过又出现以下错误了

  正在创建库 F:\php-sdk\phpdev\vc14\x64\php-source-directory\x64\Release\php_yaf.lib 和对象 F:\php-sdk\phpdev\vc14\x64\php-source-directory\x64\Release\php_yaf.exp
yaf_session.obj : error LNK2019: 无法解析的外部符号 __imp_php_session_start，该符号在函数 yaf_session_start 中被引用
F:\php-sdk\phpdev\vc14\x64\php-source-directory\x64\Release\php_yaf.dll : fatal error LNK1120: 1 个无法解析的外部命令
NMAKE : fatal error U1077: “"E:\Program Files\VS2015\VC\BIN\amd64\link.exe"”: 返回代码“0x460”
Stop.

**Comment by laruence** [comment]
恩, 你的php启用session支持.

**Comment by magicdragoon** [comment]
OK,添加了--enable-session后可以正常编译通过了，感谢鸟哥

**Comment by shaohao2014** [comment]
magicdragoon,具体编译过程能分享一下吗？我在windows下不会编译PHP7分支，我的开发环境是VS2015，谢了！我的邮箱是：2817505086@qq.com

**Comment by Elijahlz** [comment]
请问你们野马是怎么安装的,windows我的一直报错
![image](https://user-images.githubusercontent.com/13689930/44721619-1cb6f400-aafd-11e8-908d-fa545baac745.png)
