### ISSUE TITLE
regex正则路由的assemble问题

### ISSUE THREAD

**Issue by livebasic** [laruence/yaf#197]
鸟哥你好，刚使用你的YAF，感觉很好，但是卡在了路由这一块。
需求：项目处理初创期，因SEO问题可能需要时不时更换规则，所以想写一个方法根据传递的m/c/a来获取相对应的路由规则后生成URL，类似YII框架上的createUrl()方法

过程：在文档上看到了assemble方法，用这方法成功地写好了rewrite方式的路由URL生成，但是适配了rewrite也同样需要适配regex，看文档时一直不明白verify参数和reverse的作用到底是什么，文档上也没写，折腾了好几天了，一些QQ群也有人遇到过这种问题，想请鸟哥帮忙解答下，谢谢

下面是我测试写的代码
$routes = array(
            'game_gift_item' => new Yaf\Route\Rewrite('/gift/:giftid', 
                array('module' => 'game', 'controller' => 'gift', 'action' => 'item')),
            'name' => new Yaf\Route\Regex('#([a-z]+).html#', 
                array('module' => 'index', 'controller' => 'test', 'action' => 'aaaa'), 
                array(1 => ':package'),
                array(),
                '/:m/:c/:a/:package'
            )
        );
        if (!empty($routes)) {
            foreach ($routes as $routeKey => $routeVal) {
                $Router->addRoute($routeKey, $routeVal);
            }
        }

**Comment by letwang** [comment]
6666
