### ISSUE TITLE
run without url rewrite

### ISSUE THREAD

**Issue by urulab** [laruence/yaf#201]
Hi, I'am trying to use YAF 2.3.5 with OpenBSD (5.7) httpd new daemon.
Is feasible to use YAF without any URL rewite rules?

Excelent job!!!

**Comment by laruence** [comment]
@urulab yes, please have a look at http://php.net/manual/en/yaf-application.execute.php

**Comment by urulab** [comment]
@laruence, Could you give a practical example? The method "execute" is not fully documented!

**Comment by laruence** [comment]
@urulab I misread your question to using yaf in daemon apps :< sorry for that.

and is you want using Yaf without any URL rewrite rules, you may try to use Yaf_Route_Simple, which passing the routing infos in query string like /?c=controller&a=action

thanks

**Comment by urulab** [comment]
@laruence, Excelent!!!

best regards
