### ISSUE TITLE
源代码编译报错assignment from incompatible pointer type [enabled by default]

### ISSUE THREAD

**Issue by ZhiyangLeeCN** [laruence/yaf#202]
/tmp/pear/temp/yaf/yaf.c: In function ‘OnUpdateSeparator’:
/tmp/pear/temp/yaf/yaf.c:59:24: warning: assignment from incompatible pointer type [enabled by default]
  YAF_G(name_separator) = new_value;
                        ^
/tmp/pear/temp/yaf/yaf.c:60:30: error: ‘new_value_length’ undeclared (first use in this function)
  YAF_G(name_separator_len) = new_value_length;
                              ^
/tmp/pear/temp/yaf/yaf.c:60:30: note: each undeclared identifier is reported only once for each function it appears in
/tmp/pear/temp/yaf/yaf.c: In function ‘zm_deactivate_yaf’:
/tmp/pear/temp/yaf/yaf.c:230:3: warning: passing argument 1 of ‘_zval_ptr_dtor’ from incompatible pointer type [enabled by default]
   zval_ptr_dtor(&(YAF_G(modules)));
   ^
In file included from /usr/local/php/include/php/Zend/zend.h:39:0,
                 from /usr/local/php/include/php/main/php.h:35,
                 from /tmp/pear/temp/yaf/yaf.c:22:
/usr/local/php/include/php/Zend/zend_variables.h:112:15: note: expected ‘struct zval _’ but argument is of type ‘struct zval *_’
 ZEND_API void _zval_ptr_dtor(zval *zval_ptr ZEND_FILE_LINE_DC);

**Comment by iVanilla** [comment]
我也遇到了这个错误。

**Comment by laruence** [comment]
版本没用对
