### ISSUE TITLE
calling function ini_set to set yaf.environ in php file does not work

### ISSUE THREAD

**Issue by Lucups** [laruence/yaf#214]
When I want to set different configuration in the dev and prod environments, I found that  the code 

```
ini_set('yaf.environ' , 'dev');
```

 in `*.php` files does not work. So I cloned the yaf source code, and found this line code in `yaf.c`

```
STD_PHP_INI_ENTRY("yaf.environ",        	"product", PHP_INI_SYSTEM, OnUpdateString, environ, zend_yaf_globals, yaf_globals)
```

Why not use `PHP_INI_ALL` ?  Does it matter ?

**Comment by laruence** [comment]
you can use  new Yaf_Application(config,  "dev");

**Comment by Lucups** [comment]
@laruence  Thanks! 
I've seen it in [yaf docs](http://php.net/manual/en/class.yaf-application.php)
