### ISSUE TITLE
PHP7 64 位 + Yaf 3.0.0 出现 php-cgi.exe 崩溃！

### ISSUE THREAD

**Issue by logig** [laruence/yaf#218]
php_yaf.dll 能正常加载，但是一访问 yaf 应用，php-cgi.exe 马上崩溃掉，求排错的方法~ nginx 留下的错误信息无从下手，php 和 yaf 全部都是从 php 网站下载的也一样直接崩溃！

[error] 2900#2948: *39 WSARecv() failed (10054: An existing connection was forcibly closed by the remote host) while reading response header from upstream

**Comment by laruence** [comment]
你最好能得到croedump的backtrace, 或者提供一个可重现的脚本(方法)

**Comment by litec** [comment]
目前还不知道如何得到 croedump ，学习中。

**Comment by litec** [comment]
---------------------------
Microsoft Visual C++ Runtime Library
---------------------------
Debug Error!

Program: E:\php7-dev\obj\Debug\php-7.0.1-dev\ext\php_yaf.dll
Module: E:\php7-dev\obj\Debug\php-7.0.1-dev\ext\php_yaf.dll
File: e:\php7-dev\php7-src\ext\yaf\configs\yaf_config_ini.c
Line: 389

Run-Time Check Failure #2 - S

(Press Retry to debug the application)

---------------------------
中止(A)   重试(R)   忽略(I)   
---------------------------

**Comment by litec** [comment]
[Window Title]
CGI / FastCGI (DEBUG)

[Main Instruction]
CGI / FastCGI (DEBUG) 已停止工作

[Content]
Windows 可以联机检查该问题的解决方案。

[V] 查看问题详细信息  [联机检查解决方案并关闭该程序] [关闭程序] [调试程序]

**Comment by laruence** [comment]
看不出来是个啥, 你有可重现的脚本么? 比如怎么重现

**Comment by liaozt** [comment]
<?php
define('ROOT_DIR', __DIR__.DIRECTORY_SEPARATOR);
define('PUBLIC_DIR', ROOT_DIR . 'public/');
define('APP_DIR', ROOT_DIR . 'app/');
define('CONF_DIR', ROOT_DIR . 'conf/');

var_dump(class_exists('\Yaf\Application'));

$app = new \Yaf\Application(CONF_DIR . 'app.ini');
//$app->bootstrap()->run();

[product]
application.directory = APP_DIR

**Comment by liaozt** [comment]
应该跟脚本无关

**Comment by laruence** [comment]
我这里没问题啊

**Comment by liaozt** [comment]
php_yaf.dll!failwithmessage(void * retaddr, int crttype, int errnum, const char * msg)	C++
 	php_yaf.dll!_RTC_StackFailure(void * retaddr, const char * varname)	C++
 	php_yaf.dll!_RTC_CheckStackVars(void * frame, _RTC_framedesc * v)	C++
>	php_yaf.dll!yaf_config_ini_instance(_zval_struct * this_ptr, _zval_struct * filename, _zval_struct * section_name) 行 389	C
 	php_yaf.dll!yaf_config_instance(_zval_struct * this_ptr, _zval_struct * arg1, _zval_struct * arg2) 行 50	C
 	php_yaf.dll!zim_yaf_application___construct(_zend_execute_data * execute_data, _zval_struct * return_value) 行 326	C
 	php7_debug.dll!ZEND_DO_FCALL_SPEC_HANDLER(_zend_execute_data * execute_data) 行 843	C
 	php7_debug.dll!execute_ex(_zend_execute_data * ex) 行 417	C
 	php7_debug.dll!zend_execute(_zend_op_array * op_array, _zval_struct * return_value) 行 459	C
 	php7_debug.dll!zend_execute_scripts(int type, _zval_struct * retval, int file_count, ...) 行 1429	C
 	php7_debug.dll!php_execute_script(_zend_file_handle * primary_file) 行 2471	C
 	php-cgi.exe!main(int argc, char * * argv) 行 2454	C
 	[外部代码]

**Comment by litec** [comment]
$app = new \Yaf\Application( ['application'=>['directory'=>APP_DIR]] );

**Comment by litec** [comment]
这样就没问题。

**Comment by litec** [comment]
应该是在 Win7 64 位下处理 .ini 文件时出了点问题。

**Comment by litec** [comment]
谢谢，我知道怎么处理了。
