### ISSUE TITLE
Yaf_Load conflict sql_autoload_register

### ISSUE THREAD

**Issue by SamPeng87** [laruence/yaf#22]
use Yaf_Load import one inlcude `sql_autoload_register` file

will have one error: Failed opening script /Users/sampeng/Work/user/ExecFuture.php.

but,this file is include by sql_autoload_register,I take the place of require_once ,this error solve

**Comment by letwang** [comment]
机制如此

**Comment by laruence** [comment]
set yaf.use_spl_autoload=1
