### ISSUE TITLE
zend_call_method_with_0_params 的问题？

### ISSUE THREAD

**Issue by logig** [laruence/yaf#223]
1，
zend_call_method_with_0_params(controllerObject,controller_ce,NULL,ZSTR_VAL(action),&ret);
        2，
zend_call_method(controllerObject,controller_ce,NULL,ZSTR_VAL(action),ZSTR_LEN(action),&ret,0,NULL,NULL);

为什么第二行代码可以正常工作，而第一行竟报找不到方法实现的错误：Fatal error: Couldn't find implementation for method Home\IndexController::index in Unknown on line 0

**Comment by letwang** [comment]
请使用最新版本即可
