### ISSUE TITLE
我也成功安装了phpinfo里有yaf但是报错502 Bad Gateway

### ISSUE THREAD

**Issue by huangby19890920** [laruence/yaf#229]
我的环境是
PHP Version 5.5.25
nginx 
完全按照
http://www.laruence.com/manual/tutorial.firstpage.html
上面的部署第一个demo

**Comment by huangby19890920** [comment]
我找到问题所在了，，我用的是lnmp一件安装包默认安装了zend扩展
我把下面这些全注释掉，才可以正常访问

;[Zend ZendGuard Loader]
;zend_extension=/usr/local/zend/ZendGuardLoader.so
;zend_loader.enable=1
;zend_loader.disable_licensing=0
;zend_loader.obfuscation_level_support=3
;zend_loader.license_path=

;opcache
;[Zend Opcache]
;zend_extension=opcache.so
;opcache.memory_consumption=128
;opcache.interned_strings_buffer=8
;opcache.max_accelerated_files=4000
;opcache.revalidate_freq=60
;opcache.fast_shutdown=1
;opcache.enable_cli=1
;opcache end

**Comment by weimiyu** [comment]
我也遇到了这个问题，但是我看了下您上面需要注销掉得配置已经注销了，请问还有其他地方需要修改吗
