### ISSUE TITLE
反馈yaf3.0.1 simple路由协议可能存在的一个bug

### ISSUE THREAD

**Issue by allen05ren** [laruence/yaf#232]
php：7.0.0或7.0.1
yaf：3.0.0或3.0.1
问题：
匹配？m=index&c=index&a=index或c=index&a=index可正常访问，但是匹配以下url nginx报 a error occured：
？m=index&a=index
？m=index&c=index
？m=index
？c=index
？a=index
在php5.6.7+yaf2.3.5环境下没有以上问题！@laruence 谢谢！

**Comment by allen05ren** [comment]
php5.6.7+yaf2.3.5没有指定模块或控制器或动作的情况下会正确匹配到默认的模块或控制器或动作

**Comment by laruence** [comment]
这个是你的nginx rewrite有问题吧?

**Comment by laruence** [comment]
nginx的debug日志打开, 看看具体报告什么错误?

**Comment by laruence** [comment]
我好像找到原因了, 提交了一个修复.

**Comment by allen05ren** [comment]
非常感谢！我下载测试看看。

**Comment by laruence** [comment]
@allen05ren 诶, 你早点 回复就好了,  我已经发布了一个新版: https://pecl.php.net/package/yaf 你可以试试这个.... :) 期望不要有问题, 否则又要重新发布了. 哈哈哈 (我先关闭了这个issue, 有问题你再reopen)

**Comment by allen05ren** [comment]
@laruence 好的，我都下载测试看看，非常感谢！

**Comment by allen05ren** [comment]
@laruence 非常感谢！pecl上的3.0.2和github上的3.0.3-dev都已经正常！
非常钦佩敬业精神！！
