### ISSUE TITLE
在php-fpm.conf里使用php_admin_flag设置yaf.use_namespace不生效

### ISSUE THREAD

**Issue by leo108** [laruence/yaf#233]
php-fpm.conf中配置`php_admin_flag[yaf.use_namespace] = 1`

确切的说是`ini_get('yaf.use_namespace')`返回的是1，但是yaf相关的类名仍然是下划线而不是命名空间。

修改`yaf.environ`也是一样，`php_admin_value[yaf.environ] = development`，`ini_get('yaf.environ')`得到development，但YAF_ENVIRON还是product

php版本是5.4.45，yaf版本2.3.5

**Comment by leo108** [comment]
另外能否让yaf同时支持下划线和命名空间？

**Comment by laruence** [comment]
这俩个参数都是SYSTEM的, 必须在php.ini中修改

**Comment by laruence** [comment]
同时支持的时候, 自动加载会有问题... 二义性的问题会很麻烦, 之前也考虑过..最后没做
