### ISSUE TITLE
php 5.6手动编译安装yaf 3.0.2报错“unknow type name 'zend_string'”

### ISSUE THREAD

**Issue by shyandsy** [laruence/yaf#237]
环境：
gcc4.8.5
php 5.6
centos 7 x64

手动编译安装yaf 3.0.2,(readme中要求php5.2+)，执行make命令时候
报错“unknow type name 'zend_string'”

![image](https://cloud.githubusercontent.com/assets/5271457/12133619/8c9e3d6a-b3ec-11e5-9bd5-e85f60b55526.png)
![image](https://cloud.githubusercontent.com/assets/5271457/12133623/944723ec-b3ec-11e5-97a6-4bd3f4bcd83b.png)

**Comment by zxcvdavid** [comment]
3.x只支持 php7及以上 如果是5.6去用2.x

**Comment by shyandsy** [comment]
@zxcvdavid 
ok 谢谢 麻烦把302readme中requirement修改一下
