### ISSUE TITLE
yaf框架安装问题

### ISSUE THREAD

**Issue by BBigBoy** [laruence/yaf#254]
抓住元宵的尾巴，祝各位新年好！
    今天我在php7环境下安装了yaf框架，可是在我调用php命令的时候报错，以下是相关信息，还望赐教：
   1、php版本：php7.0.2
   2、yaf框架版本：yaf3.0.2
   3、在phpinfo中显示已加载 yaf模块
   3、在使用php命令时，提示：PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib64/php/modules/yaf.so' - /usr/lib64/php/modules/yaf.so: undefined symbol: zend_hash_str_del in Unknown on line 0。
        实际上在/usr/lib64/php/modules/目录是有yaf.so文件的。

    ------坚持学习进步的phper

**Comment by BBigBoy** [comment]
对不起，是我自己的原因。  我的centos上自带的php没有卸载干净。

**Comment by ruanyihang** [comment]
这个问题就是原先的php没有卸载干净造成的？
