### ISSUE TITLE
Yaf 的文档有细节错误

### ISSUE THREAD

**Issue by TankAbraham** [laruence/yaf#256]
Yaf 的函数文档中，对于 app 函数的声明是：    

`public static void Yaf_Application::app ( void )`  
对于此函数的描述是    

> 返回值为一个Yaf_Application的实例， 如果在调用之前没有初始化一个Yaf_Application实例的话，它将返回NULL     

我觉得对于函数的声明应该改一下吧？

**Comment by TankAbraham** [comment]
看了文档中对于其他函数的声明。     
Yaf函数声明中 void 类似于 C 语言中的 void* ？ 代表多类型？

**Comment by laruence** [comment]
fixed in doc on php.net
