### ISSUE TITLE
请教一下Yaf_Route_Regex的使用

### ISSUE THREAD

**Issue by liyanlong** [laruence/yaf#263]
这是Yaf 2.3.5 版本的一个问题

```
$route  = new Yaf_Route_Regex(
            "#^/product/([^/]+)/([^/])+#",
            array(
                'controller' => "product",  //route to product controller,
                ),
            array(
                   1  => "param1",
                   2  => "param2"
             ),
            array(),
            '/:m/:c/:a'
        );
```
- 第一个参数指的是匹配的条件
- 第二个参数指的是访问m/c/a的位置
- 第三个参数指的是捕获的字符串授予的参数名
- 第四个参数指的是什么意思呢? 好像我并没有从相关资料获取到足够的信息. 只知道对应存储的属性叫做_verfiy
- 第五个参数在调用assemble的时候有效,会生成一条url

所以想请各位解释一下第四个参数该怎么使用 ?

**Comment by regedit** [comment]
@liyanlong  请问你这个问题解决了吗？ 我使用regex这个路由时，通过* assemble生成时会出错，如果设置了reverse这个参数，assemble没办法生成正确的uri！
