### ISSUE TITLE
php 7.0.5环境中，编译yaf主干出错

### ISSUE THREAD

**Issue by e2ghost** [laruence/yaf#272]
phpize完了之后，configure正常，接下来make有报错

[root@ABCDEFGHIJK yaf]$ make
/bin/sh /root/soft/yaf/libtool --mode=compile cc  -I. -I/root/soft/yaf -DPHP_ATOM_INC -I/root/soft/yaf/include -I/root/soft/yaf/main -I/root/soft/yaf -I/usr/local/php-7.0.5/include/php -I/usr/local/php-7.0.5/include/php/main -I/usr/local/php-7.0.5/include/php/TSRM -I/usr/local/php-7.0.5/include/php/Zend -I/usr/local/php-7.0.5/include/php/ext -I/usr/local/php-7.0.5/include/php/ext/date/lib  -DHAVE_CONFIG_H  -g -O2   -c /root/soft/yaf/yaf.c -o yaf.lo 
mkdir .libs
 cc -I. -I/root/soft/yaf -DPHP_ATOM_INC -I/root/soft/yaf/include -I/root/soft/yaf/main -I/root/soft/yaf -I/usr/local/php-7.0.5/include/php -I/usr/local/php-7.0.5/include/php/main -I/usr/local/php-7.0.5/include/php/TSRM -I/usr/local/php-7.0.5/include/php/Zend -I/usr/local/php-7.0.5/include/php/ext -I/usr/local/php-7.0.5/include/php/ext/date/lib -DHAVE_CONFIG_H -g -O2 -c /root/soft/yaf/yaf.c  -fPIC -DPIC -o .libs/yaf.o
/root/soft/yaf/yaf.c: 在函数‘OnUpdateSeparator’中:
/root/soft/yaf/yaf.c:59:24: 警告：从不兼容的指针类型赋值 [默认启用]
  YAF_G(name_separator) = new_value; 
                        ^
/root/soft/yaf/yaf.c:60:30: 错误：‘new_value_length’未声明(在此函数内第一次使用)
  YAF_G(name_separator_len) = new_value_length;
                              ^
/root/soft/yaf/yaf.c:60:30: 附注：每个未声明的标识符在其出现的函数内只报告一次
/root/soft/yaf/yaf.c: 在函数‘zm_deactivate_yaf’中:
/root/soft/yaf/yaf.c:230:3: 警告：传递‘_zval_ptr_dtor’的第 1 个参数时在不兼容的指针类型间转换 [默认启用]
   zval_ptr_dtor(&(YAF_G(modules)));
   ^
In file included from /usr/local/php-7.0.5/include/php/Zend/zend.h:39:0,
                 from /usr/local/php-7.0.5/include/php/main/php.h:35,
                 from /root/soft/yaf/yaf.c:22:
/usr/local/php-7.0.5/include/php/Zend/zend_variables.h:112:15: 附注：需要类型‘struct zval *’，但实参的类型为‘struct zval **’
 ZEND_API void _zval_ptr_dtor(zval *zval_ptr ZEND_FILE_LINE_DC);
               ^
make: *** [yaf.lo] 错误 1

**Comment by laruence** [comment]
php7.0.5用php7分支, 不要用master

**Comment by e2ghost** [comment]
看到了，抱歉，搜索的时候，默认是open的issue，没切换到close的来看看
