### ISSUE TITLE
action名称大小写的问题

### ISSUE THREAD

**Issue by bobchow** [laruence/yaf#276]
yaf版本2.3.5 php 5.3.28
问题是我的某些action名称中，如果有大写字母的话，会报
`There is no method abababAction in IndexController`
我代码中命名的action名称是 aBaBaBAction 这样的驼峰式命名
奇怪的是，有些这样的action又可以访问，同一台服务器。
所以想问下，是不是有什么配置会影响这个地方

**Comment by vgocoder** [comment]
我也同样遇到这个问题

**Comment by vgocoder** [comment]
你看看你的文件名是不是驼峰，yaf控制器文件名命名必须是   Indexdemo.php    不能是  IndexDemo.php这种形式。只能首字母大写～

**Comment by sandacn** [comment]
controller为什么必须是首字母大写，而不能设定为驼峰的？ 是没有办法区分吗？

**Comment by owenliang** [comment]
@sandacn 因为router路由要根据uri找到对应的类，而通常文件系统是区分大小写的，所以必须指定一个规则，yaf选择了首字母大写剩余小写。

**Comment by letwang** [comment]
大小写是严格的 因为YAF要根据规则寻找文件 参考这里 已经解决
https://github.com/letwang/HookPHP/blob/master/app/admin/controllers/Hook/Module.php
