### ISSUE TITLE
鸟哥好,想问问yaf是否支持composer

### ISSUE THREAD

**Issue by gclinux** [laruence/yaf#282]
如标题

**Comment by lovelock** [comment]
这个看自己的需求，只需要在Bootstrap中加入

```
public function _initLoader(Dispatcher $dispatcher)
    {
        require __DIR__ . '/../vendor/autoload.php';
    }
```

这个方法即可。

**Comment by JokerBruceChan** [comment]
@laruence  鸟哥，请教一下，如果我在 Bootstrap 中加入了 composer 的自动加载器，这个自动加载器会优先于 yaf 本身的自动加载器生效，那么如果我给 controller 加上命名空间，在自动加载某个 controller 时岂不是 压根没有用到 yaf 的自动加载体系？
