### ISSUE TITLE
php7 分支 编译出错

### ISSUE THREAD

**Issue by xianhuawei** [laruence/yaf#283]
/bin/sh /root/php_extension/yaf-php7/libtool --mode=compile cc  -I. -I/root/php_extension/yaf-php7 -DPHP_ATOM_INC -I/root/php_extension/yaf-php7/include -I/root/php_extension/yaf-php7/main -I/root/php_extension/yaf-php7 -I/opt/php/include/php -I/opt/php/include/php/main -I/opt/php/include/php/TSRM -I/opt/php/include/php/Zend -I/opt/php/include/php/ext -I/opt/php/include/php/ext/date/lib  -DHAVE_CONFIG_H  -g -O2   -c /root/php_extension/yaf-php7/views/yaf_view_simple.c -o views/yaf_view_simple.lo 
 cc -I. -I/root/php_extension/yaf-php7 -DPHP_ATOM_INC -I/root/php_extension/yaf-php7/include -I/root/php_extension/yaf-php7/main -I/root/php_extension/yaf-php7 -I/opt/php/include/php -I/opt/php/include/php/main -I/opt/php/include/php/TSRM -I/opt/php/include/php/Zend -I/opt/php/include/php/ext -I/opt/php/include/php/ext/date/lib -DHAVE_CONFIG_H -g -O2 -c /root/php_extension/yaf-php7/views/yaf_view_simple.c  -fPIC -DPIC -o views/.libs/yaf_view_simple.o
In file included from /opt/php/include/php/Zend/zend_globals.h:28:0,
                 from /opt/php/include/php/Zend/zend_compile.h:687,
                 from /opt/php/include/php/Zend/zend_modules.h:26,
                 from /opt/php/include/php/Zend/zend_API.h:27,
                 from /opt/php/include/php/main/php.h:39,
                 from /root/php_extension/yaf-php7/views/yaf_view_simple.c:21:
/root/php_extension/yaf-php7/views/yaf_view_simple.c: In function ‘yaf_view_simple_extract’:
/opt/php/include/php/Zend/zend_globals_macros.h:46:33: error: ‘zend_executor_globals’ has no member named ‘scope’
 # define EG(v) (executor_globals.v)
                                 ^
/root/php_extension/yaf-php7/views/yaf_view_simple.c:110:56: note: in expansion of macro ‘EG’
    if (zend_string_equals_literal(var_name, "this") && EG(scope) && ZSTR_LEN(EG(scope)->name) != 0) {
                                                        ^
In file included from /opt/php/include/php/Zend/zend.h:35:0,
                 from /opt/php/include/php/main/php.h:35,
                 from /root/php_extension/yaf-php7/views/yaf_view_simple.c:21:
/opt/php/include/php/Zend/zend_globals_macros.h:46:33: error: ‘zend_executor_globals’ has no member named ‘scope’
 # define EG(v) (executor_globals.v)
                                 ^
/opt/php/include/php/Zend/zend_string.h:41:26: note: in definition of macro ‘ZSTR_LEN’
 #define ZSTR_LEN(zstr)  (zstr)->len
                          ^
/root/php_extension/yaf-php7/views/yaf_view_simple.c:110:78: note: in expansion of macro ‘EG’
    if (zend_string_equals_literal(var_name, "this") && EG(scope) && ZSTR_LEN(EG(scope)->name) != 0) {
                                                                              ^
In file included from /opt/php/include/php/Zend/zend_globals.h:28:0,
                 from /opt/php/include/php/Zend/zend_compile.h:687,
                 from /opt/php/include/php/Zend/zend_modules.h:26,
                 from /opt/php/include/php/Zend/zend_API.h:27,
                 from /opt/php/include/php/main/php.h:39,
                 from /root/php_extension/yaf-php7/views/yaf_view_simple.c:21:
/opt/php/include/php/Zend/zend_globals_macros.h:46:33: error: ‘zend_executor_globals’ has no member named ‘scope’
 # define EG(v) (executor_globals.v)
                                 ^
/root/php_extension/yaf-php7/views/yaf_view_simple.c:129:56: note: in expansion of macro ‘EG’
    if (zend_string_equals_literal(var_name, "this") && EG(scope) && ZSTR_LEN(EG(scope)->name) != 0) {
                                                        ^
In file included from /opt/php/include/php/Zend/zend.h:35:0,
                 from /opt/php/include/php/main/php.h:35,
                 from /root/php_extension/yaf-php7/views/yaf_view_simple.c:21:
/opt/php/include/php/Zend/zend_globals_macros.h:46:33: error: ‘zend_executor_globals’ has no member named ‘scope’
 # define EG(v) (executor_globals.v)
                                 ^
/opt/php/include/php/Zend/zend_string.h:41:26: note: in definition of macro ‘ZSTR_LEN’
 #define ZSTR_LEN(zstr)  (zstr)->len
                          ^
/root/php_extension/yaf-php7/views/yaf_view_simple.c:129:78: note: in expansion of macro ‘EG’
    if (zend_string_equals_literal(var_name, "this") && EG(scope) && ZSTR_LEN(EG(scope)->name) != 0) {
                                                                              ^
In file included from /opt/php/include/php/Zend/zend_globals.h:28:0,
                 from /opt/php/include/php/Zend/zend_compile.h:687,
                 from /opt/php/include/php/Zend/zend_modules.h:26,
                 from /opt/php/include/php/Zend/zend_API.h:27,
                 from /opt/php/include/php/main/php.h:39,
                 from /root/php_extension/yaf-php7/views/yaf_view_simple.c:21:
/root/php_extension/yaf-php7/views/yaf_view_simple.c: In function ‘yaf_view_simple_display’:
/opt/php/include/php/Zend/zend_globals_macros.h:46:33: error: ‘zend_executor_globals’ has no member named ‘scope’
 # define EG(v) (executor_globals.v)
                                 ^
/root/php_extension/yaf-php7/views/yaf_view_simple.c:260:14: note: in expansion of macro ‘EG’
  old_scope = EG(scope);
              ^
/opt/php/include/php/Zend/zend_globals_macros.h:46:33: error: ‘zend_executor_globals’ has no member named ‘scope’
 # define EG(v) (executor_globals.v)
                                 ^
/root/php_extension/yaf-php7/views/yaf_view_simple.c:261:2: note: in expansion of macro ‘EG’
  EG(scope) = yaf_view_simple_ce;
  ^
/opt/php/include/php/Zend/zend_globals_macros.h:46:33: error: ‘zend_executor_globals’ has no member named ‘scope’
 # define EG(v) (executor_globals.v)
                                 ^
/root/php_extension/yaf-php7/views/yaf_view_simple.c:268:4: note: in expansion of macro ‘EG’
    EG(scope) = old_scope;
    ^
/opt/php/include/php/Zend/zend_globals_macros.h:46:33: error: ‘zend_executor_globals’ has no member named ‘scope’
 # define EG(v) (executor_globals.v)
                                 ^
/root/php_extension/yaf-php7/views/yaf_view_simple.c:281:5: note: in expansion of macro ‘EG’
     EG(scope) = old_scope;
     ^
/opt/php/include/php/Zend/zend_globals_macros.h:46:33: error: ‘zend_executor_globals’ has no member named ‘scope’
 # define EG(v) (executor_globals.v)
                                 ^
/root/php_extension/yaf-php7/views/yaf_view_simple.c:291:4: note: in expansion of macro ‘EG’
    EG(scope) = old_scope;
    ^
/opt/php/include/php/Zend/zend_globals_macros.h:46:33: error: ‘zend_executor_globals’ has no member named ‘scope’
 # define EG(v) (executor_globals.v)
                                 ^
/root/php_extension/yaf-php7/views/yaf_view_simple.c:297:2: note: in expansion of macro ‘EG’
  EG(scope) = old_scope;
  ^
make: *** [views/yaf_view_simple.lo] Error 1

**Comment by zxcvdavid** [comment]
hi，你是用php7来进行编译吗的？

**Comment by xianhuawei** [comment]
是的 github.com/php/php-src 上clone的

**Comment by zxcvdavid** [comment]
我这边编译没有遇到你的问题，检查phpize php-config的目录是否指定正确 && git checkout php7

**Comment by xianhuawei** [comment]
是github.com/src/php-src的版本的extension的版本变成2016***了
官方下载的php-7.0.6没问题
扩展的接口又改了应该
