### ISSUE TITLE
yaf regex router

### ISSUE THREAD

**Issue by fgy58963** [laruence/yaf#291]
Hi, 我们在使用Yaf框架的正则路由的时候，遇到一个问题。
我们想将路径中的字符串提取出来直接作为controller和action的name使用，但是查阅了文档和搜索了之后，只有将其作为变量的方法。如果使用变量来处理就需要在controller中再次进行一次路由的处理，请问yaf是否能在Controller和action中直接调用正则规则取出的数据……
new \Yaf\Route\Regex(
                '正则路由',
                array(
                    'module' => 'post',
                    'controller' => 变量1,
                    'action' => 变量2
                    )

**Comment by laruence** [comment]
当然可以啊,  你可以在正则中使用"命名捕获组", 类似: https://github.com/laruence/yaf/blob/php7/tests/064.phpt#L14

**Comment by fgy58963** [comment]
原来能这么用~谢谢~
