### ISSUE TITLE
php7 mac build problem

### ISSUE THREAD

**Issue by tangxunye** [laruence/yaf#292]
/Users/xxx/Documents/Code/yaf_php7/yaf.c:59:24: warning: incompatible pointer types assigning to 'char *' from 'zend_string *'
      (aka 'struct _zend_string *') [-Wincompatible-pointer-types]
        YAF_G(name_separator) = new_value;
                              ^ ~~~~~~~~~
/Users/xxx/Documents/Code/yaf_php7/yaf.c:60:30: error: use of undeclared identifier 'new_value_length'
        YAF_G(name_separator_len) = new_value_length;
                                    ^
/Users/xxx/Documents/Code/yaf_php7/yaf.c:230:3: warning: incompatible pointer types passing 'zval **' (aka 'struct _zval_struct **') to parameter
      of type 'zval *' (aka 'struct _zval_struct *'); dereference with * [-Wincompatible-pointer-types]
                zval_ptr_dtor(&(YAF_G(modules)));
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/Cellar/php70/7.0.5/include/php/Zend/zend_variables.h:122:48: note: expanded from macro 'zval_ptr_dtor'
#define zval_ptr_dtor(zval_ptr) _zval_ptr_dtor((zval_ptr) ZEND_FILE_LINE_CC)
                                               ^~~~~~~~~~
/usr/local/Cellar/php70/7.0.5/include/php/Zend/zend_variables.h:112:36: note: passing argument to parameter 'zval_ptr' here
ZEND_API void _zval_ptr_dtor(zval *zval_ptr ZEND_FILE_LINE_DC);

**Comment by laruence** [comment]
你没用对yaf的代码, 你编译的yaf的代码应该是PHP5的

**Comment by tangxunye** [comment]
我切的是php7的分支啊

**Comment by laruence** [comment]
然而你就是没弄对... yaf.c:60行在php7下根本没有new_value_length

**Comment by tangxunye** [comment]
ok，谢谢鸟哥，我再去看下
