### ISSUE TITLE
yaf+php5.x的项目在升级到php7.0.7之后，无法运行。

### ISSUE THREAD

**Issue by xuebingwang** [laruence/yaf#293]
Hi，鸟哥，感谢你的这个yaf框架，让我在php生涯中学习到了很多。

我有一个项目，之前一直是运行在php5.5版本下的。
最近升级到了php7.0.7。升级完成后，安装好yaf扩展，访问项目时页面提示：
Warning: Yaf\Loader::autoload(): Failed opening script /mnt/hgfs/code/health-club/src/web/application/library/Core\Mall.php: No such file or directory in /mnt/hgfs/code/health-club/src/web/application/controllers/Index.php on line 9

Fatal error: Class 'Core_Mall' not found in /mnt/hgfs/code/health-club/src/web/application/controllers/Index.php on line 9

我的程序目录结构这样的：

application
-controllers
--Index.php
-library
--Core
--Mall.php

顺便贴上Index控制器的部分代码：
<?php
use Core\Mall;
/**
 * @name IndexController
 * @author xuebingwang
 * @desc 默认控制器
 * @see http://www.php.net/manual/en/class.yaf-controller-abstract.php
 */
class IndexController extends Mall {

类似于这个地址的目录：https://github.com/xuebingwang/xbw-swoole-yaf/tree/master/application/library/Core

我本地的开发环境是win10+ubuntu虚拟机，共享windows的一个目录。

希望您有空帮我解答一下，
感谢！

**Comment by laruence** [comment]
核心的点感觉是"b/application/library/Core\Mall.php" Core后面的这个反斜线, 理论上来说不应该是反的, 除非是Windows环境下编译的PHP...

**Comment by xuebingwang** [comment]
感谢你这么快回复！

此问题已经解决。你可以关闭这个issue了。
不是这个目录的原因，我后来把程序目录移到ubuntu的其他目录下，也是一样的报错。

最后我刚才重新编译安装了一次3.0.3的yaf扩展，就好了。昨天我编译的是master的。。。

**Comment by kyesil** [comment]
i have a same issue on windows server 2016 and server 2012. 
no problem in ubuntu.
php5x and windows : no problem
php7x and windows: apache service restart, after 3 http request 

for all version for yaf
@xuebingwang can you send me your compiled yaf 3.0.5 for php 7.2
