### ISSUE TITLE
多模块下路由问题

### ISSUE THREAD

**Issue by yinliguo** [laruence/yaf#294]
项目目录结构为
```
project
- application
  - modules
    - Admin
      - controllers
        - Index.php
      - views
        - index
          - index.twig
```

application.ini
```
application.modules=Index,Admin
```

访问http://xxx.com/admin/index/index时，模块、controller、action都是对的，但是模板从application下面的index模块中取出的，需要设置什么东西吗

**Comment by laruence** [comment]
不应该啊 , 你用的是什么版本的, 自定义的路由引擎么?

**Comment by yinliguo** [comment]
用的php-7.0.8，yaf-3.0.3

**Comment by yinliguo** [comment]
没有自定义路由，就是用默认的，也没有改写

**Comment by laruence** [comment]
我的意思是你有没有用自定义视图引擎

**Comment by yinliguo** [comment]
我用了一个网上提供的一个类https://github.com/yinliguo/phpBase/blob/master/application/library/TwigAdapter.php，是这个影响了吗

**Comment by yinliguo** [comment]
// 初始化模板引擎
    public function _initView(Yaf_Dispatcher $dispatcher) {
        $view = new TwigAdapter(APPLICATION_PATH . '/views', Yaf_Registry::get('config')->get('twig')->toArray());
        $dispatcher->setView($view);
    }

这是BootStrap文件中的

**Comment by yinliguo** [comment]
路径那是不是应该设置成变量啊

**Comment by laruence** [comment]
恩, 那肯定就是个适配器中的render方法没有处理好路径的选择.
