### ISSUE TITLE
多模块下，如何解决继承问题

### ISSUE THREAD

**Issue by youginil** [laruence/yaf#295]
开发多模块程序，modules下面的controller总是会在/application/controllers下面找类进行继承，而不是在本身的模块下的controllers中找

**Comment by lovelock** [comment]
需要在配置文件中声明application.modules 中声明你新加的模块，最终的这条配置参考：

```
application.modules = index, foo, bar
```

**Comment by letwang** [comment]
https://github.com/letwang/HookPHP/blob/master/app/admin/controllers/Hook/Module.php
