### ISSUE TITLE
getRequest()获取的请求对象中有判断Delete和Patch请求类型的方法吗？

### ISSUE THREAD

**Issue by surenkid** [laruence/yaf#296]
判断GET,POST,PUT请求类型分别可以用isGet(),isPost(),isPut()，那么判断PATCH和DELETE有判断方法吗？

是否只有用getMethod()=='PATCH'和getMethod()=='DELETE'来判断？

**Comment by netroby** [comment]
可以考虑加一个。 @laruence 鸟哥，可以加几个新方法判断是否是PATCH, DELETE么？如果可以加，我考虑发个PR来实现

May we add methods to judgment if a PATCH, or DELETE action. If @laruence agree, I would like to submit a PR to implement these method. 

Please let me know, feel free to comment.

**Comment by netroby** [comment]
@surenkid  The implement has already be merged, so i guess this issue can be closed. 
https://github.com/laruence/yaf/pull/331

**Comment by surenkid** [comment]
@netroby Thank you.
