### ISSUE TITLE
在swoole下，yaf常驻内存时，多模块无效

### ISSUE THREAD

**Issue by pantian** [laruence/yaf#298]
yaf常驻内存时，多模块无效，刚启动服务，第一次访问/Message/Index/index 第二次访问/Member/index/index,结果实际还是输出/Message/Idnex/index的内容 ，而不是/Member/Index/index的内容

**Comment by wenjun1055** [comment]
这既不是swoole的问题，也不是yaf的问题，所以你需要的是[swoole-yaf](https://github.com/wenjun1055/swoole-yaf)
