### ISSUE TITLE
cli模式下，如何向action传递参数

### ISSUE THREAD

**Issue by chitulab** [laruence/yaf#301]
get，post，file的参数

**Comment by yeszao** [comment]
同问。
比如 
`
Yaf_Request_Simple('CLI', 'Front', 'Index', 'index', ['id' => 1]);
$this->application->getDispatcher()->returnResponse(true)->dispatch($request);
`
之后，控制器黎明通过$_GET或者$_POST都不能获取到id的值。

**Comment by owenliang** [comment]
@yeszao 你应该通过action的函数参数接收Yaf_Request_Simple的参数，记得参数名和传递的key要完全一样。

**Comment by yeszao** [comment]
@owenliang 嗯，原来params是这个用途，多谢！
不过我现在用在单元测试上，要是这样的改的话，要改应用代码，也不能为了测试改逻辑。
我换了一种方式，在`dispatch()`之前设置`$_GET['id'] = 1;`
这样是可以的
