### ISSUE TITLE
Yaf_View_Simple::render 在php7中action变量值被模板文件同名变量值覆盖

### ISSUE THREAD

**Issue by xjsunny** [laruence/yaf#303]
举例说明：
Controller代码：
<?php
class IndexController extends Yaf_Controller_Abstract
{
        public function indexAction()
        {
                $sunxj = '这里是controller';
                $view = new Yaf_View_Simple('/pathtoview/view');
                $html = $view->render('index.php', array());

                echo $sunxj;
        }
}

模板文件文件index.php代码：
<?php

$sunxj = "在模板改变参数值";
echo "这里是模板文件";

 上述代码：在 $html = $view->render('index.php', array()); 这一行执行之后，$sunxj值为“在模板改变参数值”，但是在php5中它的值仍然是“这里是controller”。

追查发现，是yaf_view_simple.c里增加了这么一段代码：
+	call = zend_vm_stack_push_call_frame(ZEND_CALL_NESTED_CODE
 +#if PHP_VERSION_ID >= 70100
 +		    | ZEND_CALL_HAS_SYMBOL_TABLE
 +#endif
 +	
把这一段还原后重新编译重启后就和php5一样了。

看了一下 zend_vm_stack_push_call_frame  源码，不知道是不是php7变量堆zvalue计数有点问题？

**Comment by laruence** [comment]
你的是PHP7.0还是PHP7.1啊?

**Comment by laruence** [comment]
我不能重现这个问题,  7.0和7.1都不能重现...

**Comment by laruence** [comment]
```php
--TEST--
ISSUE #303 (local variable is overrided by view renderring)
--SKIPIF--
<?php if (!extension_loaded("yaf")) print "skip"; ?>
--INI--
yaf.use_spl_autoload=0
yaf.lowcase_path=0
yaf.use_namespace=0
--FILE--
<?php
require "build.inc";
startup();

$config = array(
    "application" => array(
        "directory" => APPLICATION_PATH,
    ),
);

file_put_contents(APPLICATION_PATH . "/controllers/Index.php", <<<PHP
<?php
   class IndexController extends Yaf_Controller_Abstract {
         public function indexAction() {
            \$local = true;
            \$this->getView()->display("index.phtml", array());;
            var_dump(\$local);
            return false;
         }
   }
PHP
);

file_put_contents(APPLICATION_PATH . "/views/index.phtml", "<?php \$local = false; ?>");

$app = new Yaf_Application($config);
$app->run();

?>
--CLEAN--
<?php
/* unlink foo2.phtml permission denied */
require "build.inc";
shutdown();
?>
--EXPECTF--

```
这是我写的测试脚本, 你可以保存为.phpt,  在本地测试下, 看看输出什么, 我这里是输出true. 所以是没有问题.

**Comment by xjsunny** [comment]
用你给的代码执行了一下，报错了，输出错误如下：
=====================================================================
PHP         : /home/***/php-7.0.9/bin/php 
PHP_SAPI    : cli
PHP_VERSION : 7.0.9
ZEND_VERSION: 3.0.0
PHP_OS      : Linux - Linux ****** 2.6.32-220.7.1.el6.x86_64 #1 SMP Wed Mar 7 00:52:02 GMT 2012 x86_64
INI actual  : /home/***/php-7.0.9/etc/php.ini
More .INIs  :   
CWD         : /home/***/php-src
Extra dirs  : 
VALGRIND    : Not used
=====================================================================
Running selected tests.
FAIL ISSUE #303 (local variable is overrided by view renderring) [/home/test] 
=====================================================================
Number of tests :    1                 1
Tests skipped   :    0 (  0.0%) --------
Tests warned    :    0 (  0.0%) (  0.0%)
Tests failed    :    1 (100.0%) (100.0%)
Expected fail   :    0 (  0.0%) (  0.0%)
Tests passed    :    0 (  0.0%) (  0.0%)
---------------------------------------------------------------------
Time taken      :    0 seconds
=====================================================================

=====================================================================
FAILED TEST SUMMARY
---------------------------------------------------------------------
ISSUE #303 (local variable is overrided by view renderring)

**Comment by laruence** [comment]
你 cat 一下生成的diff文件, 另外你是从master拉取的最新代码是吧?

**Comment by laruence** [comment]
或者是out文件,  fail是很正常的, 因为我没有写EXPECT

**Comment by xjsunny** [comment]
哦，我明白了，同事装的yaf，我看了一下时间和版本，8月4号编译的yaf-3.0.3版本，我用最新master版本，不去掉任何改进过的地方再编译，现在没问题了。
嘿嘿，不好意思，是我们没有跟进最近版本，麻烦鸟哥了，非常感谢！

ps：
diff文件是这样子的：
001+ Warning: require(build.inc): failed to open stream: No such file or directory in /home/***/test.php on line 2
003+ Fatal error: require(): Failed opening required 'build.inc' (include_path='.:/home/***/php') in /home/***/test.php on line 2
大意应该是我没有写build.inc

**Comment by laruence** [comment]
好, 那就没事了...

**Comment by xjsunny** [comment]
嗯嗯，非常感谢鸟哥
