### ISSUE TITLE
请教一下  php 5.5 编译错误 

### ISSUE THREAD

**Issue by wang199596** [laruence/yaf#304]
/usr/local/Cellar/php55/5.5.25/include/php/Zend/zend_stream.h:60:3: note: 
      'zend_stream' declared here
} zend_stream;
  ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [yaf.lo] Error 1

求大神

**Comment by laruence** [comment]
目前github仓库中, master分支是给PHP7用的, 如果是PHP5, 要用yaf的php5分支.

**Comment by wang199596** [comment]
好的  谢谢
