### ISSUE TITLE
请问如何能在控制器中设置命名空间？

### ISSUE THREAD

**Issue by ayamzh** [laruence/yaf#305]
yaf. use_namespace=1的情况下，controller怎么使用namespace？

比如：Index.php的内容

use Yaf\Controller_Abstract;
use Yaf\Dispatcher;
class IndexController extends Controller_Abstract
{
    public function indexAction()
    {
        Dispatcher::getInstance()->disableView(0);
        echo 'Great,It Works!';
    }
}
没法加namespace了

**Comment by ipersi** [comment]
你可以用https://github.com/ipersi/Syx  是基于yaf修改的。可以支持命名空间。只支持php7+

**Comment by motecshine** [comment]
跟yaf 没多大关系了 你需要阅读 psr

**Comment by qloog** [comment]
@ayamzh  controller里不需要加namespace，也没法加。在多个模块下会有相同的控制器命名的问题，虽然不影响使用，但是IDE提示会不友好。

**Comment by HYqwf** [comment]
多模块时，如何在非默认模块（同一模块）下的控制器里实现同级继承。比如：新建模块Admin/controllers。这个controllers下面有文件Base.php、User.php，如何使User.php能继承Base.php

**Comment by letwang** [comment]
可以这样达到
https://github.com/letwang/HookPHP/blob/master/app/admin/controllers/Hook/Module.php
