### ISSUE TITLE
Yaf 正则路由 能解析包含 ? 特殊字符的URL吗？

### ISSUE THREAD

**Issue by denghp** [laruence/yaf#307]
为什么yaf 不能解析包含? 特殊字符的url ?
URL地址:http://www.xxxx.com/list?p=1

;正则匹配
routes.list.route.module="#/list\?p=(\d+)#"
routes.list.route.module=goods
routes.list.route.controller=index
routes.list.route.action=list
routes.list.map.1='page'

把? 改成 & 就可以 ，难道yaf 正则不支持 ?转义吗？

**Comment by nottellyou** [comment]
如果正则能吸取ThinkPHP的话，那Yaf就相当好用了，我就是发现在路由支持这方面相当的不方便，放弃了。因为我要用到的路由既多又复杂，不是单一规则的路由。
