### ISSUE TITLE
内存泄露

### ISSUE THREAD

**Issue by longxinH** [laruence/yaf#308]
php版本
PHP 7.0.1 (cli) (built: Dec 18 2015 20:37:20) ( ZTS DEBUG )
Copyright (c) 1997-2015 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2015 Zend Technologies

yaf版本
yaf-3.0.4 

运行yaf出现内存泄露
[Fri Sep  2 09:40:38 2016]  Script:  '/data/demo/yaf/public/index.php'
/usr/local/php7/include/php/Zend/zend_string.h(121) :  Freeing 0x7FC4E8463080 (32 bytes), script=/data/demo/yaf/public/index.php
=== Total 1 memory leaks detected ===

通过valgrind检查之后发现
==10385== Memcheck, a memory error detector
==10385== Copyright (C) 2002-2013, and GNU GPL'd, by Julian Seward et al.
==10385== Using Valgrind-3.10.1 and LibVEX; rerun with -h for copyright info
==10385== Command: php70 index.php
==10385== Parent PID: 7565
==10385== 
==10385== 
==10385== HEAP SUMMARY:
==10385==     in use at exit: 6,142 bytes in 39 blocks
==10385==   total heap usage: 31,647 allocs, 31,608 frees, 4,899,576 bytes allocated
==10385== 
==10385== 32 bytes in 1 blocks are definitely lost in loss record 13 of 31
==10385==    at 0x4C2AB80: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==10385==    by 0xAA24BD: _emalloc (zend_alloc.c:2438)
==10385==    by 0xCC26D72: zend_string_alloc (zend_string.h:121)
==10385==    by 0xCC26DDB: zend_string_init (zend_string.h:157)
==10385==    by 0xCC27563: zm_activate_yaf (yaf.c:169)
==10385==    by 0xAEBF09: zend_activate_modules (zend_API.c:2535)
==10385==    by 0xA1DA08: php_request_startup (main.c:1613)
==10385==    by 0xBAF2C1: do_cli (php_cli.c:945)
==10385==    by 0xBB0957: main (php_cli.c:1345)
==10385== 
==10385== LEAK SUMMARY:
==10385==    definitely lost: 32 bytes in 1 blocks
==10385==    indirectly lost: 0 bytes in 0 blocks
==10385==      possibly lost: 0 bytes in 0 blocks
==10385==    still reachable: 6,110 bytes in 38 blocks
==10385==         suppressed: 0 bytes in 0 blocks
==10385== Reachable blocks (those to which a pointer was found) are not shown.
==10385== To see them, rerun with: --leak-check=full --show-leak-kinds=all
==10385== 
==10385== For counts of detected and suppressed errors, rerun with: -v
==10385== ERROR SUMMARY: 1 errors from 1 contexts (suppressed: 0 from 0)

**Comment by godsoul** [comment]
我也有这个报错，怎么解决

**Comment by laruence** [comment]
这个不影响, 也不会有真正的内存泄露, 如果你有洁癖一定想解决, 那么可以换PHP7版本... PHP7的没有这些问题.
