### ISSUE TITLE
希望能够自定义HOOK

### ISSUE THREAD

**Issue by metooweb** [laruence/yaf#313]
希望能够自定义HOOK
增加 模板解析前的 HOOK 与模板解析后的HOOK

**Comment by lpflpf** [comment]
自己加一个Event组件，然后在模板前后trigger一下就好了。

**Comment by letwang** [comment]
基于数据库后台控制的自定义HOOK 用户可以对HOOK分类、上传、删除、排序、移动、安装、卸载。。
https://github.com/letwang/HookPHP/blob/master/app/admin/plugins/Hook.php
https://github.com/letwang/HookPHP/tree/master/app/admin/hooks
https://github.com/letwang/HookPHP/blob/master/vendor/Hook/Hook/Hook.php
https://github.com/letwang/HookPHP/blob/master/vendor/Hook/Hook/Module.php
