### ISSUE TITLE
关于yaf源码解析的文档。。。

### ISSUE THREAD

**Issue by xuanskyer** [laruence/yaf#316]
关于yaf源码解析的文档。。。

最近在阅读框架的扩展代码，觉得有很多地方一知半解，是否有相关的文档呢

**Comment by motecshine** [comment]
你好我最近也在写扩展,我觉得看不如写。yaf的代码已经很容易阅读了,你应该是想要流程 :
[Yaf源码阅读之框架的启动（一）](http://kenby.iteye.com/blog/1979833)

*** 一些资料
[php7的一些文章] (http://jpauli.github.io/)

[有关于php5 的内核书籍](http://www.phpinternalsbook.com)

[『翻译』PHP 7 新 Hash 表实现](https://crispgm.com/page/php7-new-hashtable-implementation.html)


如果想要学做扩展开发的话，建议基于 php5.6.*  ,遇到的问题会少点，如果出现了问题也容易google到

**Comment by xuanskyer** [comment]
@motecshine 感谢回复！

相关的资料也看了不少，就是觉得不够系统，可能有点着急了，还是要一点点看吧~

之前过了一遍 [PHP扩展开发及内核应用](https://github.com/walu/phpbook) 的翻译项目文档，颇有收获。

**Comment by xuanskyer** [comment]
@motecshine 

请教下：

```

#define YPF_STARTUP_FUNCTION(module)   	ZEND_MINIT_FUNCTION(ypf_##module)
#define YPF_STARTUP(module)	 		  	ZEND_MODULE_STARTUP_N(ypf_##module)(INIT_FUNC_ARGS_PASSTHRU)

```
这2个宏，我看了下最后都会解析成 `zm_startup_##module` 。这个在加载各个模块的过程中具体是怎么起作用的呢？
