### ISSUE TITLE
yaf项目构建能否自动完成？

### ISSUE THREAD

**Issue by i6448038** [laruence/yaf#321]
翻阅了yaf的文档，发现yaf项目的目录结构都是要自己创建的，先创建public目录，然后在创建css目录。。。 是否有一个小工具，可以一键build出来？ 例如yaf 命令行：yaf build~

**Comment by jeff-wu** [comment]
有的，https://github.com/laruence/yaf/tree/master/tools/cg

**Comment by i6448038** [comment]
每次运行，输出NONE 是什么鬼

**Comment by JiankangMai** [comment]
http://www.laruence.com/manual/tutorial.last.html

**Comment by letwang** [comment]
可以的
