### ISSUE TITLE
MAC下PHP7用pecl和编译安装都失败

### ISSUE THREAD

**Issue by byronkingz** [laruence/yaf#323]
sudo pecl install yaf
downloading yaf-3.0.4.tgz ...
Starting to download yaf-3.0.4.tgz (96,359 bytes)
.....................done: 96,359 bytes
68 source files, building
running: phpize
Configuring for:
PHP Api Version:         20151012
Zend Module Api No:      20151012
Zend Extension Api No:   320151012
building in /private/tmp/pear/install/pear-build-root1UDZIh/yaf-3.0.4
running: /private/tmp/pear/install/yaf/configure --with-php-config=/usr/local/bin/php-config
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for a sed that does not truncate output... /usr/bin/sed
checking for cc... cc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... configure: error: in `/private/tmp/pear/install/pear-build-root1UDZIh/yaf-3.0.4':
configure: error: cannot run C compiled programs.
If you meant to cross compile, use `--host'.
See `config.log' for more details
ERROR: `/private/tmp/pear/install/yaf/configure --with-php-config=/usr/local/bin/php-config' failed

**Comment by laruence** [comment]
"configure: error: cannot run C compiled programs" 这是你环境的问题, 你要看看你的编译器是不是正确安装了, 路径是否正确

**Comment by byronkingz** [comment]
谢谢，解决了。是升级xcode造成的环境问题。
