### ISSUE TITLE
为什么继承Yaf_Plugin_Abstract这个类的内部不必须实现全部抽象方法？

### ISSUE THREAD

**Issue by eyesChan** [laruence/yaf#324]
Yaf_Plugin_Abstract 这个类是抽象类，那为什么自己创建的插件类集成Yaf_Plugin_Abstract之后不是必须实现全部的7个抽象方法？php对于抽象类的集成不是有这条规则吗？

**Comment by laruence** [comment]
因为Yaf_Plugin_Abstract只是个抽象类, 但没有申明任何的抽象方法(文档中的方法只是原型示例)

**Comment by eyesChan** [comment]
没有抽象方法的类为什么是抽象类？另外，手册中显示这个类中的七个方法不是没有方法体吗？

**Comment by laruence** [comment]
为什么没有抽象方法的类不能是抽象类?  手册中的是”示例“， 是”约定“， 是告诉你都有些什么Hook

**Comment by eyesChan** [comment]
我一直以为抽象类中至少有一个抽象方法  :(  
原来，事实是，如果类内有一个抽象方法，那么这个类一定是抽象类；但是抽象类不一定，有抽象方法。
