### ISSUE TITLE
Using php cli-server,  can not got Yaf_Response_Http object

### ISSUE THREAD

**Issue by netroby** [laruence/yaf#325]
I am using PHP cli-server to run fast dev environment on my local pc. i am try to got Yaf_Response_Http object by run following code inside action

```php
public function indexAction() {
    var_dump($this->getResponse());
}
```
I got Yaf_Response_Cli object. that not what i want. I could not got Header, Body from this object.

```
Uncaught Error: Call to undefined method Yaf_Response_Cli::getHeader() in ....
```

and i try to look inside yaf source code, i found yaf_response.c line 55-83

```c
/** {{{ yaf_response_t * yaf_response_instance(yaf_response_t *this_ptr, char *sapi_name)
 */
yaf_response_t * yaf_response_instance(yaf_response_t *this_ptr, char *sapi_name) {
	zval 			header, body;
	zend_class_entry 	*ce;
	yaf_response_t 		*instance;

	if (strncasecmp(sapi_name, "cli", 3)) {  //What the hell?
		ce = yaf_response_http_ce;
	} else {
		ce = yaf_response_cli_ce;
	}

    instance = this_ptr;
    if (ZVAL_IS_NULL(this_ptr)) {
        object_init_ex(instance, ce);
    }

	array_init(&header);
	zend_update_property(ce, instance, ZEND_STRL(YAF_RESPONSE_PROPERTY_NAME_HEADER), &header);
	zval_ptr_dtor(&header);

	array_init(&body);
	zend_update_property(ce, instance, ZEND_STRL(YAF_RESPONSE_PROPERTY_NAME_BODY), &body);
	zval_ptr_dtor(&body);

	return instance;
}
/* }}} */
```

php built-in http server sapi name was cli-server . not cli. so please do not just compare first 3 if it was cli. you should add more check for cli-server

**Comment by netroby** [comment]
@laruence  need your help.

**Comment by laruence** [comment]
you could make PR to fix that,  change the 3 to 4 should fix this

**Comment by netroby** [comment]
Thanks for guide me . make a small commit. @laruence  would you please take a look?
