### ISSUE TITLE
RFC: support runtime specified bootstrap file loader

### ISSUE THREAD

**Issue by netroby** [laruence/yaf#328]
We want to implement runtime specified bootstrap file loader via code. not want change the configure.

the public/index.php and public/cli.php got similar, but they need to execute different Bootstrap(Doing different works)

we have application/Bootstrap.php and application/BootstrapCli.php

and we have configs/application.conf
```php
<?php
/**
 * 基础配置文件
 */
return [
    'application' => [
        'directory' => APP_PATH . "/application/",
        'modules' => 'Index,User,ModuleA,ModuleB',
        'view' => [
            'ext' => 'php',
        ]
    ]
];
```

in public/index.php we may have these code
```php
require APP_PATH . '/vendor/autoload.php';
$config = require APP_PATH . '/configs/application.php';
$app = new Yaf_Application($config);
$app->bootstrap(APP_PATH . '/application/Bootstrap.php')->run();
```
And in public/cli.php we may have these code

```php

$config = require APP_PATH . '/configs/cli.php';
$app = new Yaf_Application($config);
$dispatcher = $app->bootstrap(APP_PATH . '/application/BootstrapCli.php')->getDispatcher();
//do following stuff
```

Or can we add one more function like setBootstrapFile(string $bootstrapFile) ? then we can run 
```php
$app->setBootstrapFile($bootstrapFile)->bootstrap()->run();
```

**Comment by netroby** [comment]
@laruence  Have any idea? New pr preparing

**Comment by laruence** [comment]
http://php.net/manual/zh/yaf-application.bootstrap.php

bootstrap allows you to pass a bootstrap instance as argument.

and that means, you already could do that by 
````
$app->bootstrap(new BootStrapCli);
````

**Comment by netroby** [comment]
tested. seems not working. i will check it again.

**Comment by netroby** [comment]
It not working at all.
The public/index.php like this
```php

require APP_PATH . '/application/BootstrapCli.php';
$config = require APP_PATH . '/configs/cli.php';
$app = new Yaf_Application($config);
$dispatcher = $app->bootstrap(new BootstrapCli())->getDispatcher();
```

the BootstrapCli.php
```php
class BootstrapCli extends Yaf_Bootstrap_Abstract
{

    public function _initConfig()
    {
        echo "CLI config initialized"; exit();
        $config = Yaf_Application::app()->getConfig();

        Yaf_Registry::set('config', $config);

        //关闭自动加载模板
        Yaf_Dispatcher::getInstance()->disableView();
    }
}
```

**Comment by ipersi** [comment]
The class name must be Bootstrap, and inheritance Yaf_Bootstrap_Abstract
