### ISSUE TITLE
RFC: Convert document project from xml to markdown, render with gitbook.

### ISSUE THREAD

**Issue by netroby** [laruence/yaf#329]
The current document of yaf had a bit outdated. lack of update. 
Can we convert document project from xml to markdown? and we can render books with gitbook.

Gitbook has many features. 

https://github.com/GitbookIO/gitbook

like render book to html, pdf, epub format. 
Has code block hightlight

**Comment by laruence** [comment]
the current manual is based on php docbook,  and it is friendly to generate docs on php.net. 
So, I don't see a good reason to change that.

**Comment by netroby** [comment]
Edit xml files not feel so good. so not much more contribute made with Yaf framework document project. 
If convert Markdown ,publish with gitbook, may users can write markdown to improve the document quality.
I have no idea , don't see a good reason to change that  means.

**Comment by netroby** [comment]
Dear @laruence , i am working on convert yaf doc project into markdown+gitbook format. to provided generate pdf,epub format book. will base on your original yaf-doc repository.

**Comment by netroby** [comment]
For preview, you can visist https://netroby.github.io/php-yaf-doc/
