### ISSUE TITLE
看源代码发现的一个小问题

### ISSUE THREAD

**Issue by lpflpf** [laruence/yaf#334]
yaf_config.c : 49

判断是否为ini 文件，判断的貌似有些问题。

应该对比的是`.ini`，少了个`.`

**Comment by klvoek** [comment]
判断没有问题，yaf_onfig.c:49为比对文件名后3个字符是不是"ini"。
`if (strncasecmp(Z_STRVAL_P(arg1) + Z_STRLEN_P(arg1) - 3, "ini", 3) == 0) {
...
}`

**Comment by lpflpf** [comment]
哈哈，仔细看我说的评论。

**Comment by klvoek** [comment]
比不比对`.`是多余的

**Comment by laruence** [comment]
这个不影响, 因为他不是由输入指定的, 而是由配置决定的, 也就是说, 可以通过良好配置决定, 所以还好. 当然, 要说严谨确实应该.ini. 但, 无所谓啦 :)
