### ISSUE TITLE
PHP Fatal error with yaf 3.0.4

### ISSUE THREAD

**Issue by sgub** [laruence/yaf#338]
On CentOS 7 running php 7.0.14 / yaf 3.0.4, php error log shows:

`[16-Feb-2017 16:27:07 Asia/Shanghai] PHP Fatal error:  Uncaught Error: Class 'XXXX_Conf' not found in /XXXX/code/application/Bootstrap.php:42
Stack trace:
#0 [internal function]: Bootstrap->_initConfig(Object(Yaf_Dispatcher))
#1 /XXXX/code/public/index.php(8): Yaf_Application->bootstrap()
#2 {main}
  thrown in /XXXX/code/application/Bootstrap.php on line 42`

Upgrade to php 7.0.15 does not solve the problem.
Downgrade to yaf 3.0.3 solved the problem.

**Comment by laruence** [comment]
are you able to make a reproduce script? like: https://github.com/laruence/yaf/commit/baa8bc4e93d24ab8a39bf14989220d788e2491df
