### ISSUE TITLE
鸟哥能不能把文档整理一下？

### ISSUE THREAD

**Issue by haython** [laruence/yaf#340]
有些已经过时了，有些都没有文档

**Comment by laruence** [comment]
php.net的上么?

**Comment by netroby** [comment]
I am working on improve yaf document quality, welcome to join with me. working together 

https://netroby.github.io/php-yaf-doc/chinese/

the source code repository located at : 
https://github.com/netroby/php-yaf-doc

**Comment by lium0** [comment]
bro, https://netroby.github.io/php-yaf-doc/chinese/  这个网址 404 了啊 ！
