### ISSUE TITLE
鸟哥，有个主控制器init 方法和error404 问题。

### ISSUE THREAD

**Issue by liuyanqiang** [laruence/yaf#347]
class Controller_Base extends Yaf_Controller_Abstract{
  
    public function init(){
        echo “hello”;
     }
public function errorAction(Exception $exception)
    {
     echo 404;    
    }
    }
class IndexController extends Controller_Base{
	public function init(){
		 parent::init();
	}
     public function indexAction(){
     echo  "world"; 
   }
}
如果访问正常 会输出hello world
如果访问一个不存在的页面。先输出 hello 404;  不应该先判段有没有action 吗？

**Comment by liuyanqiang** [comment]
没有先抛出异常再执行init 方法

**Comment by swumao** [comment]
http://php.net/manual/zh/yaf-controller-abstract.init.php 

init 方法会在控制器对象实例化之后被调用
