### ISSUE TITLE
php7环境下抛出Error无法转到Controller_Error

### ISSUE THREAD

**Issue by XIN-Dongzhe** [laruence/yaf#351]

**Comment by wxxiong6** [comment]
我这也出现500问题

**Comment by qloog** [comment]
抛异常还是抛Error ? 

Controller_Error是来捕获异常的

**Comment by xanpen** [comment]
also have this problem~~
is it a bug or not ?

**Comment by laruence** [comment]
这种错误本身不属于业务运行期错误，所以也不应该转到error controller
