### ISSUE TITLE
在Plugin中$response->getBody()竟然是空的

### ISSUE THREAD

**Issue by colly007008009** [laruence/yaf#363]
yaf2.3.5+php5.5出现了这个问题，当时开发是yaf2.3.6+php5.6现在准备都切换到开发配置再次测试，好古怪啊。

**Comment by swumao** [comment]
这个要看你是在 plugin 的哪个钩子函数执行的`$response->getBody();`吧

**Comment by letwang** [comment]
的确是个BUG 问题同https://github.com/laruence/yaf/issues/419
需要手动parse_str(file_get_contents('php://input'), $post_vars);即可
