### ISSUE TITLE
鸟哥yaf.cache_config这个不用了啊，文档要跟上啊

### ISSUE THREAD

**Issue by smalleyes** [laruence/yaf#366]
![image](https://user-images.githubusercontent.com/3990846/28867819-f9408d56-77a9-11e7-8c6a-a1dcf293f7db.png)

http://www.laruence.com/manual/yaf.ini.html

**Comment by motecshine** [comment]
https://github.com/laruence/yaf/commit/713e2904e4784fb9ebce9b1c33cf607a58734d38


确实早已移除

**Comment by smalleyes** [comment]
嗯    yaf 3.0了   但是文档还是2.x的

**Comment by laruence** [comment]
在php.net上看yaf最新文档哈

**Comment by smalleyes** [comment]
好的，谢鸟哥回复
