### ISSUE TITLE
The default route does not support CamelCased naming

### ISSUE THREAD

**Issue by netroby** [laruence/yaf#367]
We want to use the default route, and want the CamelCased route

V1/controllers/StorageObject.php

but seems the default route does not support it.

**Comment by owenliang** [comment]
Yaf在框架代码已经强制controller的所有路径层级首字母大写，剩余字母小写了。

无论你使用何种Router（比如正则，重写），甚至自定义Router，都是无法解决这个问题的。

相关代码：

yaf_dispatcher_fix_default函数：
```

		char *q, *p = zend_str_tolower_dup(Z_STRVAL_P(controller), Z_STRLEN_P(controller));
		/**
		 * Upper controller name
		 * eg: Index_sub -> Index_Sub
		 */
		q = p;
		*q = toupper(*q);
		while (*q != '\0') {
			if (*q == '_' || *q == '\\') {
			   	if (*(q+1) != '\0') {
					*(q+1) = toupper(*(q+1));
					q++;
				}
			}
			q++;
		}

		zend_update_property_stringl(yaf_request_ce, request,
				ZEND_STRL(YAF_REQUEST_PROPERTY_NAME_CONTROLLER), p, Z_STRLEN_P(controller));
```

 请求的处理函数yaf_dispatcher_dispatch：
```
		YAF_PLUGIN_HANDLE(plugins, YAF_PLUGIN_HOOK_ROUTESTARTUP, request, response);
		YAF_EXCEPTION_HANDLE(dispatcher, request, response);
		if (!yaf_dispatcher_route(dispatcher, request)) {
			yaf_trigger_error(YAF_ERR_ROUTE_FAILED, "Routing request failed");
			YAF_EXCEPTION_HANDLE_NORET(dispatcher, request, response);
			zval_ptr_dtor(response);
			return NULL;
		}
		yaf_dispatcher_fix_default(dispatcher, request);
		YAF_PLUGIN_HANDLE(plugins, YAF_PLUGIN_HOOK_ROUTESHUTDOWN, request, response);
		YAF_EXCEPTION_HANDLE(dispatcher, request, response);
		(void)yaf_request_set_routed(request, 1);
```

从实现上来说，唯一的机会是在YAF_PLUGIN_HOOK_ROUTESHUTDOWN这个插件回调环节，覆盖request里的module，controller，action，重改为驼峰风格，将可以影响到后续Yaf的磁盘文件查找过程。

你默认使用的路由器是Yaf内置的Yaf_Router，它支持simple，regex，rewrite，map等多种路由规则，通过addConfig可以向Yaf_Router添加，Yaf_Router会将uri匹配其中某个规则而结束路由。

你可以注册通过Yaf接口直接取代Yaf_Router（不建议，因为已有的多种路由规则就没法用了），也可以通过Yaf_Router->addRoute接口添加自定义的路由规则（和simpe，regex等一样的东西），这个需要继承接口Yaf_Route_Interface并实现一个路由方法即可。

Yaf_Router在匹配多个Yaf_Route_Interface的时候是根据route的添加顺序优先匹配的，然而默认规则Yaf_Route_Simple是Yaf框架首先注册的，这就导致你就算自己写Route也没法抢在simple之前生效。

既然没法简单的注入自己的Route，那么在ROUTE SHUTDOWN截断改写controller的大小写就没有了依据，除非你只使用simple route规则，那么你可以直接从request->uri复原出controller，否则极有可能uri走了其他的route规则（比如正则路由），这样你就不能简单的根据uri复原出原始controller的大小写情况了。

结论：按Yaf的规则玩耍。

**Comment by laruence** [comment]
Controller是来自用户的请求的, 用户的请求是通过URL来的, 大小写是怎么样的是不确定的, 所以必须统一规则, 否则查找起来多费劲啊,各种大小写组合试一遍?

**Comment by xrjxs** [comment]
碰到同样问题，其实一点都不费劲。参考 yii，url 是 /user/check-token 的action将会自动替换为 checkTokenAction()，根本不用各种大小写组合试一遍。现在 yaf 只能用 check-tokenAction 然而是非法的，要不然只能是 checktokenAction() 这样的名字让人抓狂...
