### ISSUE TITLE
鸟哥可以解释一下Zend里IS_INDIRECT的含义吗？

### ISSUE THREAD

**Issue by owenliang** [laruence/yaf#368]
如题，感恩。

**Comment by laruence** [comment]
这个主要用在引擎内部, 用作对另外一个zval的"直接引用", 比如
````
$array['a']['b'] = 2;
````
这个我们首先要用写模式获取$array['a'], 这在PHP5的时候没什么难得, 因为Hashtable里面存的是zval的指针的指针, 只需要获取这个指针就行了, 但是在PHP7开始, Hashtable直接存的是$array['a']本身的zval,  那怎么办呢, 我们就用IS_INDIRECT这个类型, 他的值就是$array['a']的地址, 从而解决这个问题.

**Comment by owenliang** [comment]
感恩 非常清晰的解答
