### ISSUE TITLE
php_flag 设置use_namespace不生效

### ISSUE THREAD

**Issue by nicecp** [laruence/yaf#372]
`php: 5.4.44 yaf:2.3.4`
在fpm里添加如下配置：

> php_flag[yaf.use_namespace] = on

在`phpinfo`中看到`yaf.use_namespace`是`On`;
但是报找不到类：

> Fatal error: Class 'Yaf\Application' not found 

入口文件代码：

> $app = new Yaf\Application(APPPATH . '/config/application.ini'); $app->bootstrap()->run();

**Comment by laruence** [comment]
这个只能是在php.ini启动的时候配置.

**Comment by viest** [comment]
yaf.use_namespace 的modifiable修饰符是 PHP_INI_SYSTEM，所以你在FPM中使用php_flag设置是无效的；

个人理解，如有错误请指正；

**Comment by nicecp** [comment]
@viest [PHP_INI_ALL](http://php.net/manual/zh/yaf.configuration.php)

**Comment by motecshine** [comment]
@laruence 

yaf.use_namespace | 0 | its PHP_INI_ALL value
-- | -- | --

文档好像有点落后了。 master分之下 的修饰符 是PHP_INI_SYSTEM

**Comment by laruence** [comment]
马上修改文档

**Comment by nicecp** [comment]
鸟哥，原来这是文档的锅😳
