### ISSUE TITLE
在application/bootstrap.php里 如何获取到当前模块名？

### ISSUE THREAD

**Issue by qloog** [laruence/yaf#375]
试着用 通过Dispatcher类来获取，没有取到，我的获取方式是：
`$dispathcer->getRequest()->getModuleName()`
或
`$dispathcer->getRequest()->module`

取到的都是null, 求各位大神来解下。

**Comment by laruence** [comment]
Bootstrap的时候还没有route请请求呢, 自然是NULL了....

**Comment by qloog** [comment]
感谢 @laruence 鸟哥的快速回复。

我继续追问：

因为我用了多module,  所以想在这里通过判断模块名来获取 模块里的views, 然后`$dispatcher->setView` 模板引擎目录。

我目前想到的是在 对应的moudle里加个 Bootstrap.php， 然后通过插件加载这个文件，触发里面的设置模板银引擎的方法。

不知还有没有更高的方法？

**Comment by letwang** [comment]
已经解决 参考这里
https://github.com/letwang/HookPHP/blob/master/app/admin/controllers/Abstract.php
