### ISSUE TITLE
视图渲染

### ISSUE THREAD

**Issue by yinxiongfeng** [laruence/yaf#376]
针对多模块设置配置项，关闭视图渲染。比如我有个api模块 是否可以在config里配置关闭视图渲染。
针对多模块不同二级域名如何配置？

**Comment by JokerBruceChan** [comment]
@yinxiongfeng Yaf默认是开启了自动渲染，如果不想让他寻找模板可以在 action 中 return false 或者在bootstrap.php 中关闭渲染。
`Yaf_Dispatcher::getInstance()->autoRender(false); `

**Comment by laruence** [comment]
你也可以在action里面返回false,  阻止对当前的action的视图做渲染
