### ISSUE TITLE
在apache中，yaf访问yaf，apache会异常退出是为何？

### ISSUE THREAD

**Issue by shikaiguo** [laruence/yaf#381]
class IndexController extends Yaf_Controller_Abstract
{
    public function indexAction(){
        $str = file_get_contents('http://localhost/Index/test');
        exit($str);
    }
    public function testAction(){
        exit('test');
    }
}

访问 http://localhost/Index/index 会导致apache异常

**Comment by guyanyijiu** [comment]
我也遇到了这个问题，初步定位是第二个请求走到 new Yaf_Application 的时候就异常了，不过Apache并没有崩溃

**Comment by laruence** [comment]
错误信息是?

**Comment by guyanyijiu** [comment]
Apache 没有任何日志信息，我换了xampp出现Apache崩溃了，Windows提示程序已经停止运行

Windows记录的日志信息：
日志名称:          Application
来源:            Application Error
日期:            2018/1/3 15:53:52
事件 ID:         1000
任务类别:          (100)
级别:            错误
关键字:           经典
用户:            暂缺
计算机:           PC-20161230MFQQ
描述:
错误应用程序名称: httpd.exe，版本: 2.4.17.0，时间戳: 0x561cc534
错误模块名称: php_yaf.dll，版本: 7.2.0.0，时间戳: 0x5a206349
异常代码: 0xc0000005
错误偏移量: 0x000022e8
错误进程 ID: 0x15e0
错误应用程序启动时间: 0x01d38467fe85af48
错误应用程序路径: D:\xampp\apache\bin\httpd.exe
错误模块路径: D:\xampp\php7.2\ext\php_yaf.dll
报告 ID: 3d3b00ae-f05b-11e7-8975-a5e36680284c
事件 Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" />
    <EventID Qualifiers="0">1000</EventID>
    <Level>2</Level>
    <Task>100</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2018-01-03T07:53:52.000000000Z" />
    <EventRecordID>44830</EventRecordID>
    <Channel>Application</Channel>
    <Computer>PC-20161230MFQQ</Computer>
    <Security />
  </System>
  <EventData>
    <Data>httpd.exe</Data>
    <Data>2.4.17.0</Data>
    <Data>561cc534</Data>
    <Data>php_yaf.dll</Data>
    <Data>7.2.0.0</Data>
    <Data>5a206349</Data>
    <Data>c0000005</Data>
    <Data>000022e8</Data>
    <Data>15e0</Data>
    <Data>01d38467fe85af48</Data>
    <Data>D:\xampp\apache\bin\httpd.exe</Data>
    <Data>D:\xampp\php7.2\ext\php_yaf.dll</Data>
    <Data>3d3b00ae-f05b-11e7-8975-a5e36680284c</Data>
  </EventData>
</Event>

**Comment by kent-cheung** [comment]
同样遇到这个问题。
