### ISSUE TITLE
map路由协议到底怎么用？

### ISSUE THREAD

**Issue by qloog** [laruence/yaf#383]
看了官方手册，还是没明白使用的方法。

所以求给个demo, 来看下具体是怎么使用的。

**Comment by qloog** [comment]
@laruence  鸟哥有空给解答下呗 😃 , 实在是没理解  😢 ，也没找到对map使用的相关资料。

**Comment by owenliang** [comment]
/a/b#c/1/d/2，其中分隔符#。

若设置第一个参数controller亲和=true：那么会找到controller文件A_b，调用它的indexAction，参数c=1,d=2。

若设置第一个参数controller亲和=false：那么会找到controller文件Index，调用它的a_bAction，参数c=1,d=2。

从源码看大概就是这个意思，具体你试试。

**Comment by qloog** [comment]
## 实测如下：

> 若设置第一个参数controller亲和=false：那么会找到controller文件Index，调用它的a_bAction，参数c=1,d=2。
这个可以用，但是有俩个问题：
1. controller 只能是Index吗？ 不能换其他的？
2. 可以支持多模块么？ 如果支持怎么写？

> 若设置第一个参数controller亲和=true：那么会找到controller文件A_b，调用它的indexAction，参数c=1,d=2。
这样不行， 但是把A_b 换成比如：User 就可以测试通过。

**Comment by laruence** [comment]
map的诞生就是给微博当时用的, 他比较简单, 就是比如你的url是a/b/c 那么对应的controller就是A/B/C.php 里面的 A_B_CController,  并且只会执行indexAction(map路由器只路由到controller)
