### ISSUE TITLE
语法错误、致命错误，无法转到 ErrorController

### ISSUE THREAD

**Issue by wxxiong6** [laruence/yaf#385]
用户级别的错误可以转到ErrorController，但语法错误、致命错误，无法转到 ErrorController。

Bootstrap.php
function myErrorHandler($errno, $errstr, $errfile, $errline)
{
Logger::error("Unknown error type: [$errno] $errstr $errfile in line($errline)");
throw new Yaf\Exception("Unknown error type: [$errno] $errstr $errfile in line($errline)");
return true;
}

**Comment by motecshine** [comment]
你应该看看编译原理， 语法错误，致命错误，是在编译期语法编译器检测出来的，都没有到执行期 ，怎么跳转？

**Comment by wxxiong6** [comment]
使用 register_shutdown_function 可以捕获到语法错误、致命错误等错误，其他框架捕获错误，可以跳转到一个自定义的页面。

public function _initCatchFatal(){
		ini_set('display_errors', 'Off');
        register_shutdown_function( "fatalHandler" );
        set_error_handler("errorHandler");
    }
/*
 * 获取 fatal error
 */
function fatalHandler() {
    $error = error_get_last();
    if($error && ($error["type"]===($error["type"] & E_FATAL))) {
        $errno   = $error["type"];
        $errfile = $error["file"];
        $errline = $error["line"];
        $errstr  = $error["message"];
        errorHandler($errno,$errstr,$errfile,$errline);
    }
}
/*
 * 获取所有的 error
 */
function errorHandler($errno,$errstr,$errfile,$errline){
    $errstr = "Unknown error type: [$errno] $errstr $errfile in line($errline)";
}

**Comment by laruence** [comment]
本意还是希望只捕获和Yaf框架自身相关的异常....

**Comment by wxxiong6** [comment]
非常感谢鸟哥的解惑
