### ISSUE TITLE
提议: 是否可以用非编译的方式控制开启或者关闭 debug 模式(PHP_YAF_DEBUG变量)

### ISSUE THREAD

**Issue by freeaquar** [laruence/yaf#391]
如题, 我们最近在集成自动化测试, 所以对对CLI会关注一些, 目前碰到的问题是
1. debug 模式是编译参数, 导致自动化测试不能使用开发/线上的 yaf.so, 希望能统一
2. 有一定的超级变量修改的需求: $_GET, $_POST 等, 而这些控制选项, 而非 debug 版本不能满足这个需求

初步观看源代码, 感觉目前的诉求是能以非编译的方式控制 'PHP_YAF_DEBUG'

目前希望可以控制的方式:
1. php.ini 配置
2. 环境变量

**Comment by letwang** [comment]
https://github.com/letwang/HookPHP/blob/master/app/admin/init.php
`YAF\ENVIRON`
使用环境来区分

**Comment by sakmon** [comment]
遇到同样问题

**Comment by laruence** [comment]
新的版本不需要这个配置了
