### ISSUE TITLE
$_POST等全局变量在request期间只保存了一次，导致载入swoole后，无法动态赋予

### ISSUE THREAD

**Issue by qn9301** [laruence/yaf#398]

**Comment by qn9301** [comment]
虽然在apache等环境下的确之需要获取一次，但是使用swoole这种常驻内存后，就无法根据每次的request动态获取。

**Comment by qn9301** [comment]
我不是指这个，我是说，c部分的代码, Yaf_Request_Http这个类初始话的时候，$_POST是固定的，貌似是声明Yaf_Application的时候就读取缓存了的，所以用Yaf_Request_Http这个类获取$_POST的时候不会改变。用$_POST当然可以获取到最新的，但是这样就需要项目做修改了。。

**Comment by letwang** [comment]
的确如此 无法中途修改 这不是BUG 是功能 原理类似 http://php.net/manual/zh/function.filter-input.php
比如我这里https://github.com/letwang/HookPHP/blob/master/app/admin/controllers/Abstract.php
通过默认值解决
```
mb_parse_str(file_get_contents('php://input'), $result);
$this->_request->getPost('token', $result['token'] ?? null)
```
