### ISSUE TITLE
在命令行使用Yaf出现问题，求鸟哥帮忙看看！

### ISSUE THREAD

**Issue by wujunqi** [laruence/yaf#401]
电脑环境：yaf:3.0.5  php:7.1.7

`<?php
	ini_set('display_errors', 'On');
	error_reporting(1);
	define("APP_PATH",  realpath(dirname(__FILE__) . "/../../../"));
	$application = new Yaf_Application( APP_PATH . "/conf/application.ini", "product");
	$application->bootstrap()->execute("main", $argv);

	function main(){
		$obj = new Auth_ActionModel();
	}
?>`

上面的代码运行出现：
`PHP Fatal error:  Uncaught Error: Call to a member function execute() on boolean in /home/work/www/application/modules/System/cron_movie_wjq.php:6
Stack trace:
#0 {main}
  thrown in /home/work/www/application/modules/System/cron_movie_wjq.php on line 6

Fatal error: Uncaught Error: Call to a member function execute() on boolean in /home/work/www/application/modules/System/cron_movie_wjq.php:6
Stack trace:
#0 {main}
  thrown in /home/work/www/application/modules/System/cron_movie_wjq.php on line 6`

打印$application->bootstrap()为：

`object(Yaf_Application)#1 (7) {
  ["config":protected]=>
  object(Yaf_Config_Ini)#2 (2) {
    ["_config":protected]=>
    array(2) {
      ["application"]=>
      array(5) {
        ["directory"]=>
        string(28) "APPLICATION_PATH/application"
        ["system"]=>
        array(1) {
          ["library"]=>
          string(25) "APPLICATION_PATH/library/"
        }
        ["dispatcher"]=>
        array(4) {
          ["catchException"]=>
          string(1) "1"
          ["defaultModule"]=>
          string(5) "Index"
          ["defaultController"]=>
          string(5) "Index"
          ["defaultAction"]=>
          string(5) "index"
        }
        ["modules"]=>
        string(147) "Index,Admin,System,Auth,Api,Test,Page,Blog,Mds,Movie,Music,Open,Port,Mobile,Rington,Subject,Podcast,Sell,Show,Feed,Movieapp,Mingxing,Sale,Weixinapp"
        ["showErrors"]=>
        string(1) "0"
      }
      ["database"]=>
      array(1) {
        [3757]=>
        array(7) {
          ["adapter"]=>
          string(9) "pdo_mysql"
          ["dbname"]=>
          string(5) "caleb"
          ["host"]=>
          string(9) "127.0.0.1"
          ["username"]=>
          string(7) "wujunqi"
          ["password"]=>
          string(8) "041968Wo"
          ["charset"]=>
          string(4) "UTF8"
          ["port"]=>
          string(4) "3306"
        }
      }
    }
    ["_readonly":protected]=>
    bool(true)
  }
  ["dispatcher":protected]=>
  object(Yaf_Dispatcher)#4 (10) {
    ["_router":protected]=>
    object(Yaf_Router)#5 (2) {
      ["_routes":protected]=>
      array(1) {
        ["_default"]=>
        object(Yaf_Route_Static)#6 (0) {
        }
      }
      ["_current":protected]=>
      NULL
    }
    ["_view":protected]=>
    NULL
    ["_request":protected]=>
    object(Yaf_Request_Http)#3 (11) {
      ["module"]=>
      NULL
      ["controller"]=>
      NULL
      ["action"]=>
      NULL
      ["method"]=>
      string(3) "Cli"
      ["params":protected]=>
      array(0) {
      }
      ["language":protected]=>
      NULL
      ["_exception":protected]=>
      NULL
      ["_base_uri":protected]=>
      string(0) ""
      ["uri":protected]=>
      string(0) ""
      ["dispatched":protected]=>
      bool(false)
      ["routed":protected]=>
      bool(false)
    }
    ["_plugins":protected]=>
    array(0) {
    }
    ["_auto_render":protected]=>
    bool(true)
    ["_return_response":protected]=>
    bool(false)
    ["_instantly_flush":protected]=>
    bool(false)
    ["_default_module":protected]=>
    string(5) "Index"
    ["_default_controller":protected]=>
    string(5) "Index"
    ["_default_action":protected]=>
    string(5) "index"
  }
  ["_modules":protected]=>
  array(24) {
    [0]=>
    string(5) "Index"
    [1]=>
    string(5) "Admin"
    [2]=>
    string(6) "System"
    [3]=>
    string(4) "Auth"
    [4]=>
    string(3) "Api"
    [5]=>
    string(4) "Test"
    [6]=>
    string(4) "Page"
    [7]=>
    string(4) "Blog"
    [8]=>
    string(3) "Mds"
    [9]=>
    string(5) "Movie"
    [10]=>
    string(5) "Music"
    [11]=>
    string(4) "Open"
    [12]=>
    string(4) "Port"
    [13]=>
    string(6) "Mobile"
    [14]=>
    string(7) "Rington"
    [15]=>
    string(7) "Subject"
    [16]=>
    string(7) "Podcast"
    [17]=>
    string(4) "Sell"
    [18]=>
    string(4) "Show"
    [19]=>
    string(4) "Feed"
    [20]=>
    string(8) "Movieapp"
    [21]=>
    string(8) "Mingxing"
    [22]=>
    string(4) "Sale"
    [23]=>
    string(9) "Weixinapp"
  }
  ["_running":protected]=>
  bool(false)
  ["_environ":protected]=>
  string(7) "product"
  ["_err_no":protected]=>
  int(0)
  ["_err_msg":protected]=>
  string(0) ""
}
`

打印 $application->bootstrap()为：
`bool(false)`

去掉bootstrap后代码如下：

`<?php
	ini_set('display_errors', 'On');
	error_reporting(1);
	define("APP_PATH",  realpath(dirname(__FILE__) . "/../../../"));
	$application = new Yaf_Application( APP_PATH . "/conf/application.ini", "product");
	$application->execute("main", $argv);

	function main(){
		$obj = new Auth_ActionModel();
	}
?>`

运行结果为：

`PHP Fatal error:  Uncaught Error: Class 'Auth_ActionModel' not found in /home/work/www/application/modules/System/cron_movie_wjq.php:10
Stack trace:
#0 [internal function]: main(Array)
#1 /home/work/www/application/modules/System/cron_movie_wjq.php(6): Yaf_Application->execute('main', Array)
#2 {main}
  thrown in /home/work/www/application/modules/System/cron_movie_wjq.php on line 10

Fatal error: Uncaught Error: Class 'Auth_ActionModel' not found in /home/work/www/application/modules/System/cron_movie_wjq.php:10
Stack trace:
#0 [internal function]: main(Array)
#1 /home/work/www/application/modules/System/cron_movie_wjq.php(6): Yaf_Application->execute('main', Array)
#2 {main}
  thrown in /home/work/www/application/modules/System/cron_movie_wjq.php on line 10 
`

说我找不到model， 但是明明在models下啊， 用浏览器时可以访问到的， google了一天都没有找到原因。

**Comment by motecshine** [comment]
`PHP Fatal error: Uncaught Error: Call to a member function execute() on boolean in /home/work/www/application/modules/System/cron_movie_wjq.php:6 `

**Comment by letwang** [comment]
已经解决 参考这里
https://github.com/letwang/HookPHP/blob/master/app/admin/bin/install.php
