### ISSUE TITLE
Class 'Yaf_Application' not found‘错误

### ISSUE THREAD

**Issue by 1th** [laruence/yaf#405]
Yaf版本：3.0.7
$app  = new Yaf_Application(APPLICATION_PATH . "/conf/application.ini");
提示Class 'Yaf_Application' not found‘错误

**Comment by mengxiaotian** [comment]
确定自己是否安装了yaf扩展，web模式可使用PHP info()打印查看，cli模式使用php -m | grep yaf 或者php -i | grep yaf 这两个命令看一下是否加载yaf扩展。
如果确定已经安装yaf扩展，还有问题，再查看一下yaf的配置，在php.ini中，yaf.use_namespace是否打开，若为true，则要使用Yaf\Application。若为false，使用Yaf_Application。

**Comment by 1th** [comment]
@mengxiaotian  php.ini中没有添加yaf的配置。通过phpinfo()看了一下，yaf.use_namespace的默认配置是on,用Yaf\Application可以了。

**Comment by toddgoates** [comment]
Thank you. This helped me solve a `Class "Yaf\Application" not found` error in 2024.
