### ISSUE TITLE
建议 controllerName 支持多字母驼峰，也就是大小写敏感，严格一点好

### ISSUE THREAD

**Issue by infatu8** [laruence/yaf#408]
现有控制器 UserCenterController，当访问hostname/userCenter/ 时，系统实际找的是Usercenter.php

**Comment by daxiong123** [comment]
可以利用插件来重写 ``Yaf_Request_Abstract`` 里面的 ``controller`` 属性

**Comment by infatu8** [comment]
> 可以利用插件来重写 `Yaf_Request_Abstract` 里面的 `controller` 属性

目前我就是这么干了
不过有一个问题，每个应用都得写一个，能不能写一个公用插件，每个应用都用同一个插件

**Comment by letwang** [comment]
> 现有控制器 UserCenterController，当访问hostname/userCenter/ 时，系统实际找的是Usercenter.php

参考这个 已经解决 用 下划线
https://github.com/letwang/HookPHP/blob/master/app/admin/controllers/Acl/Group.php
