### ISSUE TITLE
鸟哥的文档里面的nginx配置错了，没人提这个吗？

### ISSUE THREAD

**Issue by hwanginsitein** [laruence/yaf#409]
if (!-e $request_filename) {
    rewrite ^/(.*)  /index.php/$1 last;
}

应该改成

if (!-e $request_filename) {
    rewrite ^/(.*)  /index.php?$1 last;
}

**Comment by infatu8** [comment]
其实并没错
前提是 pathinfo 你得整好

**Comment by hwanginsitein** [comment]
配了 PATH_INFO 会出现其他的问题

**Comment by letwang** [comment]
可以参考这里配置
https://github.com/letwang/HookPHP/blob/master/README.md
