### ISSUE TITLE
使用array config 进行Yaf_Application初始化时，会碰到interned string的坑

### ISSUE THREAD

**Issue by yangjian41727** [laruence/yaf#411]
下面的代码会触发这个错误

================分割线====================
define('MY_MODULE_NAME', 'test');
$config = array(
   'application' => array(
      'dispatcher' => array('defaultModule' => MY_MODULE_NAME,),
      'directory' => '/path/to/app',
   ),
   'modules' => 'test,other',
   // other configs
);
class TestClass{
    const I_AM_A_CONSTANT_STRING = 'test';
}
$i_am_another_val = 'test';

$app = new Ap_Application($config);
var_dump($i_am_another_val, TestClass::I_AM_A_CONSTANT_STRING);
// both output are 'Test'
================分割线====================

// 下面是触发问题的位置，zend_string_dup的内部实现是当 ZSTR_IS_INTERNED 为真时，直接返回原始字符串，源码中还有好多处使用 zend_string_dup 做深拷贝的地方

ap_application.c:211 - 213

AP_G(default_module) = zend_string_dup(Z_STR_P(psval), 0);
zend_str_tolower(ZSTR_VAL(AP_G(default_module)), ZSTR_LEN(AP_G(default_module)));
*ZSTR_VAL(AP_G(default_module)) = toupper(*ZSTR_VAL(AP_G(default_module)));

**Comment by yangjian41727** [comment]
不知道应该算bug还是啥，暂时只有定位问题的能力，没有一个比较好的修复方案，期待鸟哥的回复

**Comment by laruence** [comment]
你是在用AP? 不太清楚百度内部现在谁维护AP了?  其实简单点你可以下载Yaf的源代码, 改个名....:)

anyway,  修复的方案就是不要原地修改字符串,  而是复制一个, 然后修改...
