### ISSUE TITLE
php7.3.0 编译出错

### ISSUE THREAD

**Issue by infatu8** [laruence/yaf#421]
/usr/local/src/yaf-3.0.7/yaf_session.c: In function ‘yaf_session_instance’:
/usr/local/src/yaf-3.0.7/yaf_session.c:97:31: error: ‘ZEND_WRONG_PROPERTY_OFFSET’ undeclared (first use in this function); did you mean ‘IS_WRONG_PROPERTY_OFFSET’?
  if (property_info->offset != ZEND_WRONG_PROPERTY_OFFSET) {
                               ^~~~~~~~~~~~~~~~~~~~~~~~~~
                               IS_WRONG_PROPERTY_OFFSET
/usr/local/src/yaf-3.0.7/yaf_session.c:97:31: note: each undeclared identifier is reported only once for each function it appears in
Makefile:253: recipe for target 'yaf_session.lo' failed
make: *** [yaf_session.lo] Error 1

**Comment by ericjank** [comment]
yaf_session.c 加上 #include "Zend/zend_object_handlers.h" 试试
或者把ZEND_WRONG_PROPERTY_OFFSET先改成0

**Comment by valiner** [comment]
妈耶，我也是7.3编译出错了

**Comment by kimistar** [comment]
/Users/kimi/Downloads/yaf-3.0.7/yaf-3.0.7/yaf_session.c:97:31: error: use of undeclared identifier
      'ZEND_WRONG_PROPERTY_OFFSET'
        if (property_info->offset != ZEND_WRONG_PROPERTY_OFFSET) {
                                     ^
/Users/kimi/Downloads/yaf-3.0.7/yaf-3.0.7/yaf_session.c:293:68: warning: incompatible pointer types
      passing 'unsigned long *' to parameter of type 'zend_ulong *' (aka 'unsigned long long *')
      [-Wincompatible-pointer-types]
        if (zend_hash_get_current_key(Z_ARRVAL_P(Z_REFVAL_P(sess)), &key, &index) == HASH_KEY_IS_LONG) {
                                                                          ^~~~~~
/usr/local/Cellar/php/7.3.0/include/php/Zend/zend_hash.h:225:46: note: expanded from macro
      'zend_hash_get_current_key'
        zend_hash_get_current_key_ex(ht, str_index, num_index, &(ht)->nInternalPointer)
                                                    ^~~~~~~~~
/usr/local/Cellar/php/7.3.0/include/php/Zend/zend_hash.h:211:117: note: passing argument to parameter
      'num_index' here
  ...zend_hash_get_current_key_ex(const HashTable *ht, zend_string **str_index, zend_ulong *num_index...
                                                                                            ^
1 warning and 1 error generated.
make: *** [yaf_session.lo] Error 1

**Comment by wxuns** [comment]
修改yaf_session.c中的 ZEND_WRONG_PROPERTY_OFFSET 为 ZEND_WRONG_PROPERTY_INFO

**Comment by shencw** [comment]
这个问题怎么处理的

**Comment by wxuns** [comment]
直接在github clone下来编译

**Comment by oreak** [comment]
官方解决办法　yaf_session.c
#if PHP_VERSION_ID < 70300
	if (property_info->offset != ZEND_WRONG_PROPERTY_OFFSET)
#else
	if (IS_VALID_PROPERTY_OFFSET(property_info->offset))
#endif

**Comment by 0ostreamo0** [comment]
it seemed a zend constant variable is missing now in php7.3.2, i'm encountering the same problem：
description:
------------------
[error]
php-7.3.2/ext/yaf/yaf_session.c:97:31: error: use of undeclared identifier 'ZEND_WRONG_PROPERTY_OFFSET'
        if (property_info->offset != ZEND_WRONG_PROPERTY_OFFSET) {
......

[env]
PHP 7.3.2 (cli) (built: Mar  1 2019 14:17:26) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.2, Copyright (c) 1998-2018 Zend Technologies

**Comment by worker-lyn** [comment]
编辑      yaf_session.c
加上     #define ZEND_WRONG_PROPERTY_OFFSET   0

**Comment by letwang** [comment]
PHP7.3.6是好的
