### ISSUE TITLE
Nginx+Apache PHP模块502错误

### ISSUE THREAD

**Issue by jiangbaiyan** [laruence/yaf#424]
Nginx作代理，上游为Apache的PHP module，PHP版本7.1.7，yaf框架版本3.0.7。
这个问题是在调接口过程中发生的，不是所有请求都会出现，但频率较高。
Nginx错误日志直接报上游无响应，此处略。
Apache错误日志：
![qq20181227-0](https://user-images.githubusercontent.com/23721125/50486057-fcf3f600-0a32-11e9-822c-fe8227f2c750.png)
使用gdb调试的backtrace：
<img width="1429" alt="wx20181227-232000 2x" src="https://user-images.githubusercontent.com/23721125/50504991-11280980-0aac-11e9-92f1-e9078bc49ee5.png">
代码上下文如下图所示。app变量是zval *类型。ZVAL_IS_NULL这个宏会去判断app所指向的zval结构体中的type字段是否为IS_NULL类型。但经过gdb打印，这里zend_read_static_property()方法的返回值（即app）地址为0x0，指向了一个无效地址。接下来去访问其所指向的内容一定是非法的。在方法内部，看起来是在声明一个zval *property的变量的时候没有成功，但是不清楚具体原因，想请教一下大家。
zend_read_static_property()方法的上下文：
![wx20181230-174824](https://user-images.githubusercontent.com/23721125/50546024-dc5ab480-0c5b-11e9-8015-e7d67c4638f5.png)
zend_read_static_property()方法内部调试：
![wx20181228-141907](https://user-images.githubusercontent.com/23721125/50504942-c6a68d00-0aab-11e9-8572-f87150a3492e.png)
zend_read_static_property()方法体：
![wx20181230-180021](https://user-images.githubusercontent.com/23721125/50546104-11b3d200-0c5d-11e9-994c-b3d7adb5063b.png)

**Comment by graper-guo** [comment]
同想知道在yaf_application.c中调用zend_read_static_property这个函数传了三个参数，为什么gdb会打印出四个参数，这个char *name是在哪里赋值的

**Comment by laruence** [comment]
新版本应该已经修复这个问题
