### ISSUE TITLE
Yaf_Route_Regex 参数配置的问题

### ISSUE THREAD

**Issue by regedit** [laruence/yaf#432]
new Yaf_Route_Regex(
           "#/articles/([\d]+)#", 
           [
                'module'=>'index',
                'controller'=>'articles',
                'action'=>'view'
            ],
            [
                1=>'id'
            ],
            [],
            '/articles/:id/'
        )
以上是我配置的路由，我调用assemble([':id'=>123])后返回的是/articles/:id，请问是我创建路由的方法不正确吗？如何解决这个问题？

**Comment by letwang** [comment]
请使用静态路由 性能最高

**Comment by laruence** [comment]
assemble只能针对m, c, a, 对于这种参数的，目前还不行.
