### ISSUE TITLE
$router->addConfig 通过配置加载regex类型的路由时【reverse】属性的BUG

### ISSUE THREAD

**Issue by regedit** [laruence/yaf#433]
'articles/view'=>[
            'type'=>'regex',
            'match'=>'#/articles/([\d]+)#',
            'route'=>[
                'module'=>'index',
                'controller'=>'articles',
                'action'=>'view'
            ],
            'map'=>[
                1=>'id'
            ],
            'reverse'=>'/articles/:id'
        ]
我发现以上的配置在addConfig时，属性reverse无法设置，阅读了源文件：yaf_route_interface.c
在第88行发现以下的代码：
if ((reverse = zend_hash_str_find(Z_ARRVAL_P(config), ZEND_STRL("route"))) == NULL ||
			Z_TYPE_P(reverse) != IS_STRING) {
			reverse = NULL;
		}
--------------
ZEND_STRL("route")这里应该是错了吧，我改成reverse上面的代码就可以正常运行了。

**Comment by shyandsy** [comment]
@regedit 感谢 解决了

**Comment by letwang** [comment]
666

**Comment by laruence** [comment]
fixed.
