### ISSUE TITLE
新手学习安装时，缺少文件Bootstrap.php

### ISSUE THREAD

**Issue by yingnan1314** [laruence/yaf#439]
对于新手来讲，根据readme步骤写demo，会缺少Bootstrap.php文件，建议加上。这是在php.net上找到的
`<?php
/**
 * This file should be under the APPLICATION_PATH . "/application/"(which was defined in the config passed to Yaf_Application).
 * and named Bootstrap.php,  so the Yaf_Application can find it 
 */
class Bootstrap extends Yaf_Bootstrap_Abstract {
    function _initConfig(Yaf_Dispatcher $dispatcher) {
//        echo "1st called\n";
    }

    function _initPlugin($dispatcher) {
//        echo "2nd called\n";
    }
}
?>`

**Comment by letwang** [comment]
建议参考https://github.com/letwang/HookPHP/blob/master/app/admin/Bootstrap.php

**Comment by yulonghu** [comment]
https://github.com/laruence/yaf/tree/master/tools/cg
