### ISSUE TITLE
请问一下yaf还在维护吗？

### ISSUE THREAD

**Issue by systoms** [laruence/yaf#441]
配置文件
```
application.dispatcher.defaultModule = "api"
```

函数
```
$dispatcher->setDefaultModule("Panel")
->setDefaultController("Index")
->setDefaultAction("index");
```

以上配置和函数没有任何作用，在php网站bug中只有一条类似的问题，https://bugs.php.net/bug.php?id=76217

这个问题貌似已经存在很久，不知道作者是否还在维护这个框架！

```
system os macos

PHP Version 7.2.13

yaf Version  3.0.7
```

**Comment by phpseven** [comment]
曲线救国一下
在扩展里面写

``

application/plugins/Tc.php

class TcPlugin extends Plugin_Abstract {
        public function routerShutdown(Request_Abstract $request, Response_Abstract $response) 
$app_config = Application::app()->getConfig();
                //module bind to defaultModule static
                if(!empty($app_config['application']['dispatcher']['defaultModule'])){
                $request->setModuleName($app_config['application']['dispatcher']['defaultModule']);
                }
