### ISSUE TITLE
关于action被声明为private后还可以调用问题

### ISSUE THREAD

**Issue by hanzhipu** [laruence/yaf#444]
想知道为什么PHP代码中action被声明为private的了还是可以被接口调用成功呢。 
不太懂C语言，想了解下原因。 是在调用方法之前将方法设置为access了么

**Comment by letwang** [comment]
先规避吧 不用纠结 可以参考https://github.com/letwang/HookPHP/

**Comment by laruence** [comment]
因为不是按照常规调用方式来调用的， 毕竟Yaf是在扩展层面，可以做很多“特权”的事情。

**Comment by qizekai** [comment]
神奇的调用逻辑啊
