### ISSUE TITLE
PHP 7.4 support

### ISSUE THREAD

**Issue by remicollet** [laruence/yaf#445]
Build fails for now
```
/dev/shm/BUILD/php74-php-pecl-yaf-3.0.8/NTS/views/yaf_view_simple.c: In function 'yaf_view_exec_tpl':
/dev/shm/BUILD/php74-php-pecl-yaf-3.0.8/NTS/views/yaf_view_simple.c:169:9: error: too many arguments to function 'zend_vm_stack_push_call_frame'
  call = zend_vm_stack_push_call_frame(ZEND_CALL_NESTED_CODE
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /opt/remi/php74/root/usr/include/php/Zend/zend_API.h:29,
                 from /opt/remi/php74/root/usr/include/php/main/php.h:37,
                 from /dev/shm/BUILD/php74-php-pecl-yaf-3.0.8/NTS/views/yaf_view_simple.c:21:
/opt/remi/php74/root/usr/include/php/Zend/zend_execute.h:222:46: note: declared here
 static zend_always_inline zend_execute_data *zend_vm_stack_push_call_frame(uint32_t call_info, zend_function *func, uint32_t num_args, void *object_or_called_scope)
                                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
make[1]: *** [Makefile:224: views/yaf_view_simple.lo] Error 1

```

**Comment by letwang** [comment]
7.4 还没有发布稳定版 请使用7.3

**Comment by phpseven** [comment]
/var/www/html/yaf/views/yaf_view_simple.c: In function 'yaf_view_exec_tpl':
/var/www/html/yaf/views/yaf_view_simple.c:169:9: error: too many arguments to function 'zend_vm_stack_push_call_frame'
  call = zend_vm_stack_push_call_frame(ZEND_CALL_NESTED_CODE
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/local/include/php/Zend/zend_API.h:29,
                 from /usr/local/include/php/main/php.h:37,
                 from /var/www/html/yaf/views/yaf_view_simple.c:21:
/usr/local/include/php/Zend/zend_execute.h:219:46: note: declared here
 static zend_always_inline zend_execute_data *zend_vm_stack_push_call_frame(uint32_t call_info, zend_function *func, uint32_t num_args, void *object_or_called_scope)
                                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
make: *** [Makefile:223: views/yaf_view_simple.lo] Error 1
make: *** Waiting for unfinished jobs....



同求, 马上就要发布 7.4了....

**Comment by letwang** [comment]
> /var/www/html/yaf/views/yaf_view_simple.c: In function 'yaf_view_exec_tpl':
> /var/www/html/yaf/views/yaf_view_simple.c:169:9: error: too many arguments to function 'zend_vm_stack_push_call_frame'
> call = zend_vm_stack_push_call_frame(ZEND_CALL_NESTED_CODE
> ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> In file included from /usr/local/include/php/Zend/zend_API.h:29,
> from /usr/local/include/php/main/php.h:37,
> from /var/www/html/yaf/views/yaf_view_simple.c:21:
> /usr/local/include/php/Zend/zend_execute.h:219:46: note: declared here
> static zend_always_inline zend_execute_data *zend_vm_stack_push_call_frame(uint32_t call_info, zend_function *func, uint32_t num_args, void *object_or_called_scope)
> ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> make: *** [Makefile:223: views/yaf_view_simple.lo] Error 1
> make: *** Waiting for unfinished jobs....
> 
> 同求, 马上就要发布 7.4了....

还有2天

**Comment by phpseven** [comment]
坐等7.4
(⊙o⊙)…

**Comment by letwang** [comment]
> 坐等7.4
> (⊙o⊙)…

官网已经发布7.4了

**Comment by letwang** [comment]
7.4安装yaf果然报错 期望作者解决

**Comment by laruence** [comment]
done.

**Comment by atmouse-** [comment]
ref: https://github.com/laruence/yaf/commit/a1c04c91daf84d7a77f818671bb97185f18a2d9e

**Comment by MrJackDuaner** [comment]
Good morning,
In the lastest release YAF 3.0.9 for Windows taking into account build for PHP 7.4, there is no DLL file for PHP 7.4, but only for PHP 7.3 and PHP 7.2.
I would like to know if there will be DLL files for PHP 7.4 for YAF 3.0.9 ?
Best regards,
MrJackDuaner

**Comment by MrJackDuaner** [comment]
Good afternoon,
As this issue is closed, I have opened a new one : [464](https://github.com/laruence/yaf/issues/464)
I tried building DLL from PHP and YAF sources but got error just for YAF.
Best regards,
MrJackDuaner
