### ISSUE TITLE
Yaf\Controller_Abstract::__get($name)无故会被调用一次

### ISSUE THREAD

**Issue by RoyDong** [laruence/yaf#45]
我继承了Yaf\Controller_Abstract，重写了__get方法，发现在无任何实例属性访问时，系统仍然会自动执行一次该方法，

例如：__get($name){ echo $name; } 每次访问都会额外输出 yafAutoRender。

本想在controller里加一个便捷的访问模块的方法。

**Comment by sunbiao0526** [comment]
yaf 能调用__get 魔术方法吗？造成模板渲染失败, Yaf_Application::app() 为NULL
