### ISSUE TITLE
使用 Yaf debug 模式出现问题

### ISSUE THREAD

**Issue by sakmon** [laruence/yaf#452]
yaf版本：3.0.8
php版本: 7.3.6
phpunit版本：7.0.3
系统：CentOS Linux release 7.6.1810 (Core)
Linux version 3.10.0-957.el7.x86_64 (mockbuild@kbuilder.bsys.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-36) (GCC) ) #1 SMP Thu Nov 8 23:39:32 UTC 2018

#389 跟这个问题一样
使用 HTTP 请求可以正常返回
使用 Cli 模式时候, 使用 Yaf_Request_Simple 构造 Request
在代码中执行: new Yaf_Application($this->config); 时候报错

执行命令返回信息如下：
-------------------------------------------------------------------------------------
[root@localhost tests]# phpunit --debug --verbose
PHPUnit 7.0.3 by Sebastian Bergmann and contributors.

Runtime:       PHP 7.3.6
Configuration: /mnt/hgfs/Project/yh/tests/phpunit.xml

Test 'tests\api\IndexTest::testTest' started
段错误
----------------------------------------------------------------------------------------

只有加 --enable-yaf-debug 编译后才会出现以上问题, 正常编译可以正常运行。

**Comment by jiangxiulong** [comment]
这也没人给回复啊

**Comment by laruence** [comment]
段错误后的backtrace你贴一下？ 否则我也没东西重现啊

**Comment by laruence** [comment]
新版本去掉了php-yaf-debug, 默认支持phpunit，你可以试试master分支代码
