### ISSUE TITLE
docker-php7.4编译安装yaf时报错，求解决方案

### ISSUE THREAD

**Issue by zkyy66** [laruence/yaf#454]
/tmp/yaf-yaf-3.0.8/views/yaf_view_simple.c: In function 'yaf_view_exec_tpl':
/tmp/yaf-yaf-3.0.8/views/yaf_view_simple.c:169:9: error: too many arguments to function 'zend_vm_stack_push_call_frame'
  call = zend_vm_stack_push_call_frame(ZEND_CALL_NESTED_CODE
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/local/include/php/Zend/zend_API.h:29,
                 from /usr/local/include/php/main/php.h:37,
                 from /tmp/yaf-yaf-3.0.8/views/yaf_view_simple.c:21:
/usr/local/include/php/Zend/zend_execute.h:219:46: note: declared here
 static zend_always_inline zend_execute_data *zend_vm_stack_push_call_frame(uint32_t call_info, zend_function *func, uint32_t num_args, void *object_or_called_scope)
                                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
make: *** [Makefile:223: views/yaf_view_simple.lo] Error 1

**Comment by letwang** [comment]
同求解决方案 7.4安装yaf报错

**Comment by laruence** [comment]
A new package has been released. please try to reinstall.
