### ISSUE TITLE
php7.4 pecl install yaf error 

### ISSUE THREAD

**Issue by shikaiguo** [laruence/yaf#455]
/tmp/pear/temp/yaf/views/yaf_view_simple.c: In function ‘yaf_view_exec_tpl’:
/tmp/pear/temp/yaf/views/yaf_view_simple.c:174:4: error: too many arguments to function ‘zend_vm_stack_push_call_frame’
    (zend_function*)op_array, 0, op_array->scope, Z_OBJ_P(view));
    ^
In file included from /opt/php/7.4/include/php/Zend/zend_API.h:29:0,
                 from /opt/php/7.4/include/php/main/php.h:37,
                 from /tmp/pear/temp/yaf/views/yaf_view_simple.c:21:
/opt/php/7.4/include/php/Zend/zend_execute.h:219:46: note: declared here
 static zend_always_inline zend_execute_data *zend_vm_stack_push_call_frame(uint32_t call_info, zend_function *func, uint32_t num_args, void *object_or_called_scope)
                                              ^
make: *** [views/yaf_view_simple.lo] Error 1
ERROR: `make' failed

**Comment by laruence** [comment]
A new package was released, please check it out.
