### ISSUE TITLE
3.1.2版本 控制器内调用 $this->_request->getRequest() 奔溃 (ERROR 503)

### ISSUE THREAD

**Issue by phpseven** [laruence/yaf#466]
测试环境centos php 7.3 + yaf 3.1.2
另外windows 环境  php 7.3 + yaf 3.1.2 也一样
``
class ApiController extends \Yaf\Controller_Abstract {

    public function xxAction()  //
    {
        var_dump($_REQUEST); // 直接打印$_REQUEST ok，
        var_dump($this->_request->getRequest('xxx')); //获取REQUEST内值，ok 
        var_dump($this->_request->getRequest());exit;   //程序奔溃， 旧版本 3.0.8可以使用，如不方便修复我就用$_REQUEST也可以咯

**Comment by laruence** [comment]
代码中修复了， 不过可能要等几天再发新版，积攒一些问题吧， 你可以拉取master自己编译

**Comment by phpseven** [comment]
多谢大佬
