### ISSUE TITLE
关于Yaf_Request_Http的getQuery和getPost无法过滤的问题

### ISSUE THREAD

**Issue by tutuyu23** [laruence/yaf#467]
在controller的方法中已经对$_POST、$_GET、$_REQUEST中的重新赋值为空数组，
然后再浏览器中请求：http://www.dx.com/index/index/index?name=test_name&age=test_age
分别打印出各方法的取值：
var_dump($_GET);    $_GET输出为空
var_dump($_REQUEST);    $_REQUEST输出为空
var_dump($this->getRequest()->get('name'));     变量name输出为空
var_dump( $this->getRequest()->getRequest());   输出为空，说明清空$_REQUEST对Yaf_Request_Http的getRequest()方法的取值是有效的
var_dump($this->getRequest()->getQuery());  输入不为空，打印出了['name'=>'test_name','age'=>'test_age']，说明清空$_GET和$_REQUEST对Yaf_Request_Http的getQuery()方法的取值是无效的
同样如果是post请求，那么清空$_POST和$_REQUEST对Yaf_Request_Http的getPost()方法的取值是无效的
请问如何处理才能影响Yaf_Request_Http的getPost()方法和Yaf_Request_Http的getQuery()方法的取值？想在公共方法中对用户输入数据进行统一过滤

简单事例：
class BaseController extends Yaf_Controller_Abstract {
    
    public function init() {
        
        try {
            // 输入数据过滤方法
            // 但发现$this->getRequest()->getQuery()和$this->getRequest()->getPost()获取的数据无法被过滤
            // 清空$_GET、$_POST、$_REQUEST
            $_GET=$_POST=$_REQUEST=[];
            var_dump($_GET);
            var_dump($_POST);
            var_dump($_REQUEST);
            var_dump($this->getRequest()->getRequest());
            var_dump($this->getRequest()->getPost());  // 没有得到预期的结果
            var_dump($this->getRequest()->getQuery());  // 没有得到预期的结果
        }
        catch (Exception $e) {
            
        }
        
    }
    
}

**Comment by laruence** [comment]
你使用的是那个版本的Yaf

**Comment by tutuyu23** [comment]
3.0.9

**Comment by laruence** [comment]
你试试新版的3.1.3， 3.0.x不支持覆盖。

**Comment by tutuyu23** [comment]
好的，那我试一下，谢谢

**Comment by tutuyu23** [comment]
可以了，但是不是getRequest、getQuery、getPost方法都改了，必需传名称获取指定的值了？不能获取全部了？

**Comment by laruence** [comment]
你可以不传名字，获取全部的值啊

**Comment by tutuyu23** [comment]
我试过了，$this->getRequest()->getQuery()直接就报502 Bad Gateway错误了，必需$this->getRequest()->getQuery('name')这样才可以运行，我下载的是php_yaf-3.1.2-7.3-ts-vc15-x64.zip这个版本的，我用的是windows，3.1.3还没有windows版的，php是7.3.9，nginx是1.17.3
nginx错误日志记录的是：
2020/03/23 18:45:31 [error] 4348#17156: *38 WSARecv() failed (10054: An existing connection was forcibly closed by the remote host) while reading response header from upstream, client: 127.0.0.1, server: www.dx.com, request: "GET /index/index/index/name/zs/age/1s0?name=zs&age=1s0 HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "www.dx.com"
2020/03/23 18:45:33 [error] 4348#17156: *38 connect() failed (10061: No connection could be made because the target machine actively refused it) while connecting to upstream, client: 127.0.0.1, server: www.dx.com, request: "GET /index/index/index/name/zs/age/1s0?name=zs&age=1s0 HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "www.dx.com"

**Comment by laruence** [comment]
噢，3.1.2有问题， 但是3.1.3因为pecl的windows building系统出问题了，dll暂时出不来，需要过几天。 你等下过几天下载了3.1.3的dll就可以了

**Comment by tutuyu23** [comment]
好的，谢谢

**Comment by laruence** [comment]
https://pecl.php.net/package/yaf/3.1.3/windows 已经有了

**Comment by tutuyu23** [comment]
好的，谢谢，我试一下，有问题再请教
