### ISSUE TITLE
class名称是 Autocontroller，无法正常自动加载

### ISSUE THREAD

**Issue by moetakaoruko** [laruence/yaf#469]
我的一个文件class名称是 Autocontroller，文件名是 Autocontroller.php，结果autoload去找了 Auto.php 而不是去找 Autocontroller.php

文件是在Library目录，声明查找方法为：
Yaf_Loader::getInstance()->setLibraryPath(ROOT_PATH . '/framework/library', true);

Yaf 版本 3.1.3 有问题
换回 3.0.9 正常

PHP版本7.4.0

**Comment by laruence** [comment]
你设置了yaf.name_suffix和yaf.name_separator了么？

**Comment by laruence** [comment]
如果都没设置，那应该是3.0.9的实现有问题， AutoController.php看起来应该是一个控制器的名字

**Comment by moetakaoruko** [comment]
> 你设置了yaf.name_suffix和yaf.name_separator了么？

没有设置这2项，之前PHP7.2用的3.0.6，PHP7用3.0.2也是没有这个问题的。

> 如果都没设置，那应该是3.0.9的实现有问题， AutoController.php看起来应该是一个控制器的名字

class名称是 Autocontroller 不是 AutoController，大小写不敏感？

**Comment by laruence** [comment]
hmm,  你说的对，我来修复下

**Comment by laruence** [comment]
已经修复， 明天发个新版吧,  谢谢发现这个问题 :)

**Comment by laruence** [comment]
3.1.4已经发布在pecl上了,  https://pecl.php.net/yaf
