### ISSUE TITLE
为什么在Controller中取不到$_GET?

### ISSUE THREAD

**Issue by lpisces** [laruence/yaf#47]
若用正则路由的话,规则有点复杂了？

可能我没找到合适的方法，但是我用getQuery拿不到数据。

谢谢~

**Comment by nisnaker** [comment]
我也遇到同样的问题：

`uri: /api/script?a=b&c=d`

在控制器中`print_r($_GET)`只能得到:
```
Array
(
    [s] => /api/script
)
```
`print_r($_SERVER)`结果如下：
```
[QUERY_STRING] => s=/api/script
......
[REQUEST_URI] => /api/script?a=b&c=d
```
