### ISSUE TITLE
Yaf\Loader::autoload() 文件的文件名为什么都是小写？？

### ISSUE THREAD

**Issue by jiaxian** [laruence/yaf#470]
一台机器Centos 7.7 PHP 7.3.13 yaf-3.0.9 没有问题，别一台机器 Centos 7.7 PHP 7.4.4 yaf-3.1.4 有问题
Bootstrap.php如下：
`class Bootstrap extends xl\yaf\Bootstrap {`

Warning: Yaf\Loader::autoload(): Failed opening script /www/shop/library/xl/yaf/bootstrap.php: No such file or directory in /www/shop/member/mvc/Bootstrap.php on line 19

Warning: Yaf\Application::bootstrap(): Couldn't find class Bootstrap in /www/shop/member/mvc/Bootstrap.php in /www/shop/member/public/index.php on line 5

Fatal error: Uncaught Error: Class 'xl\yaf\Bootstrap' not found in /www/shop/member/mvc/Bootstrap.php:19 Stack trace: #0 [internal function]: unknown() #1 /www/shop/member/public/index.php(5): Yaf\Application->bootstrap() #2 {main} thrown in /www/shop/member/mvc/Bootstrap.php on line 19

我的centos 7 “/www/shop/library/xl/yaf/Bootstrap.php”

**Comment by jiaxian** [comment]
还有下面的，帮吗看看：
Fatal error: Uncaught Yaf\Exception\LoadFailed\Controller: Failed opening controller script /www/shop/member/mvc/controllers/error.php: No such file or directory in /www/shop/member/public/index.php:5 Stack trace: #0 /www/shop/member/public/index.php(5): Yaf\Application->run() #1 {main} thrown in /www/shop/member/public/index.php on line 5

我的centos下是/www/shop/member/mvc/controllers/Error.php，大写，为什么会找/www/shop/member/mvc/controllers/error.php

**Comment by laruence** [comment]
解决了？

**Comment by jiaxian** [comment]
解决了，application.ini中配置有application.system.lowcase_path = TRUE，删除就好了，只机器Centos 7.7 PHP 7.3.13 yaf-3.0.9中没有影响，机器 Centos 7.7 PHP 7.4.4 yaf-3.1.4 同样的配置文件名全部得小写

**Comment by laruence** [comment]
嗯， 好， 一般都是环境影响
