### ISSUE TITLE
ErrorController::errorAction($exception) 形参名字问题

### ISSUE THREAD

**Issue by infatu8** [laruence/yaf#472]
yaf 用于统一处理异常的方法 ErrorController::errorAction($exception)
形参用 $exception时正常，用其他的如 $e 会发生fatal error

fatal error信息形同:
Fatal error: Uncaught ArgumentCountError: Too few arguments to function ErrorController::errorAction(), 0 passed and exactly 1 expected in ....../api/controllers/Error.php:13

**Comment by laruence** [comment]
这个是设计的限制，Yaf设计了request->setParam, 你可以通过这个设置一些参数，这些参数会按照名字传递给controller， 也就是说， 比如你request->setParam了一个参数名字叫做foo，
那么你的errorController无论 定义errorAction($foo, $exception),还是定义成errorAction($exception, $foo), 都可以正常传递，这个前提是，参数名必须确定。
