### ISSUE TITLE
Yaf_Controller_Abstract::getResponse返回类型错误？

### ISSUE THREAD

**Issue by uax** [laruence/yaf#475]
测试更新了下 master分支，PSR-4 命名空间没问题了。
但是 ```Yaf\Controller_Abstract::getResponse``` 返回值好像有问题，
现在 master 分支返回的是：```Yaf\Response\Cli```，
应该是```Yaf\Response\Http```吧？

**Comment by laruence** [comment]
有例子代码么？
我检测没问题， 如果你是在命令行下运行，那应该是返回cli的response

**Comment by uax** [comment]
3.2.1-dev，yaf_cg 生成的例子，控制器 Index.php ：
```
public function indexAction($name = "Stranger") {
	print_r($this->getResponse());
        return false;
}
```
结果如下：
```
Yaf\Response\Cli Object
(
    [response_code:protected] => 0
    [header_sent:protected] => 
)
```

**Comment by laruence** [comment]
你是在浏览器访问还是命令行访问？

**Comment by uax** [comment]
浏览器。
用的 PHP 内置服务器:
```
php -S localhost:8000
```
```
http://localhost:8000
```
按说不应该啊，前几个版本都正常。我刚切换回 yaf-3.1.4试了一下，输出 ```Yaf\Response\Http```。

**Comment by laruence** [comment]
好，我看下

**Comment by laruence** [comment]
已经修复， 你真是个好QA， ：）

**Comment by uax** [comment]
刚拉取果然 OK 了。
感谢修复！

**Comment by laruence** [comment]
我今天晚点再先发一个版本， 修复之前那个registerNamespace的问题
