### ISSUE TITLE
鸟哥进来看

### ISSUE THREAD

**Issue by sydboys** [laruence/yaf#476]
1、增加Yaf_Dispatcher :: setResponse（Yaf_Response_Abstract $response ）

2、Yaf_Request 和 Yaf_Response 增加 Yaf_Response_Interface、Yaf_Response_Interface，
相应的参数类型改为接口，如：
Yaf_Dispatcher::setRequest ( Yaf_Request_Interface $request ) 
public function routerStartup(Yaf_Request_Interface $request, Yaf_Response_Interface $response) 
等

**Comment by laruence** [comment]
看到了， 要不你提个PR试试？

**Comment by laruence** [comment]
setReponse想不出来啥应用场景啊

**Comment by sydboys** [comment]
PR就算了。c太菜了：）

考虑如下场景；
$response = $this->getResponse();
$response->setHeader('404','Not Found');
$response->setHeader("Content-Type", "application/json; charset=utf-8");
$response->setHeader("Res-Type", "json");
$response->setBody(json_encode(['code' => 10000, 'msg' => 'action not found']));
$response->response();

如果可以自定义Response，那么我们可以将一些逻辑封装起来，简化输出，封装更多特性，如文件下载，json/jsonp输出,xml输出等。
如：
$output = ['code' => 10000, 'msg' => 'action not found'];
$response->setStatus('404')->setHandler(new JsonHandler($output))->response();
利用Trait类，二次封装，简化为
$response->setStatus('404')->json($output);
同时plugin中也可以获取这个Response，进行一些处理等。

**Comment by laruence** [comment]
嗯，应用于REST，好，我来想想。

**Comment by sydboys** [comment]
：）

**Comment by infatu8** [comment]
看到3.2我也想说这个
尤其在ErrorController::errorAction中，由于出现了异常，yaf的生命周期没有走完，即使在 bootstrap中做了一些设置，如下
$dispatcher->autoRender(false);
$dispatcher->disableView();
$dispatcher->flushInstantly(false);
$dispatcher->returnResponse(true);

然后人工调用 Response::response() 时，并不如理想那样
$Response->setHeader('Content-Type', 'application/json');
$Response->setBody(json_encode($json));
$Response->response();

实际会输出两次 json，并且Application::run()也没有返回response对象

**Comment by infatu8** [comment]
再提一个，我司项目基于swoole+yaf的强强结合
由于swoole中不允许exit，故而希望控制器能根据Controller::init() 的返回值 true|false决定要不要继续执行下去 。
如 默认路由 /user/info 会去找UserController::infoAction()，UserController有个init()方法，并且UserController继承自BaseController，BaseController中也有init()方法
希望当在BaseController::init()中return false时，后面的UserController那部分也不必执行了

**Comment by letwang** [comment]
https://github.com/letwang/HookPHP/blob/master/app/admin/controllers/Base/Api.php#L16
https://github.com/letwang/HookPHP/blob/master/app/admin/controllers/Base/Abstract.php#L43

**Comment by laruence** [comment]
> 看到3.2我也想说这个

这个不应该啊， 如果你设置了return response， 它不应该自动输出才对。 
是哪个版本的yaf？

**Comment by infatu8** [comment]
> > 看到3.2我也想说这个
> 
> 这个不应该啊， 如果你设置了return response， 它不应该自动输出才对。
> 是哪个版本的yaf？

3.0.9   3.1.4 在ErrorController:errorAction() 中会这样
其他正常业务，或者人工catch 的exception是正常的

**Comment by laruence** [comment]
errorController重复输出的问题应该解决了。
