### ISSUE TITLE
关于$_POST、$_GET、$_REQUEST对象中的原始数据被改变的问题

### ISSUE THREAD

**Issue by tutuyu23** [laruence/yaf#478]
yaf版本3.2.1
从前端页面提交加密后的密码到后台
如：password=khdED4ui0ohx0wj3Rw6QBkoZTxMElV9sZIwK9ICi5R7UDaJQSh27pAnhYJMDi3GTxoQMQP+MVbeyHyMcdKktFkk+6TVtBoQjIA/1grie51eGOTYS4FI/HxlPBDq3PJ4VgzWEPRETNFfwJ4ArVtzK3f1zCBWzHgWBzQuecJ0T76Y=
在后台查看$_POST、$_GET、$_REQUEST中收到的password变量，结果值中的“+”号都被替换为“空格”了，并不是原始的数据，导致解密失败
例：echo $_REQUEST['password']=khdED4ui0ohx0wj3Rw6QBkoZTxMElV9sZIwK9ICi5R7UDaJQSh27pAnhYJMDi3GTxoQMQP MVbeyHyMcdKktFkk 6TVtBoQjIA/1grie51eGOTYS4FI/HxlPBDq3PJ4VgzWEPRETNFfwJ4ArVtzK3f1zCBWzHgWBzQuecJ0T76Y=

请注意：原始数据“QMQP+MVbey”变成了“QMQP MVbey” “Fkk+6TV”变成了“Fkk 6TV”

**Comment by laruence** [comment]
这个跟Yaf没关系, 参看：https://www.php.net/manual/en/reserved.variables.get.php
````
The GET variables are passed through urldecode().
````
