### ISSUE TITLE
Yaf_Loader [bug] 

### ISSUE THREAD

**Issue by Sgenmi** [laruence/yaf#479]
开启了命名空间
在models 文件夹下创建A model

```
<?php
  namespace Model;
  class A {
}
?>
````

在控制器中调用 
 $model = new \Model\A();
报错
Fatal error: Uncaught Error: Class 'Model\A' not found
经测试 plugin命名空间也是一样 报错

环境：Mac os  10.15.4   MAMP集成环境 yaf编译安装

PHP: 7.4.1
yaf: 3.1.4

**注：yaf:3.0.9 正常，之后版本 是不是要用  Yaf_Loader::getNamespacePath() 自定义加载路径？**

**Comment by laruence** [comment]
你试着设置 yaf.name_suffix=0 呢？

**Comment by Sgenmi** [comment]
> 你试着设置 yaf.name_suffix=0 呢？

以上结果，就是yaf.name_suffix=0 测试的

**Comment by laruence** [comment]
yaf.name_separator设置了什么? \\ 还是 _

**Comment by laruence** [comment]
应该已经修复了，你可以看测试用例的变化

**Comment by Sgenmi** [comment]
> 应该已经修复了，你可以看测试用例的变化

![1589034872897](https://user-images.githubusercontent.com/3337501/81476639-829dcd80-9245-11ea-88af-3666a643b0cb.jpg)

问题仍然存在。我看了用例，貌似都没有打开命名空间。 实际使用中，都是打开命名空间

**Comment by laruence** [comment]
name_sparator应该是 \\才对

**Comment by Sgenmi** [comment]
> name_sparator应该是 \才对, 原来3.0.9能这么用啊？

3.0.9 之前 都可以这么用，如果把name_sparator=‘\’   这样会报找不到控制器
![1589121878238](https://user-images.githubusercontent.com/3337501/81502378-28b60a00-9310-11ea-94e2-0ba73a835c95.jpg)
 
经过我测试，把控制器也改为命名空间，竟然可以了。如下
`
 <?php 
   namespace Controller;
  class Error extends \Yaf\Controller_Abstract {
   }
`

看到你的issue中，提到控制器不能命名空间化，有modules的问题。

所以这个问题应该还是存在的。 如果你有空的话，可以，看我的这个yaf配置。偿试一下。

3.0.9 之前 name_sparator=‘_’   控制器是按Controller_Error来查找。开了命名空间，model,plugin   都是按命名空间查找 如：\Model\User

**Comment by laruence** [comment]
modues只是影响去那个目录找controller的问题，不影响类型判断，应该还好。
这个应该是之前的实现有问题，没有正确处理_和\\作为name_separator, 你如果改成\\没问题，就先这么用吧？

**Comment by Sgenmi** [comment]
@laruence 
暂时我切回3.0.9了。 因为我分module 。希望后面能用上新版本

**Comment by laruence** [comment]
分module不影响啊？

**Comment by laruence** [comment]
我是/module/只是影响去哪个目录找mca，不影响自动加载的命名（意思是说，跟这个问题没关系）
