### ISSUE TITLE
Out of memory

### ISSUE THREAD

**Issue by pluto-er** [laruence/yaf#483]
访问默认地址 就Out of memory (allocated 4194304) (tried to allocate 18446744072677808488 bytes)

18446744072677808488 的内存明现错误 

环境：windows   PHP 7.3.4  nginx1.15.11

请问这是怎么回事？

**Comment by laruence** [comment]
哪个版本的yaf？

**Comment by laruence** [comment]
请尝试最新版的yaf，如果还有问题，可以reopen这个issue
