### ISSUE TITLE
期待处理 modules下controllers 命名空间的问题

### ISSUE THREAD

**Issue by Sgenmi** [laruence/yaf#484]
期待处理 modules下controllers 命名空间的问题  现默认 controllers 下，已有 Controller\xxx;
modules下的暂还没有发现可用命名空间

**Comment by laruence** [comment]
具体是啥样的需求呢？

**Comment by Sgenmi** [comment]
> 具体是啥样的需求呢？

yaf:配置
 yaf.use_namespace=1
 yaf.name_separator=\
 yaf.name_suffix=0

如果现在分了多模块 
/modules/admin/controllers/Index.php, 
/modules/web/controllers/Index.php  
那么对应Index.php 的命令空间怎么写。可以让Yaf\Loader找到对应目录下控制器

**Comment by laruence** [comment]
你是说多个同名index controller冲突？

**Comment by Sgenmi** [comment]
我知道处理。是我的写法有问题。和默认控制器命名空间一样即可。3.2.5 测试全通过。
