### ISSUE TITLE
3.2.3 setLibraryPath设置后提示找不到类

### ISSUE THREAD

**Issue by vergil1989** [laruence/yaf#489]
由3.1.4升级到3.2.3 调用setLibraryPath后提示LibraryPath里的类找不到，是功能有变更吗？
yaf配置如下：
Version => 3.2.3
Supports => http://pecl.php.net/package/yaf

Directive => Local Value => Master Value
yaf.library => no value => no value
yaf.environ => product => product
yaf.forward_limit => 5 => 5
yaf.use_namespace => 1 => 1
yaf.action_prefer => 1 => 1
yaf.lowcase_path => 0 => 0
yaf.use_spl_autoload => 1 => 1
yaf.name_suffix => 1 => 1
yaf.name_separator => no value => no value

**Comment by laruence** [comment]
你给个测试代码？  是setlibrary设置global library么？

**Comment by vergil1989** [comment]
代码:
index.php
`<?php

use Yaf\Application;
use Yaf\Loader;


error_reporting(E_ALL);
ini_set('display_errors', 1);

define('APP_NAME', 'Test');

$app = new Application([
    'application' => [
        'directory' => __DIR__
    ]
]);

$loader = Loader::getInstance();
$loader->setLibraryPath(__DIR__.'/Global/Library', true);

use Core\Hello;
(new Hello())->say();`

Hello.php
代码路径:./Global/Library/Core/Hello.php
`<?php
namespace Core;

class Hello{
    public function say(){
        echo 'Hello Yaf!';
    }
}`

**3.2.3**
→ php --ri yaf
yaf
yaf support => enabled
Version => 3.2.3
Supports => http://pecl.php.net/package/yaf

Directive => Local Value => Master Value
yaf.action_prefer => 1 => 1
yaf.environ => product => product
yaf.forward_limit => 5 => 5
yaf.library => no value => no value
yaf.lowcase_path => 0 => 0
yaf.name_separator => no value => no value
yaf.name_suffix => 1 => 1
yaf.use_namespace => 1 => 1
yaf.use_spl_autoload => 1 => 1

执行结果：
→ php index.php 
PHP Fatal error:  Uncaught Error: Class 'Core\Hello' not found in /Users/vergil/dev/yaf-test/index.php:23
Stack trace:
#0 {main}
  thrown in /Users/vergil/dev/yaf-test/index.php on line 23

Fatal error: Uncaught Error: Class 'Core\Hello' not found in /Users/vergil/dev/yaf-test/index.php:23
Stack trace:
#0 {main}
  thrown in /Users/vergil/dev/yaf-test/index.php on line 23

**3.1.4**
php --ri yaf
yaf
yaf support => enabled
Version => 3.1.4
Supports => http://pecl.php.net/package/yaf

Directive => Local Value => Master Value
yaf.action_prefer => On => On
yaf.environ => product => product
yaf.forward_limit => 5 => 5
yaf.library => no value => no value
yaf.lowcase_path => Off => Off
yaf.name_separator => no value => no value
yaf.name_suffix => On => On
yaf.use_namespace => On => On
yaf.use_spl_autoload => On => On

执行结果：
→ php index.php         
Hello Yaf!

**Comment by laruence** [comment]
明白了，我想想， 暂时你你可以通过设置一个namespace来规避， 
````
$loader->registerNamespace(“\Core”, “/Global/Library/Core”)；
````

**Comment by vergil1989** [comment]
好， 我先这么处理一下， 感谢！

**Comment by laruence** [comment]
新版本发布了，包含了对这个问题的修复。
