### ISSUE TITLE
请求web服务时, uri参数两个参数名相同出现 502

### ISSUE THREAD

**Issue by LiangGen283850** [laruence/yaf#490]
host.com/index.php/controller/action/param/1/param/2 

Linux version 3.10.0-957.21.3.el7.x86_64 (mockbuild@kbuilder.bsys.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-36) (GCC) ) #1 SMP Tue Jun 18 16:35:19 UTC 2019

PHP 7.4.5 (cli) (built: Apr 29 2020 18:16:09) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies

yaf
yaf support => enabled
Supports => http://pecl.php.net/package/yaf
yaf.action_prefer => Off => Off
yaf.environ => develop => develop
yaf.forward_limit => 5 => 5
yaf.library => no value => no value
yaf.lowcase_path => Off => Off
yaf.name_separator => no value => no value
yaf.name_suffix => On => On
yaf.use_namespace => On => On
yaf.use_spl_autoload => On => On

**Comment by laruence** [comment]
是用默认的路由？

**Comment by LiangGen283850** [comment]
YES




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Xinchen Hui"<notifications@github.com&gt;; 
发送时间: 2020年5月28日(星期四) 中午12:20
收件人: "laruence/yaf"<yaf@noreply.github.com&gt;; 
抄送: "盲聋"<2838508893@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [laruence/yaf] 请求web服务时, uri参数两个参数名相同出现 502 (#490)





 
是用默认的路由？
 
— 
您收到此消息是因为您创建了线程。
直接回复此电子邮件，在GitHub上查看，或取消订阅。

**Comment by laruence** [comment]
好，知道了，应该已经修复了， 过几天发个新版。 thanks :)
