### ISSUE TITLE
从3.0.9升级到3.2.4的一些变化和需要解决的问题

### ISSUE THREAD

**Issue by lilj** [laruence/yaf#492]
鸟哥你好，这是升级遇到的一些问题， 希望能得到你的帮助，特别是最后的plugin问题。

1, 配置读取，如果section不存在，会报错
PHP Fatal error:  Uncaught Yaf_Exception: There is no section 'test' in '.../conf/application.ini'
这个之前是不会的，section配置不在就读取global的嘛。

2, setModuleName 如果为空，以前是用默认的"Index"的，加载 app/controller/Index.php
   现在会去查找 app/modules//controller/Index.php。

3, Controller 的 init 方法，以前是 protected, 现在必须都是 public 了。
这个项目挺多，要修改起来比较有风险。

4,  yafAutoRender 和 Plugin 的一些问题无法解决
```php
<?php
final class Index_Controller extends Yaf_Controller_Abstract{

	public function indexAction() {

		$this->yafAutoRender = false; // 关闭渲染ok
		$this->yafAutoRender = true;  // 开启渲染ok
		$this->yafAutoRender = false; // 再次关闭渲染不ok, 代码无效？？？ 

		echo 'hi'; //可以输出
		$this->view->download_url = '/download?target=yyb';
		echo ' you'; //可以输出
		
		//include_once '/opt/yaf/Example/app/plugins/Debug.php';
		Yaf_Dispatcher::getInstance()->registerPlugin(new Debug_Plugin());
		//这里加入的plugin无效了，以前是可以的, plugin 里面只是简单的测试， 
                //我们的代码里需要通过plugin在preDispatch中修改输出，比如用json encode view 的变量。
             

	} 	
}
```

**Comment by lilj** [comment]
卸载 remi 的3.2.4， 用pecl安装降级到3.1.4， 解决了。

**Comment by laruence** [comment]
1. 这个问题，我觉得还是当前的行为是更合适的，要精确指定section
4.的话，你可能需要调用enableView（）之类的方法来设置
其他的，应该修复了

**Comment by lilj** [comment]
谢谢回复及时修复。我有时间测试一下。

**Comment by laruence** [comment]
发布了新版，3.2.5， 2，3 应该解决了

**Comment by shyandsy** [comment]
@laruence 
问题3，我这里也存在
前任在设计的时候，init方法中一旦出现exception，需要调用controller基类中的processor。

如果是直接this->processor()调用，后续action会继续执行，我们不希望如此。
所以前任的方法是this->forward(processor),基类中定义processorAction

问题来了：
1. 3.2.5版本限定了，不许forward到protected方法，理论上这没问题
2. 如果我想在init中放弃后续action执行，可否给个return false之类的方法，跳过action执行

我看了下源码，大约是这样
1. yaf controller里面，如果没有异常返回0， 否则init返回1

![image](https://user-images.githubusercontent.com/5271457/87638360-38b9f200-c776-11ea-894c-521a4c51e58d.png)

2. 如果init throw exception，则后续都不会执行，yaf_dispatcher.c
![image](https://user-images.githubusercontent.com/5271457/87638236-014b4580-c776-11ea-836f-82a6f4bc4ccc.png)

我目前好像还不（实）太（力）能（有）够（限）给他加个return false，使其跳过action。。。。
