### ISSUE TITLE
v3.2路由解析问题

### ISSUE THREAD

**Issue by infatu8** [laruence/yaf#493]
1) 访问 /userCenter/info时，发生fatal error
Recoverable fatal error: Yaf\Application::run(): Failed opening controller script ....../controllers/Usercenter.php: No such file or directory

2) 访问 /user/vipInfo时，发生fatal error
Recoverable fatal error: Yaf\Application::run(): There is no method vipInfoAction in UserController

解析: 也就是说，在路由解析过程中，把controler以及action名称全部转成了小写，然后再首字母大写，仅首字母大写，在类unix平台上controller类文件就找不到了，windows由于不区分大小写，故没问题。

注: v3.0通过plugin在routerShutdown时刻指定Request相关属性可以解决问题，v3.2用plugin也不行了

**Comment by laruence** [comment]
如果你需要全部lowercase，你设置yaf.lowcase_path？

**Comment by infatu8** [comment]
yaf.lowcase_path = off

一直用的都是 CamelCase，也就是 访问/userCenter/vipInfo 或 /UserCenter/VipInfo时，期望的是UserCenterController::vipInfoAction()

**Comment by infatu8** [comment]
其实这个问题，只要能在plugin中修改Request的controller 和action等相关属性就能解决

**Comment by infatu8** [comment]
其实这个问题，只要在plugin能修改Request的mocule/controller/action这些相关的属性，就能得到解决。
目前v3.2是这样，在plugin中 
```php
var_dump($Request);
$Request->controller = 'UserCenter';
$Request->action = 'VipInfo';
var_dump($Request);die;
```
output
```text
object(Yaf\Request\Http)#7 (10) {
  ["method"] => string(3) "GET"
  ["module"] => string(5) "Index"
  ["controller"] => string(10) "Usercenter"
  ["action"] => string(7) "vipinfo"
  ["uri:protected"] => string(19) "/UserCenter/VipInfo"
  ["base_uri:protected"] => NULL
  ["dispatched:protected"] => bool(false)
  ["routed:protected"] => bool(true)
  ["language:protected"] => string(0) ""
  ["params:protected"] => array(0) {
  }
}
object(Yaf\Request\Http)#7 (10) {
  ["method"] => string(3) "GET"
  ["module"] => string(5) "Index"
  ["controller"] => string(10) "Usercenter"
  ["action"] => string(7) "vipinfo"
  ["uri:protected"] => string(19) "/UserCenter/VipInfo"
  ["base_uri:protected"] => NULL
  ["dispatched:protected"] => bool(false)
  ["routed:protected"] => bool(true)
  ["language:protected"] => string(0) ""
  ["params:protected"] => array(0) {
  }
}
```

**Comment by laruence** [comment]
那你可以这样
````
$request->setControllerName(“UserCenter”, false); 
````
注意第二个参数false，表示告诉Yaf不要格式化这个名字

**Comment by shyandsy** [comment]
controller文件名LuckyTurntable.php， 3.2以后报错无法找到Luckyturnt.php

```
Failed opening controller script 。。。。。/application/controllers/Luckyturn.php: No such file or directory"
```

我们请求url:  {{domain}}/luckyTurn/xxxx


yaf 3.0.9正常， 3.2.x可否支持只对首字母大写，后续不变
