### ISSUE TITLE
重写Plugin_Abstract 时对Request_Abstract->controller 赋值失败，使用setControllerName也失败

### ISSUE THREAD

**Issue by cc623213878** [laruence/yaf#498]
请问这个是什么原因？
版本3.2.5，php7.3.19

use Yaf\Plugin_Abstract as YafPlugin;
use Yaf\Request_Abstract as YafRequest;
use Yaf\Response_Abstract as YafResponse;

class RoutePlugin extends YafPlugin
{

    /**
     * @param YafRequest $request
     * @param YafResponse $response
     * @return true
     */
    public function routerShutdown(YafRequest $request, YafResponse $response)
    {
        $uri = $request->getRequestUri();

        if ($uri === '/api') {
            $this->apiForward($request);
            return true;
        }
        $uri = substr($uri,1);

        $arr = explode('/', $uri);

        if (count($arr) == 2) {
            $str = $arr[0];
            $request->controller = $str;
            echo $request->controller;
        } elseif (count($arr) == 3) {
            $request->controller = $arr[1];
        }
    }

**Comment by laruence** [comment]
$request->controller现在是protected属性。

请使用$request->setControllerName();

**Comment by cc623213878** [comment]
我使用$request->setControllerName();一样会报错误，之后的业务没有处理。

**Comment by laruence** [comment]
报什么错呢？

**Comment by cc623213878** [comment]
就是找不到控制器，因为我的控制器都是使用的驼峰写法

**Comment by laruence** [comment]
我的意思是，比如你在$request->setControllerName()之后，var_dump一下， 看看你是否设置成功了，如果是因为大小写跟你设置的不一样，你可以通过调用setControllerName()的时候，传递第二个参数，类似:
````
$request->setControllerName($str, false);//false表示告诉yaf不要格式化这个名字，用原始格式
````
