### ISSUE TITLE
构造 Yaf_Request_Simple 对象时传入 params 参数，但是这个对象中 params 属性为空数组？

### ISSUE THREAD

**Issue by simtfer** [laruence/yaf#499]
在文件 test.php 文件中构造一个 Yaf_Request_Simple 对象，然后命令行启动：
```php
<?php
$params = array('a'=>'a', 'b'=>'b');
$yaf_request = new Yaf\Request\Simple(NULL, NULL, 'controller', 'action', $params);
```
命令行运行 `php test.php`
打印 yaf_request 对象，或者调用它的 getParams 方法，里面的 params 属性都是空数组。只能通过它的 setParam 方法传入。
为什么构造对象的时候传入参数不行？

**Comment by laruence** [comment]
当时写的时候好像是忘了，哈哈 应该修复了
