### ISSUE TITLE
yaf下module层路由失败的问题

### ISSUE THREAD

**Issue by vvvva110** [laruence/yaf#500]
yaf_Application不释放的情况下，第一次请求访问"域名/module/controller/action"可以正常返回，第二次访问请求访问"域名/controller/action"的时候还是返回第一次请求的"域名/module/controller/action"的结果，前后两次请求的controller和action一致，使用Dispatcher的dispatch()函数重新分发请求，第二次虽然dispatcher内的属性变了，但是请求返回的结果依旧是第一次请求的结果，请问这是什么原因导致的？是我哪个地方使用的不对吗？

**Comment by laruence** [comment]
yaf_application不释放是啥意思？ 你是说一个脚本中，dispatch俩次不同请求？

**Comment by vvvva110** [comment]
> yaf_application不释放是啥意思？ 你是说一个脚本中，dispatch俩次不同请求？

我把yaf_application放到swoole的进程里面了，我用swoole和php-fpm做的对比，发现php-fpm的两次请求是没问题的。其实相当于一个脚本中去dispatch两次不同请求，两次请求都返回了第一次请求的结果。

**Comment by laruence** [comment]
你试试把request打印出来，看看路由结果有啥变化没有。 理论上不应该，每次dispatche都会清空response

**Comment by vvvva110** [comment]
> 你试试把request打印出来，看看路由结果有啥变化没有。 理论上不应该，每次dispatche都会清空response

> 
![image](https://user-images.githubusercontent.com/30078623/86078350-73851000-ba7d-11ea-9bfe-794a36da237e.png)
这个是我打印的第一次请求的数据，红线标注的是在访问controller里面打印普通字符串，用来区分不同controller的；
![image](https://user-images.githubusercontent.com/30078623/86078416-a0392780-ba7d-11ea-9f0e-eb09b432fa9d.png)
这个是我打印的第二次请求的数据，虽然request是变了，但是访问的controller还是第一次请求的controller。所以感到奇怪。
![image](https://user-images.githubusercontent.com/30078623/86078676-25244100-ba7e-11ea-8505-f12c5f195b96.png)
这个第一次请求的module下的controller函数，
![image](https://user-images.githubusercontent.com/30078623/86078843-877d4180-ba7e-11ea-9ef4-6d9cde6478bc.png)
这个是理论上应该访问的第二次请求的默认controller函数，
我在preDispatch里面和controller里面都输出了request信息，这两个地方输出的request信息是一致的。

**Comment by laruence** [comment]
俩个Controller的类名一样么？

**Comment by vvvva110** [comment]
> Controller



> 俩个Controller的类名一样么？

类名是一样的

**Comment by laruence** [comment]
嗯，这就是问题了，PHP的自动加载，如果发现类名存在就会直接使用，所以第二次的controller不会被加载，还是会执行第一次的。

**Comment by vvvva110** [comment]
> 嗯，这就是问题了，PHP的自动加载，如果发现类名存在就会直接使用，所以第二次的controller不会被加载，还是会执行第一次的。

有点没太明白，yaf不是去对应module下去找第二次的controller了吗？是说在yaf_dispatcher_get_controller里面因为PHP的自动加载实际上获取到的是第一次的controller类呢？

**Comment by laruence** [comment]
因为你是在一个PHP生命周期内，不能出现俩个同样名字的类名，否则就会:
````
PHP Fatal error:  Cannot redeclare class  XXXXX
````

**Comment by vvvva110** [comment]
> 因为你是在一个PHP生命周期内，不能出现俩个同样名字的类名，否则就会:
> 
> ```
> PHP Fatal error:  Cannot redeclare class  XXXXX
> ```

多谢鸟哥

**Comment by shyandsy** [comment]
@laruence 

我这里现在swoole套yaf来处理请求

我用module来区分api版本，假设有modules: v1, v1.1, 我本地测试发现不同module下controller class同名是没问题的

为什么没有出现cannot redeclare class???


我这里swoole接受http request，然后创建Yaf_Request_Http并dispatch
