### ISSUE TITLE
请问下如何配置Valet的LocalValetDriver?

### ISSUE THREAD

**Issue by osenv** [laruence/yaf#505]
不知道大家开发环境有没有使用Valet的，https://laravel.com/docs/7.x/valet

在应用根目录添加了一个LocalValetDriver.php后，一直提示访问错误Failed opening controller script No such file or directory

麻烦帮看看，谢谢！

**Comment by Jeddy** [comment]
> 不知道大家开发环境有没有使用Valet的，https://laravel.com/docs/7.x/valet
> 
> 在应用根目录添加了一个LocalValetDriver.php后，一直提示访问错误Failed opening controller script No such file or directory
> 
> 麻烦帮看看，谢谢！

**Comment by Jeddy** [comment]
> 不知道大家开发环境有没有使用Valet的，https://laravel.com/docs/7.x/valet
> 
> 在应用根目录添加了一个LocalValetDriver.php后，一直提示访问错误Failed opening controller script No such file or directory
> 
> 麻烦帮看看，谢谢！

您这个问题解决了吗？ 我也是 yaf 用 valet 环境，url 中必须带有 index.php 才能正确访问，不知道怎么配置 nginx，如果您解决了，向您请教下。谢谢。

**Comment by osenv** [comment]
抱歉，我已经放弃使用valet了。
