### ISSUE TITLE
路径支持文件夹小写，php文件名大写（驼峰）吗

### ISSUE THREAD

**Issue by moqinchanyuan** [laruence/yaf#513]
我有一个class叫 Model_Service_Page_Sample_TestSample 直接使用 new Model_Service_Page_Sample_TestSample(); 提示文件不存在。
如果设置 yaf.lowcase_path = 0，将路径修改为 APP_PATH/models/Service/Page/Sample/TestSample.php 可以使用
如果设置 yaf.lowcase_path = 1，将路径修改为 APP_PATH/models/service/page/sample/testsample.php 可以使用。
可以支持这样的文件路径吗 APP_PATH/models/service/page/sample/TestSample.php。

**Comment by laruence** [comment]
新版本可以支持了，可以参看 https://github.com/laruence/yaf/commit/9103ca164f34cd4fad620abfa56669c0ec58f4aa#diff-e27b6dd330cd80304442b2af668d21b957ea3057da89c4de66a53a9dea9cedf2
