### ISSUE TITLE
yaf环境下使用composer开启psr 4自动加载真的影响性能么 

### ISSUE THREAD

**Issue by shyandsy** [laruence/yaf#515]
我看到网上说开启psr 4自动加载会影响yaf性能，对此我不是很理解，如果是这样的话，为什么会？烦请鸟哥给解答一下。

我自己的想法是这样的
1. 开启psr 4自动加载就是在class not found时候，根据类名找到一个类文件，加载进来。
2. 对于同一个类，这个过程只会触发一次，并不会持续发生

相比传统的启动之初加载所有文件，这里只是多了一次文件加载。似乎并没有太多性能影响。

麻烦鸟哥有空解答一下

**Comment by laruence** [comment]
不会
