### ISSUE TITLE
只能访问到index

### ISSUE THREAD

**Issue by sansanboy** [laruence/yaf#516]
访问地址：
http://192.168.33.10:21800/index/tt
代码

![image](https://user-images.githubusercontent.com/4065370/94430122-98446d00-01bd-11eb-9c28-d886116a3b99.png)

看到的日志：

`{"cn":"Index","ac":"index","mn":"Index","url":"\/index\/tt"`

只能访问到index/index中。

yaf 版本降到：3.0.8
php 7.0
ubuntu 18.04 
nginx/1.14.0

**Comment by sansanboy** [comment]
location / {
        if (!-e $request_filename){
            rewrite ^/(.*)$ /index.php/$1 last;
        }
    }
配置修改成这样解决

**Comment by sansanboy** [comment]
已自行解决

**Comment by lushaoming** [comment]
> location / {
> if (!-e $request_filename){
> rewrite ^/(.*)$ /index.php/$1 last;
> }
> }
> 配置修改成这样解决

我按照你这样改的，访问其他地址直接500了，YAF版本是3.2.5。查日志发现是无限循环重定向
[error] 1640#0: *81806 rewrite or internal redirection cycle while processing "/index.php/index.php/index.php/index.php/index.php/index.php/index.php/index.php/index.php/index.php/index.php/notification/getNotifications", client: 113.89.35.18, server: www.xxx.com, request: "GET /notification/getNotifications HTTP/1.1", host: "www.xxx.com"

我的完整配置：
server {
 listen 80;
 server_name www.xxx.com;
 root /usr/local/nginx/html/xxx/api/public;
 client_max_body_size 20m;
 location ~ \.php$ {
     fastcgi_pass 127.0.0.1:9000;
     fastcgi_index index.php;
     fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
     fastcgi_param PATH_INFO $fastcgi_script_name;
     include fastcgi_params;
 }
    location / {
       index index.php index.html index.htm;
        if (!-e $request_filename){
           rewrite ^/(.*)$ /index.php/$1 last;
        }
    }
}

**Comment by lushaoming** [comment]
> 已自行解决

你好，怎么解决的，我的是3.2.5，PHP7.4
我的完整配置：
server {
listen 80;
server_name www.xxx.com;
root /usr/local/nginx/html/xxx/api/public;
client_max_body_size 20m;
location ~ .php$ {
fastcgi_pass 127.0.0.1:9000;
fastcgi_index index.php;
fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
fastcgi_param PATH_INFO $fastcgi_script_name;
include fastcgi_params;
}
location / {
index index.php index.html index.htm;
if (!-e $request_filename){
rewrite ^/(.*)$ /index.php/$1 last;
}
}
}
