### ISSUE TITLE
action方法名是个驼峰的命名的问题

### ISSUE THREAD

**Issue by chenliq** [laruence/yaf#517]
有个控制器：UserController，有一个方法：miniAppLoginAction

1.  默认路由解析获取到会被自动全部转成小写：miniapplogin，如果我在控制器定义，希望对特定action方法做统一的处理，就需要将所有方法名转成全小写后设置。这个通常不影响使用，但是强迫症有点接受不了。
2. 同样这个action，我调用$request->setActionName($actionName, false);注意第二个参数，在新版加入了这个参数，那我获取到的action名确实是我预期的miniAppLogin，但是框架插件的routerShutdown里面调用这个方法后，会报错：Error: There is no method miniAppLoginAction in UserController::$actions。但是我忽然第2个参数就可以正常执行。即：$request->setActionName($actionName); 但是我代码里面的通用配置处理还是仍然要把所有的action名称当成全小写的方式处理，相当于新版新增的这个参数没有什么意义

**Comment by laruence** [comment]
不好意思，最近丢了token，一直登陆不上来，刚刚看到，我没太看明白你的第二个问题，是说routeShutdown中你直接调用$controller->miniAppLoginAction? （我也猜猜你啥意思。

**Comment by laruence** [comment]
应该已经修复，可以参看 https://github.com/laruence/yaf/commit/9103ca164f34cd4fad620abfa56669c0ec58f4aa#diff-e27b6dd330cd80304442b2af668d21b957ea3057da89c4de66a53a9dea9cedf2

**Comment by chenliq** [comment]
> 应该已经修复，可以参看 [9103ca1#diff-e27b6dd330cd80304442b2af668d21b957ea3057da89c4de66a53a9dea9cedf2](https://github.com/laruence/yaf/commit/9103ca164f34cd4fad620abfa56669c0ec58f4aa#diff-e27b6dd330cd80304442b2af668d21b957ea3057da89c4de66a53a9dea9cedf2)

早上看到更新 Fixed issue #513 (supports of custom camel MVC name)，试了下，果然成功了
