### ISSUE TITLE
3.2.5中Response->setRedirect还是返回200

### ISSUE THREAD

**Issue by aiquestion** [laruence/yaf#518]
```
class TestAction extends Yaf_Action_Abstract {
	public function run() {
			$this->getResponse()->setRedirect($info['download_url']);
			return false;
	}
}
```
直接调用response 的 setRedirect还是会返回200
修改为 $this->redirect(xxx) 是可以的

php 7.4  yaf 3.2.5

**Comment by aiquestion** [comment]
做了一下比较蠢的“二分查找“，一直到yaf-3.1.4分支都是没问题的
3.2.0开始我的程序会报一些奇怪的问题（Yaf+Smarty的，找不到SmartAdaptor的类），只有3.2.4可以找到了，但是getResponse()->setRedirect()就失效了。

**Comment by laruence** [comment]
应该是修复了
