### ISSUE TITLE
php8.0好像不支持

### ISSUE THREAD

**Issue by cqzhangyunhua** [laruence/yaf#522]
加上扩展就报警告
PHP Warning:  Missing arginfo for Yaf_Dispatcher::__construct() in Unknown on line 0
PHP Warning:  Missing arginfo for Yaf_Request_Http::__construct() in Unknown on line 0
PHP Warning:  Missing arginfo for Yaf_Request_Simple::__construct() in Unknown on line 0
PHP Warning:  Missing arginfo for Yaf_Request_Simple::isXmlHttpRequest() in Unknown on line 0
PHP Warning:  Missing arginfo for Yaf_Response_Abstract::__toString() in Unknown on line 0
PHP Warning:  Missing arginfo for Yaf_Action_Abstract::execute() in Unknown on line 0
PHP Warning:  Missing arginfo for Yaf_Action_Abstract::getController() in Unknown on line 0
PHP Warning:  Missing arginfo for Yaf_Action_Abstract::getControllerName() in Unknown on line 0
PHP Warning:  Missing arginfo for Yaf_Router::addRoute() in Unknown on line 0
PHP Warning:  Missing arginfo for Yaf_Router::addConfig() in Unknown on line 0
PHP Warning:  Missing arginfo for Yaf_Router::route() in Unknown on line 0
PHP Warning:  Missing arginfo for Yaf_Registry::__construct() in Unknown on line 0
PHP Warning:  Missing arginfo for Yaf_Session::__construct() in Unknown on line 0

**Comment by cqzhangyunhua** [comment]
期待8.0的支持

**Comment by phpseven** [comment]
期待8.0的支持

**Comment by osenv** [comment]
期待8.0的支持 +1

**Comment by defender-11** [comment]
我这儿有个在做兼容的分支,还在开发测试中,可以先试试 https://github.com/defender-11/yaf/tree/defender-php8.0

**Comment by shagondu** [comment]
> 我有个在做兼容的分支,还在开发测试中,可以先试试 https://github.com/defender-11/yaf/tree/defender-php8.0

debian php8.0 编译报错

**Comment by defender-11** [comment]
请贴一下报错信息

**Comment by defender-11** [comment]
> > 我有个在做兼容的分支,还在开发测试中,可以先试试 https://github.com/defender-11/yaf/tree/defender-php8.0
> 
> debian php8.0 编译报错

请贴一下，报错信息

**Comment by phpseven** [comment]
忍不住，自己捣鼓了一下，
https://github.com/phpseven/yaf
使用原生php😀

**Comment by renxiaotu** [comment]
> 忍不住，自己捣鼓了一下，
> https://github.com/phpseven/yaf
> 使用原生php😀

膜拜肝帝，但是学习意义大于实际意义，有时间的话殿下弄个orm吧，可能还有点用，我一直苦于找不到满意的orm

**Comment by phpseven** [comment]
> > 忍不住，自己捣鼓了一下，
> > https://github.com/phpseven/yaf
> > 使用原生php😀
> 
> 膜拜肝帝，但是学习意义大于实际意义，有时间的话殿下弄个orm吧，可能还有点用，我一直苦于找不到满意的orm

有一套完整CRUD前后台，
不过要晚些才能公开出部分对大家有意义的代码了😀

**Comment by lly0414** [comment]
> 我有个在做兼容的分支,还在开发测试中,可以先试试 https://github.com/defender-11/yaf/tree/defender-php8.0
试了一下 大哥厉害的啊🚀

**Comment by lly0414** [comment]
> 我有个在做兼容的分支,还在开发测试中,可以先试试 https://github.com/defender-11/yaf/tree/defender-php8.0
试了一下 大哥厉害的啊🚀

**Comment by shagondu** [comment]
> > > 我有个在做兼容的分支,还在开发测试中,可以先试试 https://github.com/defender-11/yaf/tree/defender-php8.0
> > 
> > 
> > debian php8.0 编译报错
> 
> 请贴一下，报错信息


/tmp/yaf/responses/yaf_response_http.c:123:26: warning: passing argument 1 of ‘zend_spprintf’ from incompatible pointer type [-Wincompatible-pointer-types]
  ctr.line_len = spprintf(&(ctr.line), 0, "%s %s", "Location:", ZSTR_VAL(url));

现在 debian php8.0 下编译就剩这个报错了。

但是编译后的表现是，一些页面的路由还是有问题。

*1 recv() failed (104: Connection reset by peer) while reading response header from upstream

**Comment by renxiaotu** [comment]
> > > 忍不住，自己捣鼓了一下，
> > > https://github.com/phpseven/yaf
> > > 使用原生php😀
> > 
> > 
> > 膜拜肝帝，但是学习意义大于实际意义，有时间的话殿下弄个orm吧，可能还有点用，我一直苦于找不到满意的orm
> 
> 鸟哥的代码还是很清晰，对着c抄一抄就出来了，目前还不够完善。
> 
> orm的话，其实是有一套完整CRUD前后台，之前是在鸟哥的框架开发的，目前的php版本是是兼容这套代码的
> 不过要晚些才能公开出**部分对大家有意义**的代码了😀

我突然发现其实你写的这个php原生yaf也挺好用的，虽然我项目不用你的代码，我用ide把你的代码外部引入，就可以自动完成了，用了都说好

**Comment by defender-11** [comment]
> > > > 我有个在做兼容的分支,还在开发测试中,可以先试试 https://github.com/defender-11/yaf/tree/defender-php8.0
> > > 
> > > 
> > > debian php8.0 编译报错
> > 
> > 
> > 请贴一下，报错信息
> 
> /tmp/yaf/responses/yaf_response_http.c:123:26: warning: passing argument 1 of ‘zend_spprintf’ from incompatible pointer type [-Wincompatible-pointer-types]
> ctr.line_len = spprintf(&(ctr.line), 0, "%s %s", "Location:", ZSTR_VAL(url));
> 
> 现在 debian php8.0 下编译就剩这个报错了。
> 
> 但是编译后的表现是，一些页面的路由还是有问题。
> 
> *1 recv() failed (104: Connection reset by peer) while reading response header from upstream

感谢反馈！这条编译警告已经修复,请拉最新代码试试,如果业务代码还有异常的最好能提供复现代码。

**Comment by shagondu** [comment]
> > > > > 我有个在做兼容的分支,还在开发测试中,可以先试试 https://github.com/defender-11/yaf/tree/defender-php8.0
> > > > 
> > > > 
> > > > debian php8.0 编译报错
> > > 
> > > 
> > > 请贴一下，报错信息
> > 
> > 
> > /tmp/yaf/responses/yaf_response_http.c:123:26: warning: passing argument 1 of ‘zend_spprintf’ from incompatible pointer type [-Wincompatible-pointer-types]
> > ctr.line_len = spprintf(&(ctr.line), 0, "%s %s", "Location:", ZSTR_VAL(url));
> > 现在 debian php8.0 下编译就剩这个报错了。
> > 但是编译后的表现是，一些页面的路由还是有问题。
> > *1 recv() failed (104: Connection reset by peer) while reading response header from upstream
> 
> 感谢反馈！这条编译警告已经修复,请拉最新代码试试,如果业务代码还有异常的最好能提供复现代码。

最新的代码编译没有警告了，但是页面访问还是502

fpm log : [pool www] child 4174 exited on signal 11 (SIGSEGV)

 nginx log : readv() failed (104: Connection reset by peer) while reading upstream

浏览器报错： net::ERR_INCOMPLETE_CHUNKED_ENCODING

在路由执行阶段就报错了，没到执行代码阶段。

**Comment by defender-11** [comment]
> > > > > > 我有个在做兼容的分支,还在开发测试中,可以先试试 https://github.com/defender-11/yaf/tree/defender-php8.0
> > > > > 
> > > > > 
> > > > > debian php8.0 编译报错
> > > > 
> > > > 
> > > > 请贴一下，报错信息
> > > 
> > > 
> > > /tmp/yaf/responses/yaf_response_http.c:123:26: warning: passing argument 1 of ‘zend_spprintf’ from incompatible pointer type [-Wincompatible-pointer-types]
> > > ctr.line_len = spprintf(&(ctr.line), 0, "%s %s", "Location:", ZSTR_VAL(url));
> > > 现在 debian php8.0 下编译就剩这个报错了。
> > > 但是编译后的表现是，一些页面的路由还是有问题。
> > > *1 recv() failed (104: Connection reset by peer) while reading response header from upstream
> > 
> > 
> > 感谢反馈！这条编译警告已经修复,请拉最新代码试试,如果业务代码还有异常的最好能提供复现代码。
> 
> 最新的代码编译没有警告了，但是页面访问还是502
> 
> fpm log : [pool www] child 4174 exited on signal 11 (SIGSEGV)
> 
> nginx log : readv() failed (104: Connection reset by peer) while reading upstream
> 
> 浏览器报错： net::ERR_INCOMPLETE_CHUNKED_ENCODING
> 
> 在路由执行阶段就报错了，没到执行代码阶段。

有复现代码能提供吗？guchangsheng@hotmail.com

**Comment by phpseven** [comment]
> > > > 忍不住，自己捣鼓了一下，
> > > > https://github.com/phpseven/yaf
> > > > 使用原生php😀
> > > 
> > > 
> > > 膜拜肝帝，但是学习意义大于实际意义，有时间的话殿下弄个orm吧，可能还有点用，我一直苦于找不到满意的orm
> > 
> > 
> > 鸟哥的代码还是很清晰，对着c抄一抄就出来了，目前还不够完善。
> > orm的话，其实是有一套完整CRUD前后台，之前是在鸟哥的框架开发的，目前的php版本是是兼容这套代码的
> > 不过要晚些才能公开出**部分对大家有意义**的代码了😀
> 
> 我突然发现其实你写的这个php原生yaf也挺好用的，虽然我项目不用你的代码，我用ide把你的代码外部引入，就可以自动完成了，用了都说好

>_<这。。也可以了。。不过老兄最好用0.2版本的，后面版本已经新增了一些特性了。/

**Comment by laruence** [comment]
马上支持，在coding了

**Comment by laruence** [comment]
应该没啥大问题了，master分支现在支持了，感谢@defender-11 的PR，我再看看有没有一些积累的bug，过几天发新版
