### ISSUE TITLE
ini_set("yaf.use_spl_autoload",1) 不生效

### ISSUE THREAD

**Issue by mahaidongs** [laruence/yaf#524]
版本号：3.2.6-dev （最新版）
ini_set("yaf.use_spl_autoload",1) 设置后 还是会报错：  Yaf_Loader::autoload(): Failed opening script   
只有在php.ini中设置 yaf.use_spl_autoload 才能生效    

yaf版本2.0.8中就可以动态设置 ini_set("yaf.use_spl_autoload",1)      求高手告知下如何解决

**Comment by laruence** [comment]
你需要在yaf app运行之前设置, 在new yaf_application之前
