### ISSUE TITLE
请求输出的内容被添加到响应头里

### ISSUE THREAD

**Issue by lly0414** [laruence/yaf#525]
### 问题描述
```
在方法内输出任何内容浏览器页面都是空白的,后来输出一小段字符串发现输出的内容被添加到了响应头里..
nginx和php日志都没有报错,不知道是不是拉了最新代码的问题还是我nginx配置的问题,一直没找到原因😥
```
### 测试的代码
```php
class IndexController extends Yaf\Controller_Abstract
{
    public function indexAction()
    {
        header("Content-Type: application/json; charset=utf-8");
        echo 'massage';
    }
}
```
### 浏览器的响应
```
Connection: keep-alive
Date: Tue, 05 Jan 2021 07:44:30 GMT
massageContent-Type: application/json; charset=utf-8
Server: nginx/1.18.0 (Ubuntu)
Transfer-Encoding: chunked
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1; mode=block
```
>在这句响应里:
**massageContent-Type: application/json; charset=utf-8**, 
`massage`被添加到了前面
### nginx配置
```nginx
listen 80;

root /xxxx/xxxx/xxxxx/;

add_header X-Frame-Options "SAMEORIGIN";
add_header X-XSS-Protection "1; mode=block";
add_header X-Content-Type-Options "nosniff";

index index.html index.htm index.php;

charset utf-8;

location / {
    try_files $uri $uri/ /index.php?$query_string;
}

location = /favicon.ico { access_log off; log_not_found off; }
location = /robots.txt  { access_log off; log_not_found off; }

error_page 404 /index.php;

location ~ \.php$ {
    fastcgi_pass unix:/run/php/php8.0-fpm.sock;
    fastcgi_index index.php;
    fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
    include fastcgi_params;
}

location ~ /\.(?!well-known).* {
    deny all;
}
```
## 求大神解答!  感谢🍖

**Comment by laruence** [comment]
有点奇怪， 你试试不直接用header，用:
````php
$this->getResponse()->setHader(“type”,  "Content-Type: application/json; charset=utf-8");
````
呢？

**Comment by lly0414** [comment]
> 有点奇怪，你试试不直接用header，用：
> 
> ```
> $这- >的GetResponse（） - > setHader（“类型”，  “内容类型：应用/ JSON;字符集= UTF-8”）;
> ```
> 
> 呢？
```php
class IndexController extends Yaf\Controller_Abstract
{
    public function indexAction()
    {
        $this->getResponse()->setHader("type",  "Content-Type: application/json; charset=utf-8");
        $this->getResponse()->setBody("massage");
        $this->getResponse()->response();
    }
}
```
## 浏览器返回
```
HTTP/1.1 200 OK
Server: nginx/1.18.0 (Ubuntu)
Date: Tue, 05 Jan 2021 09:14:10 GMT
Content-Type: text/html; charset=UTF-8
Transfer-Encoding: chunked
Connection: keep-alive
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
Content-Encoding: gzip
```
没起作用, 一直返回200,整懵了....

**Comment by lly0414** [comment]
有可能是我自己的问题, 刚才试了下直接访问php文件, 貌似也没有输出,我自己再看看...

**Comment by lly0414** [comment]
> > 有点奇怪，你试试不直接用header，用：
> > ```
> > $这- >的GetResponse（） - > setHader（“类型”，  “内容类型：应用/ JSON;字符集= UTF-8”）;
> > ```
> > 
> > 
> > 呢？
> 
> ```
> class IndexController extends Yaf\Controller_Abstract
> {
>     public function indexAction()
>     {
>         $this->getResponse()->setHader("type",  "Content-Type: application/json; charset=utf-8");
>         $this->getResponse()->setBody("massage");
>         $this->getResponse()->response();
>     }
> }
> ```
> 
> ## 浏览器返回
> ```
> HTTP/1.1 200 OK
> Server: nginx/1.18.0 (Ubuntu)
> Date: Tue, 05 Jan 2021 09:14:10 GMT
> Content-Type: text/html; charset=UTF-8
> Transfer-Encoding: chunked
> Connection: keep-alive
> X-Frame-Options: SAMEORIGIN
> X-XSS-Protection: 1; mode=block
> X-Content-Type-Options: nosniff
> Content-Encoding: gzip
> ```
> 
> 没起作用, 一直返回200,整懵了....

好了 是我服务器的问题 - -
