### ISSUE TITLE
如何解决以Model结尾的本地类被强制在models目录下加载的问题

### ISSUE THREAD

**Issue by renxiaotu** [laruence/yaf#527]
本地类如果以Model结尾，Yaf会尝试从models目录加载，如果没有会直接报错，即使用registerLocalNamespace或registerNamespace指定了路径也无用。
是否有办法让Model结尾的类也能在library目录加载
我现在的方案是配置yaf.use_spl_autoload=On并用spl_autoload_register加载，但这并不是好的解决方案

**Comment by laruence** [comment]
这个还真没啥办法，除非你自己预先加载好。
