### ISSUE TITLE
请教一个关于Controller::init()的问题

### ISSUE THREAD

**Issue by infatu8** [laruence/yaf#532]
rest app 中，我在controller的init()中对客户端加密后发送过来的 raw data 以及签名进行验签和解密
当我验签不过时，需要给客户端response 一个包含相关message的json数据，
并且，不再需要执行后面的流程了，直接在init中进行response。
目前是用exit退出的，但这有一个问题，就是不能跟swoole一起使用了。

所以，问题是，如何在不exit的情况下，在init 进行response而后续的流程就不继续做了

**Comment by laruence** [comment]
throw exception，顶层catch
