### ISSUE TITLE
application.bootstrap设置无效

### ISSUE THREAD

**Issue by ppanphper** [laruence/yaf#536]
yaf version: 3.3.1
php version: 7.0.33

在application.ini中设置application.bootstrap = APP_PATH "/application/OtherBootstrap.php" 不生效，
提示"Warning: Yaf_Application::bootstrap(): Couldn't find bootstrap file �A��-"

是这个配置去掉了吗？

**Comment by ppanphper** [comment]
$app = new \Yaf_Application(APP_PATH . "/conf/application.api.ini", PHP_ENV);
$app->bootstrap()->run();

**Comment by laruence** [comment]
应该不是无效，只是提示错误信息部分错了，你再看下。。。
