### ISSUE TITLE
基于yaf3.3.1引入composer autoload后报 17020 segmentation fault 错误

### ISSUE THREAD

**Issue by ghxter** [laruence/yaf#537]
yaf version: 3.3.1
php version: 7.3.27

基于tools/cg  生成默认代码，然后composer install 后，在Bootstrap.php引入报错。   

    public function _initAutoload(Yaf\Dispatcher $dispatcher)
    {
        \Yaf\Loader::import(APPLICATION_PATH . '/vendor/autoload.php');

    }

测试在index.php引入同样报错。 

`require_once APPLICATION_PATH . '/vendor/autoload.php';`

composer.json 参考：

`
  "require": {
    "paquettg/php-html-parser": "^2.2",
    "guzzlehttp/guzzle": "^7.0"
  }
`

**Comment by laruence** [comment]
有backtrace看看么

**Comment by ghxter** [comment]
> 有backtrace看看么
`
array(5) {
  [0]=>
  array(6) {
    ["file"]=>
    string(52) "/Users/php/yaf_cli/vendor/autoload.php"
    ["line"]=>
    int(7)
    ["function"]=>
    string(9) "getLoader"
    ["class"]=>
    string(54) "ComposerAutoloaderInit3721382387729a065b581390a0ec0b42"
    ["type"]=>
    string(2) "::"
    ["args"]=>
    array(0) {
    }
  }
  [1]=>
  array(1) {
    ["function"]=>
    string(7) "unknown"
  }
  [2]=>
  array(6) {
    ["file"]=>
    string(58) "/Users/php/yaf_cli/application/Bootstrap.php"
    ["line"]=>
    int(44)
    ["function"]=>
    string(6) "import"
    ["class"]=>
    string(10) "Yaf\Loader"
    ["type"]=>
    string(2) "::"
    ["args"]=>
    array(1) {
      [0]=>
      string(52) "/Users/php/yaf_cli/vendor/autoload.php"
    }
  }
  [3]=>
  array(5) {
    ["function"]=>
    string(13) "_initAutoload"
    ["class"]=>
    string(9) "Bootstrap"
    ["object"]=>
    object(Bootstrap)#8 (0) {
    }
    ["type"]=>
    string(2) "->"
    ["args"]=>
    array(1) {
      [0]=>
      object(Yaf\Dispatcher)#4 (8) {
        ["auto_render:protected"]=>
        bool(true)
        ["instant_flush:protected"]=>
        bool(false)
        ["return_response:protected"]=>
        bool(false)
        ["request:protected"]=>
        object(Yaf\Request\Http)#7 (10) {
          ["method"]=>
          string(3) "CLI"
          ["module"]=>
          NULL
          ["controller"]=>
          NULL
          ["action"]=>
          NULL
          ["uri:protected"]=>
          string(0) ""
          ["base_uri:protected"]=>
          NULL
          ["dispatched:protected"]=>
          bool(false)
          ["routed:protected"]=>
          bool(false)
          ["language:protected"]=>
          string(0) ""
          ["params:protected"]=>
          array(0) {
          }
        }
        ["response:protected"]=>
        NULL
        ["router:protected"]=>
        object(Yaf\Router)#5 (2) {
          ["routes:protected"]=>
          array(1) {
            ["_default"]=>
            object(Yaf\Route_Static)#6 (0) {
            }
          }
          ["current:protected"]=>
          NULL
        }
        ["view:protected"]=>
        NULL
        ["plugins:protected"]=>
        array(1) {
          [0]=>
          object(SamplePlugin)#10 (0) {
          }
        }
      }
    }
  }
  [4]=>
  array(7) {
    ["file"]=>
    string(40) "/Users/php/yaf_cli/cli.php"
    ["line"]=>
    int(36)
    ["function"]=>
    string(9) "bootstrap"
    ["class"]=>
    string(15) "Yaf\Application"
    ["object"]=>
    object(Yaf\Application)#1 (13) {
      ["directory"]=>
      string(44) "/Users/php/yaf_cli/application"
      ["library"]=>
      NULL
      ["bootstrap"]=>
      NULL
      ["ext"]=>
      string(3) "php"
      ["view_ext"]=>
      string(5) "phtml"
      ["environ:protected"]=>
      string(7) "develop"
      ["running:protected"]=>
      bool(false)
      ["err_msg:protected"]=>
      NULL
      ["err_no:protected"]=>
      int(0)
      ["config:protected"]=>
      object(Yaf\Config\Ini)#2 (3) {
        ["readonly:protected"]=>
        bool(true)
        ["config:protected"]=>
        array(2) {
          ["application"]=>
          array(2) {
            ["directory"]=>
            string(44) "/Users/php/yaf_cli/application"
            ["dispatcher"]=>
            array(2) {
              ["catchException"]=>
              string(1) "0"
              ["throwException"]=>
              string(1) "0"
            }
          }
          ["fund"]=>
          array(9) {
            [260108]=>
            string(6) "260108"
          }
        }
        ["filename:protected"]=>
        string(53) "/Users/php/yaf_cli/conf/application.ini"
      }
      ["dispatcher:protected"]=>
      object(Yaf\Dispatcher)#4 (8) {
        ["auto_render:protected"]=>
        bool(true)
        ["instant_flush:protected"]=>
        bool(false)
        ["return_response:protected"]=>
        bool(false)
        ["request:protected"]=>
        object(Yaf\Request\Http)#7 (10) {
          ["method"]=>
          string(3) "CLI"
          ["module"]=>
          NULL
          ["controller"]=>
          NULL
          ["action"]=>
          NULL
          ["uri:protected"]=>
          string(0) ""
          ["base_uri:protected"]=>
          NULL
          ["dispatched:protected"]=>
          bool(false)
          ["routed:protected"]=>
          bool(false)
          ["language:protected"]=>
          string(0) ""
          ["params:protected"]=>
          array(0) {
          }
        }
        ["response:protected"]=>
        NULL
        ["router:protected"]=>
        object(Yaf\Router)#5 (2) {
          ["routes:protected"]=>
          array(1) {
            ["_default"]=>
            object(Yaf\Route_Static)#6 (0) {
            }
          }
          ["current:protected"]=>
          NULL
        }
        ["view:protected"]=>
        NULL
        ["plugins:protected"]=>
        array(1) {
          [0]=>
          object(SamplePlugin)#10 (0) {
          }
        }
      }
      ["modules:protected"]=>
      array(1) {
        [0]=>
        string(5) "Index"
      }
      ["default_route:protected"]=>
      NULL
    }
    ["type"]=>
    string(2) "->"
    ["args"]=>
    array(0) {
    }
  }
}
`

多谢 @laruence 大佬~

**Comment by laruence** [comment]
Thank you for this bug report. To properly diagnose the problem, we
need a backtrace to see what is happening behind the scenes. To
find out how to generate a backtrace, please read
http://bugs.php.net/bugs-generating-backtrace.php for *NIX and
http://bugs.php.net/bugs-generating-backtrace-win32.php for Win32

**Comment by laruence** [comment]
@ghxter 你按照我上面贴的link，看看segfault以后的backtrace是啥，不是php应用的backtrace哈

**Comment by ghxter** [comment]
> 的

非常非常感谢大佬， 我回滚到yaf-3.0.6之后正常使用了， 刚才重新升级yaf-3.3.1也正常了，不能重现了。

Excess command line arguments ignored. (finan/run ...)
GNU gdb (GDB) 10.1
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-apple-darwin20.2.0".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
pyaf: No such file or directory.
"/php/yaf_cli/cli.php" is not a core dump: file format not recognized
(gdb) bt
No stack.
(gdb)

如果再遇到了， 我用这个方法，把信息提上来。

**Comment by laruence** [comment]
嗯，那有可能是因为之前的一个内存越界写导致的副作用，你可以升级到3.3.2
