### ISSUE TITLE
addRoute 导致502

### ISSUE THREAD

**Issue by Sgenmi** [laruence/yaf#538]
开发环境：
OS：MAC  10.13.6
PHP：集成环境 MAMP ，php7.4.2
Yaf:3.3.1

bug：当在Bootstrap加入自定义路由，则影响部份控制器无法访问

test: $router->addRoute加入自定义路由， 则/role,/main 都不可以访问，直接502；但/tests 可以访问，去掉addRoute 则都可以访问

demo: [https://github.com/Sgenmi/yaf-debug](url)

注：1.  V3.0.9 之后大部份版本存在这个问题，现在一直停在3.0.9
       2.   Centos环境下运行正常，无此bug,  此bug暂只发现在mac下

**Comment by laruence** [comment]
我下载了你的demo，用的是php8，通过php8 -S localhost -t yaf-debug/public/  启动服务

然后访问localhost/common 得到正确的结果，index controller data action
访问localhost/role 得到role controller，index action

无法复现 （yaf-3.3.2-dev, mac os bigsur 11.2.1)

**Comment by Sgenmi** [comment]
![image](https://user-images.githubusercontent.com/3337501/109914173-62666000-7cea-11eb-8c58-68d3c099ecaa.png)
yaf

yaf support => enabled
Version => 3.3.1
Supports => http://pecl.php.net/package/yaf

Directive => Local Value => Master Value
yaf.library => no value => no value
yaf.environ => product => product
yaf.forward_limit => 5 => 5
yaf.use_namespace => 1 => 1
yaf.action_prefer => 0 => 0
yaf.lowcase_path => 0 => 0
yaf.use_spl_autoload => 0 => 0
yaf.name_suffix => 1 => 1
yaf.name_separator => no value => no value



$ php -v
PHP 7.4.2 (cli) (built: Feb 17 2020 12:56:02) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies

**Comment by laruence** [comment]
能看到backtracke么，coredump了应该是

**Comment by laruence** [comment]
这样沟通太费劲，你有我微信么？

**Comment by Sgenmi** [comment]
> 这样沟通太费劲，你有我微信么？

 我还没有大佬的微信，我的 13989484889

**Comment by Sgenmi** [comment]
我发现一个奇怪的事，我在 _initRoutes方法中，增加一个 file_put_contents 操作，竟然正常访问了。去掉file_put_contents就不可以了。

**Comment by Sgenmi** [comment]
![image](https://user-images.githubusercontent.com/3337501/109924969-0efd0d80-7cfc-11eb-8143-a18dd84926cf.png)
Core dump

**Comment by laruence** [comment]
你的php是怎么安装的？自己编译的么？

**Comment by laruence** [comment]
我现在怀疑是gcc编译7.4的问题，如果编译php的时候--enable-debug，我就不能重现了。

（主要是coredump看起来太奇怪了，lldb跟踪半天，找不到头绪，所以才想到是这个

**Comment by Sgenmi** [comment]
> 你的php是怎么安装的？自己编译的么？

我直接用MAMP 集成环境。他是编译好的。 这个集成环境，有多个PHP版本，其他版本也是一样的。 自己在centos上 编译的php,确实是没有问题。   这真有可能这个PHP编译本身的问题。

**Comment by Sgenmi** [comment]
初步解决办法，开发环境 我在自定义路由下，增加一个file_put_contents() 就可以正常，线上环境跳过此方法。

**Comment by Sgenmi** [comment]
我把 _initRoutes 放在最顶部，竟然 通过了。 神奇。。  算是 解决了。  3Q

**Comment by laruence** [comment]
哈哈哈哈，想了一晚上，灵光一闪，修复了，是一个越界写导致的，我回头发个新版。

**Comment by laruence** [comment]
发了新版本3.3.2，你可以试试了，应该没问题了

**Comment by Sgenmi** [comment]
> 发了新版本3.3.2，你可以试试了，应该没问题了

测试通过
