### ISSUE TITLE
为什么php -i | grep 'yaf' 显示有  yaf，但是 phpinfo 里面却没有？？

### ISSUE THREAD

**Issue by wgj6112345** [laruence/yaf#541]
![Screenshot from 2021-03-13 17-49-27](https://user-images.githubusercontent.com/24644442/111026299-86315080-8424-11eb-98ca-de55232d1cd6.png)
![Screenshot from 2021-03-13 17-50-27](https://user-images.githubusercontent.com/24644442/111026325-a4974c00-8424-11eb-8b6e-1a4215add541.png)

**Comment by wgj6112345** [comment]
网上实在是查不到资料，有说 use_namespace 的，但是好像都不行，才接触php几天，完全不知道怎么办了

**Comment by hkui** [comment]
> 网上实在是查不到资料，有说 use_namespace 的，但是好像都不行，才接触php几天，完全不知道怎么办了

添加扩展后，你web容器重启了没？
fastcgi用的ini文件和php --ini 里显示的是否一致

**Comment by wgj6112345** [comment]
> > 网上实在是查不到资料，有说 use_namespace 的，但是好像都不行，才接触php几天，完全不知道怎么办了
> 
> 添加扩展后，你web容器重启了没？
> fastcgi用的ini文件和php --ini 里显示的是否一致

我是 php7.1 + nginx，没用容器，php -i 显示的是  php/7.1/cli/php.ini 这个配置文件。
平常情况下 php 文件是正常打开的，但是这个 yaf 框架运行不了。

下面这个是我的 nginx 中 /etc/nginx/sites-enabled下面的配置文件:
![Screenshot from 2021-03-13 20-43-48](https://user-images.githubusercontent.com/24644442/111030384-dc11f280-843c-11eb-875e-d59e8750925d.png)

**Comment by hkui** [comment]
> > > 网上实在是查不到资料，有说 use_namespace 的，但是好像都不行，才接触php几天，完全不知道怎么办了
> > 
> > 
> > 添加扩展后，你web容器重启了没？
> > fastcgi用的ini文件和php --ini 里显示的是否一致
> 
> 我是 php7.1 + nginx，没用容器，php -i 显示的是 php/7.1/cli/php.ini 这个配置文件。
> 平常情况下 php 文件是正常打开的，但是这个 yaf 框架运行不了。
> 
> 下面这个是我的 nginx 中 /etc/nginx/sites-enabled下面的配置文件:
> ![Screenshot from 2021-03-13 20-43-48](https://user-images.githubusercontent.com/24644442/111030384-dc11f280-843c-11eb-875e-d59e8750925d.png)

你的php-fpm重启了没？php --ini 查看cli使用的php.ini 
 看下和你phpinfo或者php -i里看到php.ini一致吗
如果不一致，把fpm关闭，然后启动时 添加 -c 指定php.ini路径

**Comment by laruence** [comment]
嗯，楼上说的对。
