### ISSUE TITLE
Yaf_Loader::autoload()  和 class_exists 有冲突 

### ISSUE THREAD

**Issue by 80boys** [laruence/yaf#547]
使用 composer 引入第三方类库
第三方类库里 使用了 class_exists 函数 判断 类 是否存在 
但是第三方类库没有在 class_exists 函数里设置第二个参数为false, 
导致 class_exists 函数 触发了  __autoload  
但是 不知道为何 __autoload 之后又 触发了 Yaf_Loader::autoload()
而 Yaf_Loader::autoload() 直接报错 application/library/下面 没有 类文件

由于第三方库 直接修改 不太符合规范  望今后版本修复此问题

**Comment by laruence** [comment]
你可以设置yaf.use_spl_autoload=1，这样yaf起码就不会报错了

**Comment by 80boys** [comment]
谢谢 已解决
