### ISSUE TITLE
view接口实现时getScriptPath方法需要传递参数

### ISSUE THREAD

**Issue by listyu** [laruence/yaf#555]
在文档中这个方法并不需要传递参数, 但实际使用时需要传递一个参数.
版本3.3.3 直接在PECL上下载的DLL

**Comment by macintoshplus** [comment]
Hi,

I have initiated a CI to build some PHP extensions for Windows.

This extension is now available here: https://phpext.phptools.online/extension/system/yaf-379

I'm available for more information.
