### ISSUE TITLE
yaf3.3.3 当控制器里一个action不存在时无法捕获错误

### ISSUE THREAD

**Issue by zy2701** [laruence/yaf#561]
环境：win10 + apache + php 7.4.22 + yaf 3.3.3 
当控制器里一个action不存在时无法捕获错误，直接报500 Internal Server Error
之前的其它版本我记得没有这个问题

**Comment by laruence** [comment]
你有测试代码么，我自己测试应该没问题。
只不过就是你要catch Error，不能catch Exception

**Comment by zy2701** [comment]
我是这么操作的：




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "laruence/yaf"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月16日(星期二) 中午12:03
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [laruence/yaf] yaf3.3.3 当控制器里一个action不存在时无法捕获错误 (Issue #561)





 
你有测试代码么，我自己测试应该没问题。
 只不过就是你要catch Error，不能catch Exception
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by zy2701** [comment]
我是这么操作的：
<?php
class&nbsp;ErrorController&nbsp;extends&nbsp;Yaf_Controller_Abstract&nbsp;{
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;public&nbsp;function&nbsp;error($exception)&nbsp;{
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;switch&nbsp;($exception-&gt;getCode())&nbsp;{
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;case&nbsp;YAF_ERR_NOTFOUND_MODULE:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;case&nbsp;YAF_ERR_NOTFOUND_CONTROLLER:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;case&nbsp;YAF_ERR_NOTFOUND_ACTION:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;case&nbsp;YAF_ERR_NOTFOUND_VIEW:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;echo&nbsp;404,&nbsp;":",&nbsp;$exception-&gt;getMessage();
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;break;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;default&nbsp;:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$message&nbsp;=&nbsp;$exception-&gt;getMessage();
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;echo&nbsp;0,&nbsp;":",&nbsp;$exception-&gt;getMessage();
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;break;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}&nbsp;
}
?&gt;


还有其它方法么？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "laruence/yaf"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月16日(星期二) 中午12:03
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [laruence/yaf] yaf3.3.3 当控制器里一个action不存在时无法捕获错误 (Issue #561)





 
你有测试代码么，我自己测试应该没问题。
 只不过就是你要catch Error，不能catch Exception
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by zy2701** [comment]
php7.4+yaf 3.3的环境下



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Xinchen ***@***.***&gt;; 
发送时间: 2021年11月16日(星期二) 中午12:03
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [laruence/yaf] yaf3.3.3 当控制器里一个action不存在时无法捕获错误 (Issue #561)





 
你有测试代码么，我自己测试应该没问题。
 只不过就是你要catch Error，不能catch Exception
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by zy2701** [comment]
大佬我又来挖坟了，我现在终于测试出来了，这种情况存在于所有的yaf版本。
具体的情况是：
控制器使用了__get魔术方法后，当action不存在的时候，php进程会被直接终止.。
windows+apache下显示：500 Internal Server Error
同时apache会记录一条错误日志：[core:error] [pid 5664:tid 1540] [client 127.0.0.1:56787] End of script output before headers: index.php

linux+nginx下显示：502 Bad Gateway
同时nginx会记录一条错误日志：recv() failed (104: Connection reset by peer) while reading response header from upstream

相同的情况，php都没有错误日志被记录。
希望大佬下次再更新的时候，能把这个bug给解决一下。
