### ISSUE TITLE
yaf 3.3.3及以后版本，xdebug发现Bootstrap.php没有加载类内的_init方法

### ISSUE THREAD

**Issue by shaoshiqiang** [laruence/yaf#566]
php版本：7.2.34

yaf版本：3.3.3 or 3.3.4

php.ini配置：
extension="yaf.so"
yaf.environ='dev'
yaf.use_namespace=1

**Comment by shaoshiqiang** [comment]
3.0.7版本下，可以加载Bootstrap.php的_init方法

**Comment by shaoshiqiang** [comment]
已经结果，把_init方法变成_init***  即可加载。

是不是新版本的不支持_init了？

**Comment by yunx-lee** [comment]
> 已经处理好了，把_init方法变成_init*** 即可加载。
> 
> 是不是新版本3.3.3以后不支持_init了？

类方法名现在不能仅仅是 “_init”了，方法名字后面随便写个字母就好了

**Comment by laruence** [comment]
这个是上次重构的副作用，已经修复，谢谢
