### ISSUE TITLE
PHP8.2下 安装yaf-3.3.5报错

### ISSUE THREAD

**Issue by letwang** [laruence/yaf#580]
`libtool: compile:  cc -I. -I/tmp/pear/temp/yaf -I/tmp/pear/temp/pear-build-defaultuser9Kt7Qo/yaf-3.3.5/include -I/tmp/pear/temp/pear-build-defaultuser9Kt7Qo/yaf-3.3.5/main -I/tmp/pear/temp/yaf -I/usr/include/php/20220829 -I/usr/include/php/20220829/main -I/usr/include/php/20220829/TSRM -I/usr/include/php/20220829/Zend -I/usr/include/php/20220829/ext -I/usr/include/php/20220829/ext/date/lib -DHAVE_CONFIG_H -g -O2 -D_GNU_SOURCE -DZEND_COMPILE_DL_EXT=1 -c /tmp/pear/temp/yaf/responses/yaf_response_cli.c -MMD -MF responses/yaf_response_cli.dep -MT responses/yaf_response_cli.lo  -fPIC -DPIC -o responses/.libs/yaf_response_cli.o
/bin/bash /tmp/pear/temp/pear-build-defaultuser9Kt7Qo/yaf-3.3.5/libtool --mode=compile cc -I. -I/tmp/pear/temp/yaf -I/tmp/pear/temp/pear-build-defaultuser9Kt7Qo/yaf-3.3.5/include -I/tmp/pear/temp/pear-build-defaultuser9Kt7Qo/yaf-3.3.5/main -I/tmp/pear/temp/yaf -I/usr/include/php/20220829 -I/usr/include/php/20220829/main -I/usr/include/php/20220829/TSRM -I/usr/include/php/20220829/Zend -I/usr/include/php/20220829/ext -I/usr/include/php/20220829/ext/date/lib  -DHAVE_CONFIG_H  -g -O2 -D_GNU_SOURCE    -DZEND_COMPILE_DL_EXT=1 -c /tmp/pear/temp/yaf/yaf_view.c -o yaf_view.lo  -MMD -MF yaf_view.dep -MT yaf_view.lo
libtool: compile:  cc -I. -I/tmp/pear/temp/yaf -I/tmp/pear/temp/pear-build-defaultuser9Kt7Qo/yaf-3.3.5/include -I/tmp/pear/temp/pear-build-defaultuser9Kt7Qo/yaf-3.3.5/main -I/tmp/pear/temp/yaf -I/usr/include/php/20220829 -I/usr/include/php/20220829/main -I/usr/include/php/20220829/TSRM -I/usr/include/php/20220829/Zend -I/usr/include/php/20220829/ext -I/usr/include/php/20220829/ext/date/lib -DHAVE_CONFIG_H -g -O2 -D_GNU_SOURCE -DZEND_COMPILE_DL_EXT=1 -c /tmp/pear/temp/yaf/yaf_view.c -MMD -MF yaf_view.dep -MT yaf_view.lo  -fPIC -DPIC -o .libs/yaf_view.o
/bin/bash /tmp/pear/temp/pear-build-defaultuser9Kt7Qo/yaf-3.3.5/libtool --mode=compile cc -I. -I/tmp/pear/temp/yaf -I/tmp/pear/temp/pear-build-defaultuser9Kt7Qo/yaf-3.3.5/include -I/tmp/pear/temp/pear-build-defaultuser9Kt7Qo/yaf-3.3.5/main -I/tmp/pear/temp/yaf -I/usr/include/php/20220829 -I/usr/include/php/20220829/main -I/usr/include/php/20220829/TSRM -I/usr/include/php/20220829/Zend -I/usr/include/php/20220829/ext -I/usr/include/php/20220829/ext/date/lib  -DHAVE_CONFIG_H  -g -O2 -D_GNU_SOURCE    -DZEND_COMPILE_DL_EXT=1 -c /tmp/pear/temp/yaf/views/yaf_view_interface.c -o views/yaf_view_interface.lo  -MMD -MF views/yaf_view_interface.dep -MT views/yaf_view_interface.lo
libtool: compile:  cc -I. -I/tmp/pear/temp/yaf -I/tmp/pear/temp/pear-build-defaultuser9Kt7Qo/yaf-3.3.5/include -I/tmp/pear/temp/pear-build-defaultuser9Kt7Qo/yaf-3.3.5/main -I/tmp/pear/temp/yaf -I/usr/include/php/20220829 -I/usr/include/php/20220829/main -I/usr/include/php/20220829/TSRM -I/usr/include/php/20220829/Zend -I/usr/include/php/20220829/ext -I/usr/include/php/20220829/ext/date/lib -DHAVE_CONFIG_H -g -O2 -D_GNU_SOURCE -DZEND_COMPILE_DL_EXT=1 -c /tmp/pear/temp/yaf/views/yaf_view_interface.c -MMD -MF views/yaf_view_interface.dep -MT views/yaf_view_interface.lo  -fPIC -DPIC -o views/.libs/yaf_view_interface.o
/bin/bash /tmp/pear/temp/pear-build-defaultuser9Kt7Qo/yaf-3.3.5/libtool --mode=compile cc -I. -I/tmp/pear/temp/yaf -I/tmp/pear/temp/pear-build-defaultuser9Kt7Qo/yaf-3.3.5/include -I/tmp/pear/temp/pear-build-defaultuser9Kt7Qo/yaf-3.3.5/main -I/tmp/pear/temp/yaf -I/usr/include/php/20220829 -I/usr/include/php/20220829/main -I/usr/include/php/20220829/TSRM -I/usr/include/php/20220829/Zend -I/usr/include/php/20220829/ext -I/usr/include/php/20220829/ext/date/lib  -DHAVE_CONFIG_H  -g -O2 -D_GNU_SOURCE    -DZEND_COMPILE_DL_EXT=1 -c /tmp/pear/temp/yaf/views/yaf_view_simple.c -o views/yaf_view_simple.lo  -MMD -MF views/yaf_view_simple.dep -MT views/yaf_view_simple.lo
libtool: compile:  cc -I. -I/tmp/pear/temp/yaf -I/tmp/pear/temp/pear-build-defaultuser9Kt7Qo/yaf-3.3.5/include -I/tmp/pear/temp/pear-build-defaultuser9Kt7Qo/yaf-3.3.5/main -I/tmp/pear/temp/yaf -I/usr/include/php/20220829 -I/usr/include/php/20220829/main -I/usr/include/php/20220829/TSRM -I/usr/include/php/20220829/Zend -I/usr/include/php/20220829/ext -I/usr/include/php/20220829/ext/date/lib -DHAVE_CONFIG_H -g -O2 -D_GNU_SOURCE -DZEND_COMPILE_DL_EXT=1 -c /tmp/pear/temp/yaf/views/yaf_view_simple.c -MMD -MF views/yaf_view_simple.dep -MT views/yaf_view_simple.lo  -fPIC -DPIC -o views/.libs/yaf_view_simple.o
/tmp/pear/temp/yaf/views/yaf_view_simple.c: In function 'yaf_view_simple_eval':
/tmp/pear/temp/yaf/views/yaf_view_simple.c:392:20: error: too few arguments to function 'zend_compile_string'
  392 |         op_array = zend_compile_string(Z_STR(phtml), eval_desc);
      |                    ^~~~~~~~~~~~~~~~~~~
make: *** [Makefile:257: views/yaf_view_simple.lo] Error 1
ERROR: `make' failed
`

**Comment by smashdog** [comment]
修改./views/yaf_view_simple.c:394:20
 op_array = zend_compile_string(Z_STR(phtml), eval_desc);
改为
 op_array = zend_compile_string;

**Comment by letwang** [comment]
> 

需要作者重新发包哦

**Comment by smashdog** [comment]
> > 
> 
> 需要作者重新发包哦

https://github.com/laruence/yaf/pull/579/files
这个才是正确的做法，我那个有问题

**Comment by smashdog** [comment]
> > 
> 
> 需要作者重新发包哦

自己下载源文件，修改对应的文件内容，再编译就行了

**Comment by keilestone** [comment]
还是希望鸟哥能重新发版，docker部署的，pecl直接安装比较方便

**Comment by letwang** [comment]
> 

是的
