### ISSUE TITLE
Yaf_Config_Ini 造成 Too many open files 问题

### ISSUE THREAD

**Issue by waming** [laruence/yaf#581]
在swoole使用yaf框架, 执行以下命令
`lsof -p 25481 > openfiles.log `
openfiles.log文件中 都是
`271768 php     25481 root *686r      REG  253,1      164   4459829 /var/www/config/cache.ini`
`271769 php     25481 root *687r      REG  253,1      164   4459829 /var/www/config/cache.ini`
`271770 php     25481 root *688r      REG  253,1      164   4459829 /var/www/config/cache.ini`

会造成 Too many open files  这种错误。

**Comment by yunx-lee** [comment]
yaf 跟 swoole 并不完全能共用，这其中有很多地方容易踩坑，一不小心就万劫不复，我建议不要在生产环境中尝试 yaf + swoole 的方案

**Comment by waming** [comment]
> yaf 跟 swoole 并不完全能共用，这其中有很多地方容易踩坑，一不小心就万劫不复，我建议不要在生产环境中尝试 yaf + swoole 的方案

这个问题很好解决，就是把获取的config保存在一个静态变量里。
其实生产环境也没什么坑的，现在稳定的很。

**Comment by waming** [comment]
我就想知道，是不是文件打开后，句柄没关的原因。

**Comment by yunx-lee** [comment]
> > yaf 跟 swoole 并不完全能共用，这其中有很多地方容易踩坑，一不小心就万劫不复，我建议不要在生产环境中尝试 yaf + swoole 的方案
> 
> 这个问题很好解决，就是把获取的config保存在一个静态变量里。 其实生产环境也没什么坑的，现在稳定的很。 我就想知道，是不是文件打开后，句柄没关的原因。要去看看源码了。

能看看你怎么把 yaf 跟 swoole 结合吗，来一个demo看看
yaf 的 ini config 是只读的，所以放到一个全局变量里就行，可以放到 registry 注册表里

另外，我还是建议只在 fpm 下使用 yaf
因为运行中有很多单例的实例，如 application dispatcher, 然后 dispatcher::setRequest dispatcher::getRequest 这样的getter setter 也有一些坑，前两年我用 golang 参考 yaf 的流程图写了一个框架，这就跟swoole常驻内存有点类似啦，所以我对这些问题是深有感触
