### ISSUE TITLE
fpm进程中存在多个application.ini文件句柄

### ISSUE THREAD

**Issue by dongchuant** [laruence/yaf#585]
application.ini 路径相同，文件句柄一直没有释放，请教下是否正常？入口文件代码如下：

`<?php
define('APP_PATH', realpath(dirname(__FILE__).'/../'));
$app = new Yaf_Application(APP_PATH."/conf/application.ini");
$app->bootstrap();
$app->run();`

![image](https://github.com/laruence/yaf/assets/5419747/292506e3-d89a-4eba-8946-75785e38f6be)

**Comment by scott-pb** [comment]
![image](https://github.com/laruence/yaf/assets/33451243/275d0ae1-4fd9-4bbe-ab63-6cfadaffbe3d)

zend_stream_init_fp(&fh, VCWD_FOPEN(ini_file, "r"), ini_file);

#define VCWD_FOPEN(path, mode)  fopen(path, mode)

ZEND_API void zend_stream_init_fp(zend_file_handle *handle, FILE *fp, const char *filename) {
	memset(handle, 0, sizeof(zend_file_handle));
	handle->type = ZEND_HANDLE_FP;
	handle->handle.fp = fp;
	handle->filename = filename ? zend_string_init(filename, strlen(filename), 0) : NULL;
}

yaf_config_ini_init function has not fclose(handle->handle.fp)

**Comment by fnu** [comment]
https://github.com/laruence/yaf/pull/587

这里有修复

**Comment by laruence** [comment]
感谢@fnu, 应该被修复了，原因是从PHP8.1开始，ini_parser不再主动释放文件句柄了
