### ISSUE TITLE
PHP8.3 install yaf-3.3.5、yaf-3.3.4 extenstion error：make: *** [Makefile:209: yaf.lo] Error 1

### ISSUE THREAD

**Issue by Frank520520** [laruence/yaf#588]
# make

/www/pkg/php_ext/yaf-3.3.5/yaf.c:253:9: error: expected ‘;’ before ‘int’
  253 | ZEND_HOT int yaf_call_user_method(zend_object *obj, zend_function* fbc, int num_arg, zval *args, zval *ret) /* {{{ */ {
      |         ^~~~
      |         ;
/www/pkg/php_ext/yaf-3.3.5/yaf.c:305:9: error: expected ‘;’ before ‘int’
  305 | ZEND_HOT int yaf_call_user_method_with_0_arguments(zend_object *obj, zend_function* fbc, zval *ret) /* {{{ */ {
      |         ^~~~
      |         ;
/www/pkg/php_ext/yaf-3.3.5/yaf.c:329:9: error: expected ‘;’ before ‘int’
  329 | ZEND_HOT int yaf_call_user_method_with_1_arguments(zend_object *obj, zend_function* fbc, zval *arg, zval *ret) /* {{{ */ {
      |         ^~~~
      |         ;
/www/pkg/php_ext/yaf-3.3.5/yaf.c:355:9: error: expected ‘;’ before ‘int’
  355 | ZEND_HOT int yaf_call_user_method_with_2_arguments(zend_object *obj, zend_function* fbc, zval *arg1, zval *arg2, zval *ret) /* {{{ */ {
      |         ^~~~
      |         ;
/www/pkg/php_ext/yaf-3.3.5/yaf.c:382:1: error: unknown type name ‘ZEND_HOT’; did you mean ‘ZEND_POW’?
  382 | ZEND_HOT zend_string *yaf_build_camel_name(const char *str, size_t len) /* {{{ */ {
      | ^~~~~~~~
      | ZEND_POW
/www/pkg/php_ext/yaf-3.3.5/yaf.c:382:22: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘*’ token
  382 | ZEND_HOT zend_string *yaf_build_camel_name(const char *str, size_t len) /* {{{ */ {
      |                      ^
/www/pkg/php_ext/yaf-3.3.5/yaf.c:442:1: error: unknown type name ‘ZEND_HOT’; did you mean ‘ZEND_POW’?
  442 | ZEND_HOT zend_string *yaf_build_lower_name(const char *str, size_t len) /* {{{ */ {
      | ^~~~~~~~
      | ZEND_POW
/www/pkg/php_ext/yaf-3.3.5/yaf.c:442:22: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘*’ token
  442 | ZEND_HOT zend_string *yaf_build_lower_name(const char *str, size_t len) /* {{{ */ {
      |                      ^
/www/pkg/php_ext/yaf-3.3.5/yaf.c:456:1: error: unknown type name ‘ZEND_HOT’; did you mean ‘ZEND_POW’?
  456 | ZEND_HOT zend_string *yaf_canonical_name(int type, zend_string *name) /* {{{ */ {
      | ^~~~~~~~
      | ZEND_POW
/www/pkg/php_ext/yaf-3.3.5/yaf.c:456:22: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘*’ token
  456 | ZEND_HOT zend_string *yaf_canonical_name(int type, zend_string *name) /* {{{ */ {
      |                      ^
/www/pkg/php_ext/yaf-3.3.5/yaf.c:480:9: error: expected ‘;’ before ‘void’
  480 | ZEND_HOT void yaf_replace_chr(char *name, uint32_t len, zend_uchar f, zend_uchar t) /* {{{ */ {
      |         ^~~~~
      |         ;
make: *** [Makefile:209: yaf.lo] Error 1

**Comment by Frank520520** [comment]
├── php_yaf.h
├── requests
│   └── yaf_request_simple.c
├── tests
│   ├── 031.phpt
│   └── issue231.phpt
├── views
│   └── yaf_view_simple.c
└── yaf_application.c

Just replace it and recompile it

**Comment by ryandesign** [comment]
A fix for this was already submitted in #579.
