### ISSUE TITLE
设置默认module后出现bug

### ISSUE THREAD

**Issue by skaic** [laruence/yaf#92]
[yaf]
application.directory=APPLICATION_PATH "/application"
application.library=APPLICATION_PATH "/application/library"
application.modules="Index,Test"
application.dispatcher.defaultModule="Test"

设置默认Module = “Test” 后，

访问 “http://yaf.me/” 或 “http://yaf.me/test/index/index” 都会访问到 Index 模块里

**Comment by loncool** [comment]
我也被这个问题坑了 一下午。。哎。

**Comment by lagolas** [comment]
请问，最后咋解决啊这个？？？
